Repository Automattic/simplenote-ios, pull requests merged in 2019-06, with the labels that each got.

#321 Use a tagged version of Tracks
  Podfile
  Podfile.lock
Labels: tooling

#320 Enhanced Sort Options
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcworkspace/contents.xcworkspacedata
  Simplenote/Classes/SPDefaultTableViewCell.swift
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPNotifications.h
  Simplenote/Classes/SPNotifications.m
  Simplenote/Classes/SPOptionsViewController.h
  Simplenote/Classes/SPOptionsViewController.m
  Simplenote/Classes/SPSortOrderViewController.swift
  Simplenote/Classes/SPTableViewCell.m
  Simplenote/Classes/SPTracker.h
  Simplenote/Classes/SPTracker.m
  Simplenote/Classes/SortMode.swift
  Simplenote/Classes/UserDefaults+Simplenote.swift
  Simplenote/Options.swift
  Simplenote/SPAppDelegate.m
  Simplenote/Simplenote-Bridging-Header.h
  Simplenote/VSTheme+Keys.swift
Labels: enhancement

#324 Share Extension: Fixing Keychain Access Groups
  SimplenoteShare/SimplenoteShare-Development.entitlements
  SimplenoteShare/SimplenoteShare-Internal.entitlements
Labels: bug

#328 Adding TextBundleWrapper
  Simplenote.xcodeproj/project.pbxproj
  SimplenoteShare/Simplenote-Share-Bridging-Header.h
  SimplenoteShare/Tools/TextBundleWrapper.h
  SimplenoteShare/Tools/TextBundleWrapper.m
Labels: enhancement

#325 Share Extension: TextBundle Support
  Podfile
  Podfile.lock
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcworkspace/contents.xcworkspacedata
  SimplenoteShare/Extensions/NSExtensionContext+Simplenote.swift
  SimplenoteShare/Extensions/NSURLSessionConfiguration+Extensions.swift
  SimplenoteShare/Extractors/Extractor.swift
  SimplenoteShare/Extractors/Extractors.swift
  SimplenoteShare/Extractors/PlainTextExtractor.swift
  SimplenoteShare/Extractors/URLExtractor.swift
  SimplenoteShare/Info.plist
  SimplenoteShare/ShareViewController.swift
  SimplenoteShare/Simperium/Note.swift
  SimplenoteShare/Simperium/Uploader.swift
  SimplenoteShare/ViewControllers/ShareViewController.swift
Labels: enhancement

#329 Login goes Safe Insets!
  Podfile
  Podfile.lock
  Simplenote/Classes/SPLoginViewController.m
  Simplenote/Classes/UserDefaults+Simplenote.swift
  Simplenote/VSTheme+Keys.swift
Labels: enhancement

#331 Use dynamic type styles + increase editor line spacing
  Simplenote/Classes/SPActionButton.m
  Simplenote/Classes/SPActionSheet.m
  Simplenote/Classes/SPActivityView.m
  Simplenote/Classes/SPEmptyListView.m
  Simplenote/Classes/SPEntryListCell.m
  Simplenote/Classes/SPEntryListViewController.m
  Simplenote/Classes/SPHorizontalPickerView.m
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPRatingsPromptView.m
  Simplenote/Classes/SPTableViewCell.m
  Simplenote/Classes/SPTagEntryField.m
  Simplenote/Classes/SPTagListViewCell.m
  Simplenote/Classes/SPTagPill.m
  Simplenote/Classes/SPTagsListViewController.m
  Simplenote/Classes/SPTransitionController.m
  Simplenote/Classes/SPVersionPickerViewCell.m
  Simplenote/Classes/UIBarButtonItem+Images.m
  Simplenote/DB5/VSThemeManager.m
  Simplenote/Simplenote-DB5.plist
Labels: [feature] editor, task

#332 Add get_pullrequests_list lane
  fastlane/Fastfile
  fastlane/env.example
Labels: tooling

#335 Add metadata translations
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/en.lproj/Localizable.strings
  fastlane/Fastfile
  fastlane/actions/ios_update_metadata_source.rb
  fastlane/appstoreres/metadata/source/description.txt
  fastlane/appstoreres/metadata/source/keywords.txt
  fastlane/appstoreres/metadata/source/subtitle.txt
Labels: tooling

#337 Siri Shortcuts
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/ActivityType.swift
  Simplenote/Classes/NSUserActivity+Shortcuts.swift
  Simplenote/Classes/NSUserActivity+Simplenote.swift
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/ShortcutsHandler.swift
  Simplenote/SPAppDelegate.h
  Simplenote/SPAppDelegate.m
  Simplenote/SPPrivacyViewController.swift
  Simplenote/Simplenote-Bridging-Header.h
  Simplenote/Simplenote-Info.plist
Labels: enhancement
