Repository Automattic/simplenote-ios, pull requests merged in 2019-05, with the labels that each got.

#298 Update GitHub Templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/---bug-report.md
  .github/ISSUE_TEMPLATE/---feature-request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: tooling

#299 Updated README.md
  CONTRIBUTING.md
  README.md
Labels: task

#300 Added build tooling + XCode 10.2/Swift 5 updates
  .bundle/config
  .gitignore
  External/DTPinLock/DTTwoPageViewController.m
  Gemfile
  Gemfile.lock
  Podfile
  Podfile.lock
  README.md
  Rakefile
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcodeproj/xcshareddata/xcschemes/Simplenote.xcscheme
  Simplenote/Classes/SPAboutViewController.swift
  Simplenote/Classes/SPActionSheet.m
  Simplenote/Classes/SPActivityView.m
  Simplenote/Classes/SPAddCollaboratorsViewController.m
  Simplenote/Classes/SPHorizontalPickerView.m
  Simplenote/Classes/SPIntegrityHelper.m
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPSidebarContainerViewController.m
  Simplenote/Classes/SPTagEntryField.m
  Simplenote/Classes/SPTagPill.m
  Simplenote/Classes/SPTagView.m
  Simplenote/Classes/SPTagsListViewController.m
  Simplenote/Classes/SPTextView.m
  Simplenote/Classes/SPTitleView.swift
  Simplenote/Classes/SPTransitionSnapshot.m
  Simplenote/Classes/SPVersionPickerViewCell.m
  Simplenote/Classes/UIAlertController+Helpers.swift
  Simplenote/SPAppDelegate.m
  Simplenote/SPPrivacyViewController.swift
  SimplenoteShare/ShareViewController.swift
Labels: task, tooling

#302 Adds .bundle/config file
  .bundle/config
  .gitignore
Labels: tooling

#301 Add fastlane and the secret store
  .configure
  Gemfile
  Gemfile.lock
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: tooling

#308 Updates Simperium lib from 0.8.19 to 0.8.21
  Podfile
  Podfile.lock
Labels: debt, task

#314 Markdown Preview: Fixing Anchor Links Crash
  Simplenote/Classes/SPMarkdownPreviewViewController.m
Labels: crash

#304 Add Sentry Support
  .configure
  Podfile
  Podfile.lock
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/BuildConfiguration.swift
  Simplenote/CrashLogging.swift
  Simplenote/Preferences.m
  Simplenote/SPAppDelegate.m
  Simplenote/SPCredentials.swift
  Simplenote/SPPrivacyViewController.swift
Labels: tooling

#315 Fixing Warnings!
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPOnboardingViewController.m
  Simplenote/SPAppDelegate.m
Labels: debt

#317 Add configuration for Hound and Swiftlint
  .hound.yml
  .swiftlint.yml
Labels: tooling
