Repository Automattic/simplenote-ios, pull requests merged in 2019-12, with the labels that each got.

#536 Search: Wiring Results
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/FeatureManager.swift
  Simplenote/Classes/Note.h
  Simplenote/Classes/Note.m
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPNoteTableViewCell.swift
  Simplenote/Classes/SPSearchResultsController.swift
  Simplenote/Classes/SPSearchResultsViewController.swift
  Simplenote/Classes/SPSearchResultsViewController.xib
  Simplenote/Classes/UIView+Animations.swift
Labels: [feature] search

#550 Fixing Add Collaborators UI
  RELEASE-NOTES.txt
  Simplenote/Classes/SPAddCollaboratorsViewController.m
Labels: bug

#543 Add configure to rake dependencies
  .configure
  Rakefile
Labels: tooling

#551 Release/4.14.1
  RELEASE-NOTES.txt
  Simplenote/Classes/SPAddCollaboratorsViewController.m
  config/Version.Public.xcconfig
  fastlane/Deliverfile
Labels: releases

#552 Merge release 4.14.1 into develop
  RELEASE-NOTES.txt
  Simplenote/Classes/SPAddCollaboratorsViewController.m
  config/Version.Public.xcconfig
  fastlane/Deliverfile
Labels: releases

#554 Feature/add match signing
  .configure
  .gitignore
  Simplenote.xcodeproj/project.pbxproj
  fastlane/Fastfile
  fastlane/Matchfile
  fastlane/env.example
  fastlane/env/project.env-example
  fastlane/env/user.env-example
Labels: tooling

#547 Fixing warnings
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcodeproj/xcshareddata/xcschemes/Simplenote.xcscheme
  Simplenote/Classes/Note.h
  Simplenote/Preferences.m
Labels: debt

#538 SearchResultsViewController: KeyboardObservable
  Simplenote/Classes/SPSearchResultsViewController.swift
Labels: [feature] search

#539 Search: Dismissing Keyboard upon scroll
  Simplenote/Classes/SPSearchController.swift
  Simplenote/Classes/SPSearchResultsViewController.swift
Labels: [feature] search

#557 Fix: Surrogate Pairs (Mark II)
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: [priority] high, crash

#561 Updates Simperium to Mark 0.8.26
  Podfile
  Podfile.lock
Labels: [priority] high

#562 Merge Release/4.14.2 into develop
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  config/Version.Public.xcconfig
  fastlane/Deliverfile
Labels: releases

#563 Merge release 4.14.2 into master
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  config/Version.Public.xcconfig
  fastlane/Deliverfile
Labels: releases
