Repository Automattic/simplenote-ios, pull requests merged in 2019-10, with the labels that each got.

#438 Updating WordPress-AppBot dependency
  Podfile
  Podfile.lock
Labels: debt

#420 Styling Search Bar
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPNavigationController.m
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController.h
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPRatingsPromptView.m
  Simplenote/Classes/SPSidebarContainerViewController.h
  Simplenote/Classes/UIBezierPath+Simplenote.swift
  Simplenote/Classes/UIColor+Helpers.swift
  Simplenote/Classes/UIColorName.swift
  Simplenote/Classes/UIImage+Dynamic.swift
  Simplenote/Classes/UIImageName.swift
  Simplenote/Classes/UIKitConstants.swift
  Simplenote/Classes/UITraitCollection+Simplenote.swift
  Simplenote/Classes/UIView+Simplenote.swift
  Simplenote/Classes/UIView+Subviews.h
  Simplenote/Classes/UIView+Subviews.m
  Simplenote/Classes/VSTheme+Keys.swift
  Simplenote/Colors.xcassets/simplenoteGray10.colorset/Contents.json
  Simplenote/DB5/VSThemeManager.m
  Simplenote/Images.xcassets/Navigation Bar/Dark/navigation_bar_shadow_dark.imageset/Contents.json
  Simplenote/Images.xcassets/Navigation Bar/Dark/navigation_bar_shadow_dark.imageset/navigation_bar_shadow_dark@2x-1.png
  Simplenote/Images.xcassets/Navigation Bar/Dark/navigation_bar_shadow_dark.imageset/navigation_bar_shadow_dark@2x.png
  Simplenote/Images.xcassets/Navigation Bar/Default/navigation_bar_shadow.imageset/Contents.json
  Simplenote/Images.xcassets/Navigation Bar/Default/navigation_bar_shadow.imageset/navigation_bar_shadow.png
  Simplenote/Images.xcassets/Navigation Bar/Default/navigation_bar_shadow.imageset/navigation_bar_shadow@2x.png
  Simplenote/Images.xcassets/Navigation Bar/Default/navigation_bar_shadow.imageset/navigation_bar_shadow_dark.png
  Simplenote/Images.xcassets/Navigation Bar/Default/navigation_bar_shadow.imageset/navigation_bar_shadow_dark@2x.png
  Simplenote/Images.xcassets/SearchBar/Contents.json
  Simplenote/Images.xcassets/SearchBar/searchbar_background.imageset/Contents.json
  Simplenote/Images.xcassets/SearchBar/searchbar_background.imageset/searchbar_background-1.png
  Simplenote/Images.xcassets/SearchBar/searchbar_background.imageset/searchbar_background.png
  Simplenote/Images.xcassets/SearchBar/searchbar_background.imageset/searchbar_background@2x-1.png
  Simplenote/Images.xcassets/SearchBar/searchbar_background.imageset/searchbar_background@2x.png
  Simplenote/Images.xcassets/SearchBar/searchbar_background_dark.imageset/Contents.json
  Simplenote/Images.xcassets/SearchBar/searchbar_background_dark.imageset/searchbar_background.png
  Simplenote/Images.xcassets/SearchBar/searchbar_background_dark.imageset/searchbar_background@2x.png
  Simplenote/SPAppDelegate.m
  Simplenote/Simplenote-DB5.plist
Labels: spring cleaning

#436 Updates Deployment Target
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPAboutViewController.swift
  Simplenote/Classes/SPActionSheet.m
  Simplenote/Classes/SPAuthViewController.swift
  Simplenote/Classes/SPEditorTextView.m
  Simplenote/Classes/SPEntryListViewController.m
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPOnboardingViewController.swift
  Simplenote/Classes/SPOptionsViewController.m
  Simplenote/Classes/SPSheetController.swift
  Simplenote/Classes/SPSidebarContainerViewController.m
  Simplenote/Classes/SPTagsListViewController.m
  Simplenote/Classes/SPTransitionController.m
  Simplenote/NSMutableAttributedString+Styling.m
Labels: debt

#441 Fixing Darkness
  RELEASE-NOTES.txt
  Simplenote/Classes/SPInteractiveTextStorage.m
  Simplenote/Classes/SPNoteEditorViewController.h
  Simplenote/Classes/SPNoteEditorViewController.m
Labels: bug

#440 Splitting Notes List Initializer
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController.h
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPSidebarContainerViewController.h
  Simplenote/Classes/SPSidebarContainerViewController.m
  Simplenote/Classes/SPTagsListViewController.m
  Simplenote/Classes/UISearchBar+Simplenote.swift
  Simplenote/SPConstants.h
  Simplenote/SPConstants.m
Labels: debt

#432 Search Controller: Spring Cleaning
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPBorderedTableView.m
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController.h
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPSearchController.swift
  Simplenote/Classes/SPTitleView.swift
  Simplenote/Classes/SPTransitionController.m
  Simplenote/Classes/UIImage+Dynamic.swift
  Simplenote/DB5/VSThemeManager.m
Labels: spring cleaning

#443 Search Controller: Merging to *develop*
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPBorderedTableView.m
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController.h
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPSearchController.swift
  Simplenote/Classes/SPTitleView.swift
  Simplenote/Classes/SPTransitionController.m
  Simplenote/Classes/UIImage+Dynamic.swift
  Simplenote/DB5/VSThemeManager.m
Labels: task

#445 Release/4.11
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: releases

#444 Fixing Search Results Highlight
  RELEASE-NOTES.txt
  Simplenote/Classes/NSTextStorage+Highlight.h
  Simplenote/Classes/NSTextStorage+Highlight.m
  Simplenote/Classes/SPNoteEditorViewController.h
  Simplenote/Classes/SPNoteEditorViewController.m
Labels: bug

#454 Ensuring First Row is always visible at launch
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController.m
Labels: bug

#449 Simplifying UIImageName Innerworkings
  Simplenote/Classes/UIImage+Simplenote.swift
  Simplenote/Classes/UIImageName.swift
  Simplenote/Classes/VSTheme+Keys.swift
  Simplenote/DB5/VSTheme.h
  Simplenote/DB5/VSTheme.m
  Simplenote/Images.xcassets/Navigation Bar/Contents.json
  Simplenote/Images.xcassets/Navigation Bar/Dark/navigation_bar_background_landscape_prompt_dark.imageset/navigation_bar_background_landscape_prompt_dark.png
  Simplenote/Images.xcassets/Navigation Bar/Dark/navigation_bar_background_landscape_prompt_dark.imageset/navigation_bar_background_landscape_prompt_dark@2x.png
  Simplenote/Images.xcassets/Navigation Bar/Dark/navigation_bar_background_prompt_dark.imageset/Contents.json
  Simplenote/Images.xcassets/Navigation Bar/Default/Contents.json
  Simplenote/Images.xcassets/Navigation Bar/Default/navigation_bar_background_landscape_prompt.imageset/Contents.json
  Simplenote/Images.xcassets/Navigation Bar/Default/navigation_bar_background_landscape_prompt.imageset/navigation_bar_background_landscape_prompt.png
  Simplenote/Images.xcassets/Navigation Bar/Default/navigation_bar_background_landscape_prompt.imageset/navigation_bar_background_landscape_prompt@2x.png
  Simplenote/Images.xcassets/Navigation Bar/Default/navigation_bar_background_landscape_prompt.imageset/navigation_bar_background_landscape_prompt_dark.png
  Simplenote/Images.xcassets/Navigation Bar/Default/navigation_bar_background_landscape_prompt.imageset/navigation_bar_background_landscape_prompt_dark@2x.png
  Simplenote/Images.xcassets/Navigation Bar/navigation_bar_background.imageset/Contents.json
  Simplenote/Images.xcassets/Navigation Bar/navigation_bar_background.imageset/background_navigationBar@2x.png
  Simplenote/Images.xcassets/Navigation Bar/navigation_bar_background.imageset/background_navigationBar_dark.png
  Simplenote/Images.xcassets/Navigation Bar/navigation_bar_background.imageset/background_navigationBar_dark@2x.png
  Simplenote/Images.xcassets/Navigation Bar/navigation_bar_background.imageset/navigation_bar_background.png
  Simplenote/Images.xcassets/Navigation Bar/navigation_bar_background_dark.imageset/Contents.json
  Simplenote/Images.xcassets/Navigation Bar/navigation_bar_background_dark.imageset/background_navigationBar_dark.png
  Simplenote/Images.xcassets/Navigation Bar/navigation_bar_background_dark.imageset/background_navigationBar_dark@2x.png
  Simplenote/Images.xcassets/Navigation Bar/navigation_bar_background_prompt.imageset/Contents.json
  Simplenote/Images.xcassets/Navigation Bar/navigation_bar_background_prompt.imageset/navigation_bar_background_prompt.png
  Simplenote/Images.xcassets/Navigation Bar/navigation_bar_background_prompt.imageset/navigation_bar_background_prompt@2x.png
  Simplenote/Images.xcassets/Navigation Bar/navigation_bar_background_prompt.imageset/navigation_bar_background_prompt_dark.png
  Simplenote/Images.xcassets/Navigation Bar/navigation_bar_background_prompt.imageset/navigation_bar_background_prompt_dark@2x.png
  Simplenote/Images.xcassets/Navigation Bar/navigation_bar_background_prompt_dark.imageset/Contents.json
  Simplenote/Images.xcassets/Navigation Bar/navigation_bar_background_prompt_dark.imageset/navigation_bar_background_prompt_dark.png
  Simplenote/Images.xcassets/Navigation Bar/navigation_bar_background_prompt_dark.imageset/navigation_bar_background_prompt_dark@2x.png
  Simplenote/Simplenote-DB5.plist
Labels: debt, spring cleaning

#451 Adding Missing UIImageName Cases
  Simplenote/Classes/SPAuthViewController.swift
  Simplenote/Classes/SPEntryListCell.m
  Simplenote/Classes/SPEntryListViewController.m
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPTagPill.m
  Simplenote/Classes/SPTagsListViewController.m
  Simplenote/Classes/SnapshotRenderer.swift
  Simplenote/Classes/UIBarButtonItem+Images.m
  Simplenote/Classes/UIImageName.swift
  Simplenote/DB5/VSThemeManager.m
  Simplenote/Images.xcassets/Icons/icon_add.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_allnotes.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_settings.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_task_checked.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_task_unchecked.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_trash.imageset/Contents.json
Labels: debt, spring cleaning

#466 Fixing Dark Mode Glitch
  Simplenote/Classes/SPNoteEditorViewController.m
Labels: bug

#460 Tags List Refresh: Mark I
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPTagListViewCell.h
  Simplenote/Classes/SPTagListViewCell.m
  Simplenote/Classes/SPTagsListViewController.h
  Simplenote/Classes/SPTagsListViewController.m
  Simplenote/Classes/SPTagsListViewController.xib
  Simplenote/SPAppDelegate.m
  Simplenote/Simplenote-DB5.plist
Labels: spring cleaning

#464 Tags List Refresh: Mark II
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPTagHeaderView.swift
  Simplenote/Classes/SPTagHeaderView.xib
  Simplenote/Classes/SPTagListViewCell.h
  Simplenote/Classes/SPTagListViewCell.m
  Simplenote/Classes/SPTagListViewCell.xib
  Simplenote/Classes/SPTagsListViewController.h
  Simplenote/Classes/SPTagsListViewController.m
  Simplenote/Classes/SPTagsListViewController.xib
  Simplenote/Classes/UIImageName.swift
  Simplenote/Classes/UIKitConstants.swift
  Simplenote/Classes/UIView+Simplenote.swift
  Simplenote/Images.xcassets/Icons/icon_tag.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_tag.imageset/icon_tag.pdf
  Simplenote/Simplenote-Bridging-Header.h
  Simplenote/Simplenote-DB5.plist
Labels: spring cleaning

#467 Tags List Refresh: Mark III
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/NSPredicate+Simplenote.swift
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController.h
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPTagsListViewController.m
  Simplenote/Classes/SPTracker.h
  Simplenote/Classes/SPTracker.m
  Simplenote/Classes/UIImageName.swift
  Simplenote/Images.xcassets/Icons/icon_untagged.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_untagged.imageset/icon_untagged.pdf
  Simplenote/SPConstants.h
  Simplenote/SPConstants.m
  SimplenoteTests/NSPredicateSimplenoteTests.swift
Labels: spring cleaning

#473 Merge release 4.11 into develop
  RELEASE-NOTES.txt
  Simplenote/Classes/SPEditorTextView.h
  Simplenote/Classes/SPEditorTextView.m
  Simplenote/Classes/SPNoteEditorViewController.h
  Simplenote/Classes/SPNoteEditorViewController.m
  config/Version.Public.xcconfig
Labels: releases

#482 Updates Authentication Strings
  Simplenote/Classes/SPOnboardingViewController.swift
Labels: enhancement

#469 Sidebar: Spring Cleaning
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPBorderedTableView.h
  Simplenote/Classes/SPBorderedTableView.m
  Simplenote/Classes/SPBorderedView.h
  Simplenote/Classes/SPBorderedView.m
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController.h
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPSidebarContainerViewController.h
  Simplenote/Classes/SPSidebarContainerViewController.m
  Simplenote/Classes/SPSidebarViewController.h
  Simplenote/Classes/SPSidebarViewController.m
  Simplenote/Classes/SPTagListViewCell.xib
  Simplenote/Classes/SPTagsListViewController.h
  Simplenote/Classes/SPTagsListViewController.m
  Simplenote/Classes/SPTagsListViewController.xib
  Simplenote/Classes/UIGestureRecognizer+Simplenote.swift
  Simplenote/Classes/UIScreen+Simplenote.swift
  Simplenote/Classes/UITableView+Simplenote.swift
  Simplenote/Classes/UITableView+Styling.h
  Simplenote/Classes/UITableView+Styling.m
  Simplenote/Classes/UIView+Simplenote.swift
  Simplenote/SPAppDelegate.h
  Simplenote/SPAppDelegate.m
  Simplenote/Simplenote-DB5.plist
Labels: spring cleaning

#496 Disabling Peek and Pop in Trash
  RELEASE-NOTES.txt
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController.h
  Simplenote/Classes/SPNoteListViewController.m
Labels: bug

#492 Merge Release/4.12 into Develop
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  config/Version.Public.xcconfig
Labels: releases

#484 TransitionController: Nukes Magic Numbers
  Simplenote/Classes/SPTransitionController.h
  Simplenote/Classes/SPTransitionController.m
Labels: debt

#497 Fixing Swipe to Dismiss
  RELEASE-NOTES.txt
  Simplenote/Classes/SPInteractivePushPopAnimationController.h
  Simplenote/Classes/SPInteractivePushPopAnimationController.m
Labels: bug

#483 Color Studio: Mark I
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/ColorStudio.swift
  Simplenote/Classes/SPAuthViewController.swift
  Simplenote/Classes/SPOnboardingViewController.swift
  Simplenote/Classes/SPSheetController.swift
  Simplenote/Classes/SPTagHeaderView.swift
  Simplenote/Classes/SPTagListViewCell.m
  Simplenote/Classes/SPTextInputView.swift
  Simplenote/Classes/UIColor+Helpers.swift
  Simplenote/Classes/UIColor+Studio.swift
  Simplenote/Classes/UIColorName.swift
  Simplenote/Classes/UIImage+Dynamic.swift
  Simplenote/Classes/VSTheme+Keys.swift
  Simplenote/Colors.xcassets/searchBarImageColor.colorset/Contents.json
  Simplenote/Colors.xcassets/simplenoteAlmostBlack.colorset/Contents.json
  Simplenote/Colors.xcassets/simplenoteDeepSeaBlue.colorset/Contents.json
  Simplenote/Colors.xcassets/simplenoteGray10.colorset/Contents.json
  Simplenote/Colors.xcassets/simplenoteGray50.colorset/Contents.json
  Simplenote/Colors.xcassets/simplenoteGunmetal.colorset/Contents.json
  Simplenote/Colors.xcassets/simplenoteLightNavy.colorset/Contents.json
  Simplenote/Colors.xcassets/simplenoteLightPink.colorset/Contents.json
  Simplenote/Colors.xcassets/simplenoteLipstick.colorset/Contents.json
  Simplenote/Colors.xcassets/simplenoteMidBlue.colorset/Contents.json
  Simplenote/Colors.xcassets/simplenotePalePurple.colorset/Contents.json
  Simplenote/Colors.xcassets/simplenoteSlateGrey.colorset/Contents.json
  Simplenote/Simplenote-DB5.plist
Labels: debt

#498 Fixing StatusBar Color
  RELEASE-NOTES.txt
  Simplenote/SPAppDelegate.m
Labels: bug

#490 Bugfix: UI Freeze!
  Simplenote/Classes/SPNoteListViewController.h
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPSearchController.swift
  Simplenote/Classes/SPTransitionController.m
Labels: [priority] high, bug

#500 Enables Preserve Vector Data flag in assets
  Simplenote/Images.xcassets/Icons/icon_add.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_allnotes.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_arrow_top_right.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_checklist.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_chevron_left.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_chevron_right.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_collaborate.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_hide_keyboard.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_history.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_info.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_menu.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_new_note.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_onepassword.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_pin.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_settings.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_share.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_shared.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_tag.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_trash.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_untagged.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_user.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_visibility_off.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_visibility_on.imageset/Contents.json
Labels: enhancement

#502 Fixing Rotation Bug
  Simplenote/Classes/SPSidebarContainerViewController.m
  Simplenote/Classes/SPTagsListViewController.xib
Labels: bug

#503 Preventing Interactive Animation Race Condition
  Simplenote/Classes/SPSidebarContainerViewController.m
Labels: bug

#505 Bugfix: Dark Mode Regression (iOS 11)
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPSidebarContainerViewController.m
Labels: bug

#494 Color Studio: Mark II
  External/DTPinLock/DTPinLockController.m
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/ColorStudio.swift
  Simplenote/Classes/SPActionSheet.m
  Simplenote/Classes/SPActivityView.m
  Simplenote/Classes/SPEditorTextView.m
  Simplenote/Classes/SPEntryListViewController.m
  Simplenote/Classes/SPHorizontalPickerGradientView.m
  Simplenote/Classes/SPHorizontalPickerView.m
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPNoteTableViewCell.swift
  Simplenote/Classes/SPOptionsViewController.m
  Simplenote/Classes/SPRatingsPromptView.m
  Simplenote/Classes/SPTableViewController.m
  Simplenote/Classes/SPTagsListViewController.m
  Simplenote/Classes/SPTextView.m
  Simplenote/Classes/SnapshotRenderer.swift
  Simplenote/Classes/UIColor+Studio.swift
  Simplenote/Classes/UIColorName.swift
  Simplenote/Classes/UITableView+Styling.m
  Simplenote/Classes/VSTheme+Keys.swift
  Simplenote/Colors.xcassets/destructiveActionColor.colorset/Contents.json
  Simplenote/Colors.xcassets/dividerColor.colorset/Contents.json
  Simplenote/Colors.xcassets/horizontalPickerBorderColor.colorset/Contents.json
  Simplenote/Colors.xcassets/horizontalPickerTitleFontColor.colorset/Contents.json
  Simplenote/Colors.xcassets/lockBackgroundColor.colorset/Contents.json
  Simplenote/Colors.xcassets/lockTextColor.colorset/Contents.json
  Simplenote/Colors.xcassets/navigationBarTitleFontColor.colorset/Contents.json
  Simplenote/Colors.xcassets/noteBodyFontPreviewColor.colorset/Contents.json
  Simplenote/Colors.xcassets/noteHeadlineFontColor.colorset/Contents.json
  Simplenote/Colors.xcassets/searchHighlightFontColor.colorset/Contents.json
  Simplenote/Colors.xcassets/secondaryActionColor.colorset/Contents.json
  Simplenote/Colors.xcassets/switchOnTintColor.colorset/Contents.json
  Simplenote/Colors.xcassets/switchTintColor.colorset/Contents.json
  Simplenote/Colors.xcassets/tertiaryActionColor.colorset/Contents.json
  Simplenote/DB5/VSThemeManager.m
  Simplenote/SPPrivacyViewController.swift
  Simplenote/Simplenote-DB5.plist
  SimplenoteShare/Themes/SPUserInterface.swift
  SimplenoteShare/ViewControllers/SharePresentationController.swift
Labels: spring cleaning
