Repository Automattic/simplenote-ios, pull requests merged in 2019-09, with the labels that each got.

#416 Notes List Cell + Autolayout
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/NSTextStorage+Highlight.h
  Simplenote/Classes/NSTextStorage+Highlight.m
  Simplenote/Classes/SPInteractiveTextStorage.h
  Simplenote/Classes/SPNoteListViewController.h
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPNoteTableViewCell.swift
  Simplenote/Classes/SPNoteTableViewCell.xib
  Simplenote/Classes/SPOptionsViewController.h
  Simplenote/Classes/SPOptionsViewController.m
  Simplenote/Classes/SPTableViewCell.h
  Simplenote/Classes/SPTableViewCell.m
  Simplenote/Classes/SPTransitionController.m
  Simplenote/Classes/SnapshotRenderer.swift
  Simplenote/Classes/UITableViewCell+Simplenote.swift
  Simplenote/Classes/UIView+Simplenote.swift
  Simplenote/Classes/UserDefaults+Simplenote.swift
  Simplenote/Options.swift
Labels: debt

#422 Hotfix: System theme Issue
  Simplenote/Options.swift
  Simplenote/SPAppDelegate.m
Labels: bug

#425 Fixing Search Race Condition
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
Labels: bug

#411 Spring Cleaning: Refreshing Note Cell
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcodeproj/xcshareddata/xcschemes/Simplenote.xcscheme
  Simplenote/Classes/NSAttributedString+Styling.h
  Simplenote/Classes/NSAttributedString+Styling.m
  Simplenote/Classes/SPEditorTextView.m
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteListViewController.h
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPNoteTableViewCell.swift
  Simplenote/Classes/SPNoteTableViewCell.xib
  Simplenote/Classes/SPOptionsViewController.m
  Simplenote/Classes/SPTextView.h
  Simplenote/Classes/SPTextView.m
  Simplenote/Classes/SPTransitionController.m
  Simplenote/Classes/SnapshotRenderer.swift
  Simplenote/Classes/UIKitConstants.swift
  Simplenote/Classes/UIView+ImageRepresentation.h
  Simplenote/Classes/UIView+ImageRepresentation.m
  Simplenote/Classes/UIView+ImageRepresentation.swift
  Simplenote/Images.xcassets/Icons/icon_pin.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_pin.imageset/icon_pin.pdf
  Simplenote/Images.xcassets/Icons/icon_pin.imageset/icon_pin.png
  Simplenote/Images.xcassets/Icons/icon_pin.imageset/icon_pin@2x.png
  Simplenote/Images.xcassets/Icons/icon_shared.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_shared.imageset/icon_shared.pdf
  Simplenote/Images.xcassets/Icons/icon_shared.imageset/icon_shared@1x.png
  Simplenote/Images.xcassets/Icons/icon_shared.imageset/icon_shared@2x.png
  Simplenote/Images.xcassets/Icons/icon_shared.imageset/icon_shared@3x.png
  Simplenote/SPAppDelegate.m
  Simplenote/Simplenote-Bridging-Header.h
Labels: Spring Cleaning

#419 Nukes IS_XCODE_11 guards
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPActivityView.m
  Simplenote/Classes/SPBorderedTableView.m
  Simplenote/Classes/SPHorizontalPickerGradientView.m
  Simplenote/Classes/SPMarkdownPreviewViewController.m
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPOnboardingViewController.swift
  Simplenote/Classes/SPUserInterface.swift
  Simplenote/Classes/SnapshotRenderer.swift
  Simplenote/SPConstants.h
  SimplenoteTests/UIColorSimplenoteTests.swift
  config/SDKVersions.xcconfig
  config/Simplenote.debug.xcconfig
  config/Simplenote.release.xcconfig
Labels: debt

#434 Merge Release/4.10.1 into Master
  Gemfile
  Gemfile.lock
  Podfile.lock
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  config/Version.Public.xcconfig
  fastlane/Deliverfile
Labels: Releases

#427 Note List Cell: New Metrics!
  Simplenote/Classes/NSString+Condensing.h
  Simplenote/Classes/NSString+Condensing.m
  Simplenote/Classes/Note.h
  Simplenote/Classes/Note.m
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPNoteTableViewCell.swift
  Simplenote/Classes/SPNoteTableViewCell.xib
  Simplenote/Classes/SPTransitionController.m
  Simplenote/Classes/SnapshotRenderer.swift
  Simplenote/Simplenote-Bridging-Header.h
  Simplenote/Simplenote-DB5.plist
Labels: Spring Cleaning, enhancement
