Repository Automattic/simplenote-ios, pull requests merged in 2019-11, with the labels that each got.

#499 Updates Log Out Strings
  Simplenote/Classes/SPOptionsViewController.m
Labels: enhancement

#509 Merge release 4.12 into develop
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteListViewController.h
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPSearchController.swift
  Simplenote/Classes/SPSidebarContainerViewController.m
  Simplenote/Classes/SPTagsListViewController.xib
  Simplenote/Classes/SPTransitionController.m
  Simplenote/Images.xcassets/Icons/icon_add.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_allnotes.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_arrow_top_right.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_checklist.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_chevron_left.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_chevron_right.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_collaborate.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_hide_keyboard.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_history.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_info.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_menu.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_new_note.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_onepassword.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_pin.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_settings.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_share.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_shared.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_tag.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_trash.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_untagged.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_user.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_visibility_off.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_visibility_on.imageset/Contents.json
  config/Version.Public.xcconfig
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: releases

#485 Navigation Bar Blur
  External/DTPinLock/DTPinLockController.h
  External/DTPinLock/DTPinLockController.m
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPAuthViewController.swift
  Simplenote/Classes/SPMarkdownPreviewViewController.m
  Simplenote/Classes/SPNavigationController.h
  Simplenote/Classes/SPNavigationController.m
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController.h
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPOnboardingViewController.swift
  Simplenote/Classes/SPSearchController.swift
  Simplenote/Classes/SPTransitionController.m
  Simplenote/Classes/SPVisualEffectView.swift
  Simplenote/Classes/UIBlurEffect+Simplenote.swift
  Simplenote/Classes/UIImageName.swift
  Simplenote/Classes/UINavigationBar+Simplenote.swift
  Simplenote/Classes/UISearchBar+Simplenote.swift
  Simplenote/DB5/VSThemeManager.m
  Simplenote/Images.xcassets/Navigation Bar/Contents.json
  Simplenote/Images.xcassets/Navigation Bar/navigation_bar_background.imageset/Contents.json
  Simplenote/Images.xcassets/Navigation Bar/navigation_bar_background.imageset/background_navigationBar@2x.png
  Simplenote/Images.xcassets/Navigation Bar/navigation_bar_background.imageset/background_navigationBar_dark.png
  Simplenote/Images.xcassets/Navigation Bar/navigation_bar_background.imageset/background_navigationBar_dark@2x.png
  Simplenote/Images.xcassets/Navigation Bar/navigation_bar_background.imageset/navigation_bar_background.png
  Simplenote/Images.xcassets/Navigation Bar/navigation_bar_background_dark.imageset/Contents.json
  Simplenote/Images.xcassets/Navigation Bar/navigation_bar_background_dark.imageset/background_navigationBar_dark.png
  Simplenote/Images.xcassets/Navigation Bar/navigation_bar_background_dark.imageset/background_navigationBar_dark@2x.png
  Simplenote/Images.xcassets/Navigation Bar/navigation_bar_background_prompt.imageset/Contents.json
  Simplenote/Images.xcassets/Navigation Bar/navigation_bar_background_prompt.imageset/navigation_bar_background_prompt.png
  Simplenote/Images.xcassets/Navigation Bar/navigation_bar_background_prompt.imageset/navigation_bar_background_prompt@2x.png
  Simplenote/Images.xcassets/Navigation Bar/navigation_bar_background_prompt.imageset/navigation_bar_background_prompt_dark.png
  Simplenote/Images.xcassets/Navigation Bar/navigation_bar_background_prompt.imageset/navigation_bar_background_prompt_dark@2x.png
  Simplenote/Images.xcassets/Navigation Bar/navigation_bar_background_prompt_dark.imageset/Contents.json
  Simplenote/Images.xcassets/Navigation Bar/navigation_bar_background_prompt_dark.imageset/navigation_bar_background_prompt_dark.png
  Simplenote/Images.xcassets/Navigation Bar/navigation_bar_background_prompt_dark.imageset/navigation_bar_background_prompt_dark@2x.png
  Simplenote/SPAppDelegate.m
Labels: spring cleaning

#514 Merge Release/4.13 into develop
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: releases

#506 Color Studio: Mark III
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/ColorStudio.swift
  Simplenote/Classes/SPActionButton.m
  Simplenote/Classes/SPActionSheet.m
  Simplenote/Classes/SPActivityView.m
  Simplenote/Classes/SPDebugViewController.m
  Simplenote/Classes/SPDefaultTableViewCell.swift
  Simplenote/Classes/SPEntryListCell.m
  Simplenote/Classes/SPEntryListViewController.m
  Simplenote/Classes/SPHorizontalPickerGradientView.m
  Simplenote/Classes/SPHorizontalPickerView.m
  Simplenote/Classes/SPMarkdownPreviewViewController.m
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPNoteTableViewCell.swift
  Simplenote/Classes/SPOptionsViewController.m
  Simplenote/Classes/SPRatingsPromptView.m
  Simplenote/Classes/SPSidebarContainerViewController.m
  Simplenote/Classes/SPSortOrderViewController.swift
  Simplenote/Classes/SPTableViewController.m
  Simplenote/Classes/SPTagHeaderView.swift
  Simplenote/Classes/SPTagListViewCell.m
  Simplenote/Classes/SPTagPill.m
  Simplenote/Classes/SPTagView.m
  Simplenote/Classes/SPTagsListViewController.m
  Simplenote/Classes/SPThemeViewController.swift
  Simplenote/Classes/SPVersionPickerViewCell.m
  Simplenote/Classes/SnapshotRenderer.swift
  Simplenote/Classes/UIBarButtonItem+Images.m
  Simplenote/Classes/UIColor+Studio.swift
  Simplenote/Classes/UIColorName.swift
  Simplenote/Classes/UISearchBar+Simplenote.swift
  Simplenote/Classes/UITableView+Simplenote.swift
  Simplenote/Classes/UITableView+Styling.h
  Simplenote/Classes/UITableView+Styling.m
  Simplenote/Classes/VSTheme+Keys.swift
  Simplenote/Colors.xcassets/backgroundColor.colorset/Contents.json
  Simplenote/Colors.xcassets/collaboratorTextColor.colorset/Contents.json
  Simplenote/Colors.xcassets/lightBlueColor.colorset/Contents.json
  Simplenote/Colors.xcassets/tableViewBackgroundColor.colorset/Contents.json
  Simplenote/Colors.xcassets/textColor.colorset/Contents.json
  Simplenote/Colors.xcassets/tintColor.colorset/Contents.json
  Simplenote/Resources/markdown-dark.css
  Simplenote/SPAppDelegate.m
  Simplenote/SPPrivacyViewController.swift
  Simplenote/Simplenote-Bridging-Header.h
  Simplenote/Simplenote-DB5.plist
  SimplenoteShare/ViewControllers/SharePresentationController.swift
Labels: spring cleaning

#512 Fixing Markdown Gestures
  RELEASE-NOTES.txt
  Simplenote/Classes/SPInteractivePushPopAnimationController.m
  Simplenote/Classes/SPMarkdownPreviewViewController.m
  Simplenote/Classes/SPTransitionController.h
  Simplenote/Classes/SPTransitionController.m
Labels: bug, groundskeeping

#516 Switch to appcenter
  .configure
  Podfile
  Podfile.lock
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/SPAppDelegate.m
  Simplenote/SPCredentials-demo.swift
  Simplenote/Simplenote-Info.plist
  fastlane/env.example
Labels: tooling

#515 Update Fastlane to upload Simplenote Internal to AppCenter
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: tooling

#519 Fixing Caret Repositioning in Authenticator
  RELEASE-NOTES.txt
  Simplenote/Classes/SPAuthViewController.swift
Labels: bug, groundskeeping

#518 Disabling Markdown Swipe during Text Selection
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPInteractivePushPopAnimationController.h
  Simplenote/Classes/SPInteractivePushPopAnimationController.m
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/UITextView+Simplenote.swift
Labels: bug, groundskeeping

#508 NavigationBar Blur Adjustments
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPBlurEffectView.swift
  Simplenote/Classes/SPMarkdownPreviewViewController.m
  Simplenote/Classes/SPNavigationController.m
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteListViewController.h
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPVisualEffectView.swift
  Simplenote/Classes/UIColor+Studio.swift
  Simplenote/Classes/UIKitConstants.swift
Labels: spring cleaning

#523 Merge release 4.13 into develop
  Gemfile.lock
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPInteractivePushPopAnimationController.h
  Simplenote/Classes/SPInteractivePushPopAnimationController.m
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/UITextView+Simplenote.swift
  config/Version.Public.xcconfig
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: releases

#525 Fix: Surrogate Pairs Crash!
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: crash

#526 Merge Release/4.13 into develop
  config/Version.Public.xcconfig
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: releases

#529 Merge Release/4.14 into develop
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: releases

#534 Disabling iOS 13 Aggressive Links Workaround
  RELEASE-NOTES.txt
  Simplenote/Classes/SPEditorTextView.h
  Simplenote/Classes/SPEditorTextView.m
  Simplenote/Classes/SPNoteEditorViewController.m
Labels: bug

#527 SearchResults: Specialized ViewController
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/FeatureManager.swift
  Simplenote/Classes/SPNoteListViewController.h
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPSearchController.swift
  Simplenote/Classes/SPSearchResultsViewController.swift
  Simplenote/Classes/SPSearchResultsViewController.xib
  Simplenote/Classes/UIView+Animations.swift
Labels: [feature] search

#537 Preferences: New Property
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Preferences.h
  Simplenote/Simplenote.xcdatamodeld/.xccurrentversion
  Simplenote/Simplenote.xcdatamodeld/Simplenote 5.xcdatamodel/contents
Labels: [feature] search

#541 Update Fastlane to the new org name in AppCenter
  fastlane/Fastfile
Labels: tooling

#542 Add localize to the code freeze lane
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: tooling

#545 Fixing Update-Translations Script
  Scripts/update-translations.rb
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/cy.lproj/Localizable.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/el.lproj/Localizable.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
Labels: [priority] high

#544 Merge Release/4.14 into develop
  Scripts/update-translations.rb
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/cy.lproj/Localizable.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/el.lproj/Localizable.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/Fastfile
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: releases
