Repository Automattic/simplenote-ios, pull requests merged in 2019-07, with the labels that each got.

#338 Display Published Icon for individual Notes
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/NSString+Search.h
  Simplenote/Classes/NSString+Search.m
  Simplenote/Classes/SPInteractivePushPopAnimationController.m
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPTableViewCell.h
  Simplenote/Classes/SPTableViewCell.m
  Simplenote/Classes/SPTransitionController.h
  Simplenote/Classes/SPTransitionController.m
  Simplenote/Classes/SnapshotRenderer.swift
  Simplenote/Classes/UIImage+Simplenote.swift
  Simplenote/Classes/UIView+Extensions.h
  Simplenote/Classes/UIView+Extensions.m
  Simplenote/Classes/UIView+Simplenote.swift
  Simplenote/Classes/VSTheme+Extensions.m
  Simplenote/Images.xcassets/Icons/icon_shared.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_shared.imageset/icon_shared@1x.png
  Simplenote/Images.xcassets/Icons/icon_shared.imageset/icon_shared@2x.png
  Simplenote/Images.xcassets/Icons/icon_shared.imageset/icon_shared@3x.png
  Simplenote/Simplenote-Bridging-Header.h
  Simplenote/VSTheme+Keys.swift
Labels: enhancement

#349 Remove the Simperium link from About
  Simplenote/Classes/SPAboutViewController.swift
Labels: [feature] settings

#347 Update the project to use external xcconfig file for versioning
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Simplenote-Info.plist
  SimplenoteShare/Info.plist
  config/Simplenote.debug.xcconfig
  config/Simplenote.release.xcconfig
  config/Version.Public.xcconfig
Labels: tooling

#348 Notes List: New Swipeable Actions
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/UIColor+Simplenote.swift
Labels: enhancement

#350 Reduce number of conflicts in RELEASE-NOTES.txt
  .gitattributes
Labels: tooling

#351 Exporting Notes: WPiOS Customized Activity Item!
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/FileManager+Simplenote.swift
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SimplenoteActivityItemSource.swift
  Simplenote/Classes/UIActivity+Simplenote.swift
  Simplenote/UIActivityViewController+Simplenote.swift
Labels: enhancement

#352 Hotfix: Sort Order Migration
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/UserDefaults+Simplenote.swift
  Simplenote/Options.swift
  SimplenoteTests/OptionsTests.swift
Labels: bug

#353 Add codefreeze automation
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: tooling

#354 Broken Settings Recovery
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/Bundle+Simplenote.swift
  Simplenote/Classes/MigrationsHandler.swift
  Simplenote/Classes/SPSortOrderViewController.swift
  Simplenote/Classes/UIAlertController+Helpers.swift
  Simplenote/Classes/UIViewController+Simplenote.swift
  Simplenote/Classes/UserDefaults+Simplenote.swift
  Simplenote/SPAppDelegate.m
  Simplenote/Simplenote-Bridging-Header.h
  Simplenote/Simplenote-Info.plist
  SimplenoteShare/Info.plist
Labels: [priority] high

#362 Issue/323 share ui
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/KeyboardObservable.swift
  Simplenote/Classes/UIColor+DarkMode.swift
  Simplenote/Classes/UIColor+Simplenote.swift
  Simplenote/Classes/UIViewController+Helpers.swift
  Simplenote/NSObject+Helpers.swift
  SimplenoteShare/Base.lproj/MainInterface.storyboard
  SimplenoteShare/Presentation/ExtensionPresentationAnimator.swift
  SimplenoteShare/Presentation/ExtensionPresentationController.swift
  SimplenoteShare/Presentation/ExtensionTransitioningManager.swift
  SimplenoteShare/ViewControllers/SharePresentationController.swift
  SimplenoteShare/ViewControllers/ShareViewController.swift
  SimplenoteShare/ViewControllers/ShareViewController.xib
Labels: [feature] sharing, enhancement

#364 Merge 4.8.1 into develop
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/Bundle+Simplenote.swift
  Simplenote/Classes/MigrationsHandler.swift
  Simplenote/Classes/SPSortOrderViewController.swift
  Simplenote/Classes/UIAlertController+Helpers.swift
  Simplenote/Classes/UIViewController+Simplenote.swift
  Simplenote/Classes/UserDefaults+Simplenote.swift
  Simplenote/Options.swift
  Simplenote/SPAppDelegate.m
  Simplenote/Simplenote-Bridging-Header.h
  SimplenoteTests/OptionsTests.swift
  config/Version.Public.xcconfig
Labels: Releases

#363 Merge Release/4.8.0 into Master
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/Bundle+Simplenote.swift
  Simplenote/Classes/MigrationsHandler.swift
  Simplenote/Classes/SPSortOrderViewController.swift
  Simplenote/Classes/UIAlertController+Helpers.swift
  Simplenote/Classes/UIViewController+Simplenote.swift
  Simplenote/Classes/UserDefaults+Simplenote.swift
  Simplenote/Options.swift
  Simplenote/SPAppDelegate.m
  Simplenote/Simplenote-Bridging-Header.h
  Simplenote/Simplenote-Info.plist
  SimplenoteShare/Info.plist
  SimplenoteTests/OptionsTests.swift
Labels: Releases

#355 Add lanes for automatic build and upload
  .gitignore
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
  fastlane/env.example
Labels: Releases

#366 Updates Cocoapods to Mk 1.7.5
  Gemfile
  Gemfile.lock
  Podfile.lock
Labels: enhancement

#370 Fix/download translations
  Scripts/update-translations.rb
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/cy.lproj/Localizable.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/el.lproj/Localizable.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
Labels: i18n

#369 Notes List: iOS 13 clipsToBounds Bugfix
  RELEASE-NOTES.txt
  Simplenote/Classes/SPTableViewCell.m
Labels: bug

#368 Dark Mode: Mark I
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPDefaultTableViewCell.swift
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SnapshotRenderer.swift
  Simplenote/Classes/UIColor+DarkMode.swift
  Simplenote/Classes/UIColor+Simplenote.swift
  Simplenote/Classes/UIColorName.swift
  Simplenote/DB5/VSThemeManager.h
  Simplenote/SPPrivacyViewController.swift
  Simplenote/Simplenote-DB5.plist
  Simplenote/VSTheme+Keys.swift
  SimplenoteShare/Extensions/UIColor+Simplenote.swift
Labels: enhancement

#373 Share Extension: First Responder Handling
  SimplenoteShare/ViewControllers/ShareViewController.swift
Labels: enhancement

#371 Dark Mode: Mark II
  External/DTPinLock/DTPinLockController.m
  Simplenote/Classes/SPActionButton.m
  Simplenote/Classes/SPActionSheet.m
  Simplenote/Classes/SPActivityView.m
  Simplenote/Classes/SPAddCollaboratorsViewController.m
  Simplenote/Classes/SPBorderedTableView.m
  Simplenote/Classes/SPEditorTextView.h
  Simplenote/Classes/SPEditorTextView.m
  Simplenote/Classes/SPEmptyListView.m
  Simplenote/Classes/SPEntryListCell.m
  Simplenote/Classes/SPEntryListViewController.m
  Simplenote/Classes/SPHorizontalPickerGradientView.m
  Simplenote/Classes/SPHorizontalPickerView.m
  Simplenote/Classes/SPMarkdownPreviewViewController.m
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPOptionsViewController.m
  Simplenote/Classes/SPRatingsPromptView.m
  Simplenote/Classes/SPSidebarContainerViewController.m
  Simplenote/Classes/SPTableViewCell.m
  Simplenote/Classes/SPTableViewController.m
  Simplenote/Classes/SPTagCompletionPill.m
  Simplenote/Classes/SPTagEntryField.m
  Simplenote/Classes/SPTagListViewCell.m
  Simplenote/Classes/SPTagPill.h
  Simplenote/Classes/SPTagPill.m
  Simplenote/Classes/SPTagView.m
  Simplenote/Classes/SPTagsListViewController.m
  Simplenote/Classes/SPTextView.m
  Simplenote/Classes/SPVersionPickerViewCell.m
  Simplenote/Classes/UIBarButtonItem+Images.m
  Simplenote/Classes/UIColorName.swift
  Simplenote/Classes/UITableView+Styling.m
  Simplenote/DB5/VSThemeManager.m
  Simplenote/SPAppDelegate.m
  Simplenote/VSTheme+Keys.swift
Labels: enhancement

#378 Share extension: Absolute URL fallback for URLExtractor.buildExternalLinkNote
  SimplenoteShare/Extractors/URLExtractor.swift
Labels: [feature] sharing, bug

#379 Merge Release/4.9 into develop
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  SimplenoteShare/Extractors/URLExtractor.swift
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases
