Repository Automattic/simplenote-ios, pull requests merged in 2019-08, with the labels that each got.

#375 Dark Mode: Mark IV
  External/DTPinLock/DTPinLockController.m
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPActionButton.h
  Simplenote/Classes/SPActionButton.m
  Simplenote/Classes/SPActionSheet.m
  Simplenote/Classes/SPActivityView.h
  Simplenote/Classes/SPActivityView.m
  Simplenote/Classes/SPBorderedTableView.m
  Simplenote/Classes/SPDefaultTableViewCell.swift
  Simplenote/Classes/SPEntryListCell.m
  Simplenote/Classes/SPEntryListViewController.m
  Simplenote/Classes/SPHorizontalPickerGradientView.h
  Simplenote/Classes/SPHorizontalPickerGradientView.m
  Simplenote/Classes/SPHorizontalPickerView.m
  Simplenote/Classes/SPMarkdownParser.m
  Simplenote/Classes/SPMarkdownPreviewViewController.m
  Simplenote/Classes/SPNavigationController.m
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPOptionsViewController.m
  Simplenote/Classes/SPRatingsPromptView.m
  Simplenote/Classes/SPTableViewCell.m
  Simplenote/Classes/SPTableViewController.m
  Simplenote/Classes/SPTagListViewCell.m
  Simplenote/Classes/SPTagPill.h
  Simplenote/Classes/SPTagPill.m
  Simplenote/Classes/SPTagView.m
  Simplenote/Classes/SPTagsListViewController.m
  Simplenote/Classes/SPUserInterface.swift
  Simplenote/Classes/SPVersionPickerViewCell.m
  Simplenote/Classes/SnapshotRenderer.swift
  Simplenote/Classes/UIBarButtonItem+Images.m
  Simplenote/Classes/UIColor+Simplenote.swift
  Simplenote/Classes/UIColorName.swift
  Simplenote/Classes/UIImage+Simplenote.swift
  Simplenote/Classes/UIImageName.swift
  Simplenote/Classes/UITableView+Styling.m
  Simplenote/Classes/VSTheme+Keys.swift
  Simplenote/Classes/VSTheme+Simplenote.h
  Simplenote/Classes/VSTheme+Simplenote.m
  Simplenote/DB5/VSTheme.h
  Simplenote/DB5/VSTheme.m
  Simplenote/DB5/VSThemeManager.m
  Simplenote/Images.xcassets/Buttons/button_delete_small.imageset/Contents.json
  Simplenote/Images.xcassets/Navigation Bar/Default/navigation_bar_background.imageset/Contents.json
  Simplenote/Images.xcassets/Navigation Bar/Default/navigation_bar_background_landscape_prompt.imageset/Contents.json
  Simplenote/Images.xcassets/Navigation Bar/Default/navigation_bar_background_prompt.imageset/Contents.json
  Simplenote/Images.xcassets/Navigation Bar/Default/navigation_bar_shadow.imageset/Contents.json
  Simplenote/Images.xcassets/SearchBar/searchbar_background.imageset/Contents.json
  Simplenote/SPConstants.h
  Simplenote/SPPrivacyViewController.swift
  Simplenote/Simplenote-DB5.plist
  Simplenote/VSTheme+Keys.swift
  SimplenoteTests/UIColorSimplenoteTests.swift
  SimplenoteTests/UIImageSimplenoteTests.swift
  config/SDKVersions.xcconfig
  config/Simplenote.debug.xcconfig
  config/Simplenote.release.xcconfig
Labels: enhancement

#380 Dark Mode: Mark V
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPNotifications.h
  Simplenote/Classes/SPNotifications.m
  Simplenote/Classes/SPOptionsViewController.m
  Simplenote/Classes/SPThemeViewController.swift
  Simplenote/Classes/SPUserInterface.swift
  Simplenote/Classes/SortMode.swift
  Simplenote/Classes/Theme.swift
  Simplenote/Classes/UserDefaults+Simplenote.swift
  Simplenote/DB5/VSThemeManager.h
  Simplenote/DB5/VSThemeManager.m
  Simplenote/Options.swift
  Simplenote/SPAppDelegate.m
  Simplenote/Simplenote-DB5.plist
  SimplenoteTests/OptionsTests.swift
  SimplenoteTests/UIColorSimplenoteTests.swift
  SimplenoteTests/UserDefaults+Tests.swift
Labels: enhancement

#372 Update Fastlane
  Gemfile
  Gemfile.lock
Labels: tooling

#383 Nü Onboarding: Mark I
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPSquaredButton.swift
  Simplenote/Classes/SPTextField.h
  Simplenote/Classes/SPTextField.m
  Simplenote/Classes/SPTextInputView.swift
  Simplenote/Classes/UIColorName.swift
  Simplenote/Classes/VSTheme+Keys.swift
  Simplenote/Colors.xcassets/simplenoteAlmostBlack.colorset/Contents.json
  Simplenote/Colors.xcassets/simplenoteLightNavy.colorset/Contents.json
  Simplenote/Colors.xcassets/simplenoteLightPink.colorset/Contents.json
  Simplenote/Colors.xcassets/simplenoteMidBlue.colorset/Contents.json
  Simplenote/Colors.xcassets/simplenotePalePurple.colorset/Contents.json
  Simplenote/Colors.xcassets/simplenoteSlateGrey.colorset/Contents.json
  Simplenote/Simplenote-Bridging-Header.h
  Simplenote/Simplenote-DB5.plist
Labels: enhancement

#387 Merge Release/4.9 into develop
  .configure
  config/Version.Public.xcconfig
  fastlane/download_metadata.swift
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#384 Nü Onboarding: Mark II
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPOnboardingViewController.h
  Simplenote/Classes/SPOnboardingViewController.m
  Simplenote/Classes/SPOnboardingViewController.swift
  Simplenote/Classes/SPOnboardingViewController.xib
  Simplenote/Classes/UIColorName.swift
  Simplenote/Classes/UIImageName.swift
  Simplenote/Classes/UINavigationBar+Simplenote.swift
  Simplenote/Classes/VSTheme+Keys.swift
  Simplenote/Colors.xcassets/simplenoteGunmetal.colorset/Contents.json
  Simplenote/Images.xcassets/Buttons/button_onepassword.imageset/Contents.json
  Simplenote/Images.xcassets/Buttons/button_onepassword.imageset/button-onepassword.png
  Simplenote/Images.xcassets/Buttons/button_onepassword.imageset/button-onepassword@2x.png
  Simplenote/Images.xcassets/Buttons/button_onepassword.imageset/button-onepassword@3x.png
  Simplenote/Images.xcassets/Buttons/button_visibility_off.imageset/Contents.json
  Simplenote/Images.xcassets/Buttons/button_visibility_off.imageset/button_visibility_off@1x.png
  Simplenote/Images.xcassets/Buttons/button_visibility_off.imageset/button_visibility_off@2x.png
  Simplenote/Images.xcassets/Buttons/button_visibility_off.imageset/button_visibility_off@3x.png
  Simplenote/Images.xcassets/Buttons/button_visibility_on.imageset/Contents.json
  Simplenote/Images.xcassets/Buttons/button_visibility_on.imageset/button_visibility_on@1x.png
  Simplenote/Images.xcassets/Buttons/button_visibility_on.imageset/button_visibility_on@2x.png
  Simplenote/Images.xcassets/Buttons/button_visibility_on.imageset/button_visibility_on@3x.png
  Simplenote/Images.xcassets/Buttons/onepassword_button.imageset/Contents.json
  Simplenote/Images.xcassets/Buttons/onepassword_button.imageset/onepassword_button.png
  Simplenote/Images.xcassets/Buttons/onepassword_button.imageset/onepassword_button@2x.png
  Simplenote/Images.xcassets/Buttons/onepassword_button.imageset/onepassword_button@3x.png
  Simplenote/Images.xcassets/features/feature-everywhere.imageset/Contents.json
  Simplenote/Images.xcassets/features/feature-everywhere.imageset/feature-everywhere-2x.png
  Simplenote/Images.xcassets/features/feature-everywhere.imageset/feature-everywhere.png
  Simplenote/Images.xcassets/features/feature-free.imageset/Contents.json
  Simplenote/Images.xcassets/features/feature-free.imageset/feature-free-2x.png
  Simplenote/Images.xcassets/features/feature-free.imageset/feature-free.png
  Simplenote/Images.xcassets/features/feature-organize.imageset/Contents.json
  Simplenote/Images.xcassets/features/feature-organize.imageset/feature-organize-2x.png
  Simplenote/Images.xcassets/features/feature-organize.imageset/feature-organize.png
  Simplenote/Images.xcassets/features/feature-search.imageset/Contents.json
  Simplenote/Images.xcassets/features/feature-search.imageset/feature-search-2x.png
  Simplenote/Images.xcassets/features/feature-search.imageset/feature-search.png
  Simplenote/Images.xcassets/features/feature-share.imageset/Contents.json
  Simplenote/Images.xcassets/features/feature-share.imageset/feature-share-2x.png
  Simplenote/Images.xcassets/features/feature-share.imageset/feature-share.png
  Simplenote/Images.xcassets/features/feature-time.imageset/Contents.json
  Simplenote/Images.xcassets/features/feature-time.imageset/feature-time-2x.png
  Simplenote/Images.xcassets/features/feature-time.imageset/feature-time.png
  Simplenote/SPAppDelegate.m
  Simplenote/Simplenote-DB5.plist
Labels: enhancement

#388 LaunchScreen Storyboard
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Images.xcassets/LaunchImage.launchimage/Contents.json
  Simplenote/Images.xcassets/LaunchImage.launchimage/default@2x.png
  Simplenote/Images.xcassets/LaunchImage.launchimage/default_1242@2x.png
  Simplenote/Images.xcassets/LaunchImage.launchimage/default_568@2x.png
  Simplenote/Images.xcassets/LaunchImage.launchimage/default_750@2x.png
  Simplenote/Images.xcassets/LaunchImage.launchimage/default_ipad_landscape.png
  Simplenote/Images.xcassets/LaunchImage.launchimage/default_ipad_landscape@2x.png
  Simplenote/Images.xcassets/LaunchImage.launchimage/default_ipad_portrait.png
  Simplenote/Images.xcassets/LaunchImage.launchimage/default_ipad_portrait@2x.png
  Simplenote/LaunchScreen.xib
  Simplenote/Resources/LaunchScreen.storyboard
Labels: debt

#385 Nü Onboarding: Mark III
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/NSMutableAttributedString+Simplenote.swift
  Simplenote/Classes/SPAuthError.swift
  Simplenote/Classes/SPAuthHandler.swift
  Simplenote/Classes/SPAuthViewController.swift
  Simplenote/Classes/SPAuthViewController.xib
  Simplenote/Classes/SPLabel.swift
  Simplenote/Classes/SPLoginViewController.h
  Simplenote/Classes/SPLoginViewController.m
  Simplenote/Classes/SPOnboardingViewController.swift
  Simplenote/Classes/SPTextInputView.swift
  Simplenote/Classes/UIColor+Simplenote.swift
  Simplenote/Classes/UIColorName.swift
  Simplenote/Classes/UINavigationBar+Simplenote.swift
  Simplenote/Classes/UIView+Animations.swift
  Simplenote/Classes/VSTheme+Keys.swift
  Simplenote/Colors.xcassets/simplenoteLipstick.colorset/Contents.json
  Simplenote/SPConstants.m
  Simplenote/Simplenote-DB5.plist
Labels: enhancement

#393 Bugfix: Onboarding Constraints
  Simplenote/Classes/SPAuthViewController.xib
Labels: bug

#395 Notes List: Peek and Pop
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPNoteEditorViewController.h
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController.h
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPTagsListViewController.m
  Simplenote/SPAppDelegate.m
  Simplenote/Simplenote-Bridging-Header.h
Labels: enhancement

#401 Restoring First Responder Behavior
  Simplenote/Classes/SPNoteEditorViewController.m
Labels: bug

#386 Nü Onboarding: Mark IV
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPAuthViewController.swift
  Simplenote/Classes/SPOnboardingViewController.swift
  Simplenote/Classes/SPSheetController.swift
  Simplenote/Classes/SPSheetController.xib
  Simplenote/Classes/UIColorName.swift
  Simplenote/Classes/UIKitConstants.swift
  Simplenote/Classes/UIView+Simplenote.swift
  Simplenote/Classes/UserDefaults+Simplenote.swift
  Simplenote/Classes/VSTheme+Keys.swift
  Simplenote/Classes/WPAuthHandler.h
  Simplenote/Classes/WPAuthHandler.m
  Simplenote/Colors.xcassets/simplenoteDeepSeaBlue.colorset/Contents.json
  Simplenote/SPConstants.h
  Simplenote/SPConstants.m
  Simplenote/SPCredentials.swift
  Simplenote/Simplenote-Bridging-Header.h
  Simplenote/Simplenote-DB5.plist
Labels: enhancement

#406 Update release-toolkit to 0.7.1
  Gemfile.lock
  fastlane/Pluginfile
Labels: tooling

#404 Updates SignUp password length
  Simplenote/Classes/SPAuthViewController.swift
Labels: [feature] login

#407 PR Template: Update Release section to be required
  .github/PULL_REQUEST_TEMPLATE.md
Labels: tooling

#410 Merge Release/4.10 into develop
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases

#412 SignUp >> Login String
  Simplenote/Classes/SPAuthError.swift
Labels: bug

#414 Peek + Pop: Preventing Pan
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPSidebarContainerViewController.h
  Simplenote/Classes/SPSidebarContainerViewController.m
  Simplenote/Classes/UIGestureRecognizer+Simplenote.swift
Labels: bug

#413 Forgot Password: Escaping Emails
  Simplenote/Classes/SPAuthHandler.swift
Labels: bug

#405 Nü Credentials Mechanism
  .circleci/config.yml
  .gitignore
  README.md
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/WPAuthHandler.m
  Simplenote/CrashLogging.swift
  Simplenote/KeychainMigrator.swift
  Simplenote/SPCredentials-demo.swift
  Simplenote/SPCredentials.swift
  Simplenote/config-demo.plist
  SimplenoteShare/Simperium/Uploader.swift
  SimplenoteTests/UIColorSimplenoteTests.swift
  SimplenoteTests/UIImageSimplenoteTests.swift
Labels: debt

#415 Update Tracks to disable memory warning
  Podfile.lock
Labels: enhancement
