Repository Automattic/simplenote-ios, pull requests merged in 2020-01, with the labels that each got.

#553 Nukes Appbot
  Podfile
  Podfile.lock
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPFeedbackManager.swift
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPRatingsPromptView.h
  Simplenote/Classes/SPRatingsPromptView.m
  Simplenote/Classes/SPRatingsPromptView.swift
  Simplenote/Classes/SPRatingsPromptView.xib
  Simplenote/Classes/UIView+Simplenote.swift
  Simplenote/SPAnimations.h
  Simplenote/SPAnimations.m
  Simplenote/SPAppDelegate.m
  Simplenote/SPCredentials-demo.swift
Labels: enhancement

#559 Nukes unused extensions
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/NSDate+Helper.h
  Simplenote/Classes/NSDate+Helper.m
  Simplenote/Classes/NSString+Condensing.h
  Simplenote/Classes/NSString+Condensing.m
  Simplenote/Classes/NSString+Metadata.h
  Simplenote/Classes/NSString+Metadata.m
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/UIDevice+Extensions.h
  Simplenote/Classes/UIDevice+Extensions.m
  Simplenote/Classes/UIImage+Extensions.h
  Simplenote/Classes/UIImage+Extensions.m
Labels: debt

#567 Updates App Icons
  RELEASE-NOTES.txt
  Simplenote/Icons.xcassets/AppIcon.appiconset/Contents.json
  Simplenote/Icons.xcassets/AppIcon.appiconset/icon1024pt.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/icon29pt@1x-1.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/icon29pt@1x.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/icon29pt@2x-1.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/icon29pt@2x.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/icon29pt@3x.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/icon50pt@1x.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/icon50pt@2x.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/icon512pt@1x.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/icon512pt@2x.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/icon60pt@2x.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/icon60pt@3x.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/icon76pt@1x.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/icon76pt@2x.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/icon83.5pt@2x.png
Labels: enhancement

#560 Nukes Integrity Failsafe
  Podfile
  Podfile.lock
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPIntegrityHelper.h
  Simplenote/Classes/SPIntegrityHelper.m
  Simplenote/SPAppDelegate.m
Labels: debt

#568 Adds New Assets
  Simplenote/Classes/UIImageName.swift
  Simplenote/Images.xcassets/Icons/icon_archive.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_archive.imageset/icon_archive.pdf
  Simplenote/Images.xcassets/Icons/icon_cross.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_cross.imageset/icon_cross.pdf
  Simplenote/Images.xcassets/Icons/icon_cross_big.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_cross_big.imageset/icon_cross.pdf
  Simplenote/Images.xcassets/Icons/icon_cross_big_outlined.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_cross_big_outlined.imageset/icon_cross_outline.pdf
  Simplenote/Images.xcassets/Icons/icon_cross_outlined.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_cross_outlined.imageset/icon_cross_outline.pdf
  Simplenote/Images.xcassets/Icons/icon_editor.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_editor.imageset/icon_editor.pdf
  Simplenote/Images.xcassets/Icons/icon_ellipsis.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_ellipsis.imageset/icon_ellipsis.pdf
  Simplenote/Images.xcassets/Icons/icon_restore.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_restore.imageset/icon_restore.pdf
  Simplenote/Images.xcassets/Icons/icon_tags.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_tags.imageset/icon_tags.pdf
  Simplenote/Images.xcassets/Icons/icon_tags_close.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_tags_close.imageset/icon_tags_close.pdf
  Simplenote/Images.xcassets/Icons/icon_tags_open.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_tags_open.imageset/icon_tags_open.pdf
Labels: enhancement

#569 Renaming SearchController > SearchDisplayController
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPSearchResultsViewController.swift
  Simplenote/Classes/SearchDisplayController.swift
Labels: [feature] search

#570 Removes Specialized SearchResults UI
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/FeatureManager.swift
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPSearchResultsViewController.swift
  Simplenote/Classes/SearchDisplayController.swift
  Simplenote/Classes/UIView+Animations.swift
Labels: [feature] search

#575 Merge Release/4.15 into develop
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/en.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: releases

#571 Fixes Print Share Printing White in Darkmode
  Simplenote/SPSimpleTextPrintFormatter.swift
  Simplenote/UIActivityViewController+Simplenote.swift
Labels: bug

#576 Update Fastlane to 2.140.0
  Gemfile
  Gemfile.lock
Labels: tooling

#581 Fixing Build
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPSimpleTextPrintFormatter.swift
Labels: bug

#583 Adds Asset: .sortOrder
  Simplenote/Classes/UIImageName.swift
  Simplenote/Images.xcassets/Icons/icon_sort_order.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_sort_order.imageset/icon_sort_order.pdf
Labels: [feature] search

#582 Implementing ResultsController: Part 0
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/FetchedResultsControllerDelegateWrapper.swift
  Simplenote/Classes/NSManagedObject+Simplenote.swift
  Simplenote/Classes/ResultsController.swift
  Simplenote/Classes/UITableView+ResultsController.swift
  SimplenoteTests/Constants.swift
  SimplenoteTests/MockupStorage+Sample.swift
  SimplenoteTests/MockupStorage.swift
  SimplenoteTests/ResultsControllerTests.swift
Labels: [feature] search

#577 Implements ResultsController: Part 1
  Simplenote.xcodeproj/project.pbxproj
  SimplenoteTests/MockupTableView.swift
  SimplenoteTests/ResultsControllerUIKitTests.swift
Labels: [feature] search

#578 Nukes SearchViewController + SearchResultsController
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPSearchResultsController.swift
  Simplenote/Classes/SPSearchResultsViewController.swift
  Simplenote/Classes/SPSearchResultsViewController.xib
Labels: debt

#579 NSPredicate+Simplenote: Updates API(s)
  Simplenote/Classes/NSPredicate+Simplenote.swift
  Simplenote/Classes/SPNoteListViewController.m
  SimplenoteTests/NSPredicateSimplenoteTests.swift
  SimplenoteTests/ResultsControllerTests.swift
Labels: [feature] search

#580 Implements NotesListController: Part I
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/NotesListController.swift
  Simplenote/Classes/NotesListFilter.swift
  Simplenote/Classes/NotesListState.swift
  Simplenote/Classes/SortMode+Descriptors.swift
  Simplenote/Simplenote-Bridging-Header.h
  SimplenoteTests/MockupStorage+Sample.swift
  SimplenoteTests/MockupStorage.swift
  SimplenoteTests/NotesListControllerTests.swift
Labels: [feature] search

#584 Implements NotesListController: Part II
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/IndexPath+Simplenote.swift
  Simplenote/Classes/NotesListController.swift
  Simplenote/Classes/NotesListState.swift
  Simplenote/Classes/ResultsController.swift
  Simplenote/Classes/ResultsObjectChange.swift
  Simplenote/Classes/ResultsSectionChange.swift
  SimplenoteTests/MockupStorage.swift
  SimplenoteTests/NotesListControllerTests.swift
Labels: [feature] search

#586 Notes List: Swifting UITableViewDatasource
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController.m
Labels: [feature] search

#594 Merge Release/4.15 into develop
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/cy.lproj/Localizable.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/el.lproj/Localizable.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: releases

#588 Notes List: Swifting UITableViewDelegate
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPObjectManager.h
  Simplenote/Classes/SPObjectManager.m
  Simplenote/Classes/UITableViewRowAction+Simplenote.swift
  Simplenote/Simplenote-Bridging-Header.h
Labels: [feature] search

#587 Wiring NotesListController
  Simplenote/Classes/NotesListController.swift
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController.h
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPTransitionController.m
  Simplenote/Classes/UITableView+Simplenote.swift
  Simplenote/SPAppDelegate.m
Labels: [feature] search

#589 Notes List: Tags UI
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/NotesListController.swift
  Simplenote/Classes/NotesListSection.swift
  Simplenote/Classes/NotesListState.swift
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController.h
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPSectionHeaderView.swift
  Simplenote/Classes/SPSectionHeaderView.xib
  Simplenote/Classes/SPTagTableViewCell.swift
  Simplenote/Classes/SPTagTableViewCell.xib
  Simplenote/Classes/UIColor+Studio.swift
  Simplenote/Classes/UIFont+Simplenote.swift
  Simplenote/Classes/UITableView+Simplenote.swift
  Simplenote/Classes/UITableViewHeaderFooterView+Simplenote.swift
  SimplenoteTests/NotesListControllerTests.swift
Labels: [feature] search

#590 Search: Limits the number of Tag Results
  Simplenote/Classes/NotesListController.swift
  Simplenote/Classes/ResultsController.swift
  SimplenoteTests/NotesListControllerTests.swift
Labels: [feature] search

#591 Search: Tag Operator
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/NSPredicate+Simplenote.swift
  Simplenote/Classes/NotesListState.swift
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController.h
  Simplenote/Classes/SearchDisplayController.swift
  Simplenote/Classes/String+Simplenote.swift
  SimplenoteTests/NSPredicateSimplenoteTests.swift
  SimplenoteTests/StringSimplenoteTests.swift
Labels: [feature] search
