Repository Automattic/simplenote-ios, pull requests merged in 2020-05, with the labels that each got.

#742 Merge finalized release 4.18 into develop
  config/Version.Public.xcconfig
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/app_store_screenshot_1.txt
  fastlane/metadata/en-US/app_store_screenshot_2.txt
  fastlane/metadata/en-US/app_store_screenshot_3.txt
  fastlane/metadata/en-US/app_store_screenshot_4.txt
  fastlane/metadata/en-US/app_store_screenshot_5.txt
  fastlane/metadata/en-US/app_store_screenshot_6.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#743 Merge release 4.18 into master
  .bundle/config
  .circleci/config.yml
  .configure
  .gitignore
  Gemfile.lock
  README.md
  RELEASE-NOTES.txt
  Scripts/update-translations.rb
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcodeproj/xcshareddata/xcschemes/SimplenoteScreenshots.xcscheme
  Simplenote/Classes/NSPredicate+Simplenote.swift
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPOptionsViewController.m
  Simplenote/Classes/SPTagsListViewController.m
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/Simplenote-Info.plist
  Simplenote/fa.lproj/Localizable.strings
  SimplenoteScreenshots/Info.plist
  SimplenoteScreenshots/ScreenshotsCredentials-demo.swift
  SimplenoteScreenshots/SimplenoteScreenshots.swift
  SimplenoteScreenshots/SnapshotHelper.swift
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/Fastfile
  fastlane/Pluginfile
  fastlane/actions/ios_update_metadata_source.rb
  fastlane/appstoreres/.gitattributes
  fastlane/appstoreres/assets/iphone_8_plus.png
  fastlane/appstoreres/assets/styles/style.css
  fastlane/download_metadata.swift
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
  fastlane/screenshots.json
Labels: Releases

#744 Updates OnePassword Dependency
  Podfile
  Podfile.lock
  Simplenote/Classes/SPAuthError.swift
Labels: debt

#746 Hardened Security: Mark 1
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/AuthenticationValidator.swift
  Simplenote/Classes/SPAuthViewController.swift
  Simplenote/Classes/String+Simplenote.swift
  Simplenote/Classes/UIView+Animations.swift
  Simplenote/NSPredicate+Email.swift
  SimplenoteTests/AuthenticationValidatorTests.swift
  SimplenoteTests/NSPredicateEmailTests.swift
Labels: [feature] security, enhancement

#726 Take screenshots on CI (no composition yet)
  .configure-files/ScreenshotsCredentials.swift.enc
  .github/workflows/screenshots.yml
  Scripts/pre-actions/configure-status-bar.sh
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcodeproj/xcshareddata/xcschemes/SimplenoteScreenshots.xcscheme
  SimplenoteScreenshots/SimplenoteScreenshots.swift
  SimplenoteScreenshots/XCTest+Extensions.swift
  fastlane/Fastfile
  fastlane/appstoreres/assets/ipad_12_9_3rd_gen_mask.png
  fastlane/appstoreres/assets/ipad_2nd_gen.png
  fastlane/appstoreres/assets/ipad_3rd_gen.png
  fastlane/appstoreres/assets/iphone_Xs_mask_no_notch.png
  fastlane/appstoreres/assets/iphone_Xs_max.png
  fastlane/screenshots.json
Labels: Needs Screenshots, tooling

#752 Update separator colour
  Simplenote/Classes/UIColor+Studio.swift
Labels: spring cleaning

#753 Adding Style Guidelines
  README.md
Labels: documentation

#747 Hardened Security: Mark 2
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/AuthenticationValidator.swift
  Simplenote/Classes/SPAuthHandler.swift
  Simplenote/Classes/SPAuthViewController.swift
  Simplenote/Classes/SimplenoteConstants.swift
  SimplenoteTests/AuthenticationValidatorTests.swift
Labels: [feature] security

#750 Spring Cleaning: Checklist Button
  RELEASE-NOTES.txt
  Simplenote/Classes/SPEditorTextView.h
  Simplenote/Classes/SPEditorTextView.m
  Simplenote/Classes/SPNoteEditorViewController.h
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
Labels: enhancement, spring cleaning

#754 Perform screenshot composition in CI
  .github/workflows/screenshots.yml
  fastlane/Fastfile
  fastlane/appstoreres/.gitattributes
  fastlane/appstoreres/assets/SourceSansPro-Regular.ttf
  fastlane/metadata/en-US/app_store_screenshot_1.txt
  fastlane/metadata/en-US/app_store_screenshot_2.txt
  fastlane/metadata/en-US/app_store_screenshot_3.txt
  fastlane/metadata/en-US/app_store_screenshot_4.txt
  fastlane/metadata/en-US/app_store_screenshot_5.txt
  fastlane/metadata/en-US/app_store_screenshot_6.txt
Labels: Needs Screenshots, tooling

#759 Merge 4.19 beta 1 in develop
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/en.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases
