Repository Automattic/simplenote-ios, pull requests merged in 2020-07, with the labels that each got.

#792 Merge hotfix 4.20.1 into develop
  RELEASE-NOTES.txt
  Simplenote/Classes/SPAboutViewController.swift
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/metadata/de-DE/description.txt
  fastlane/metadata/default/description.txt
  fastlane/metadata/en-US/description.txt
  fastlane/metadata/es-ES/description.txt
  fastlane/metadata/fr-FR/description.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/description.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/description.txt
  fastlane/metadata/ja/description.txt
  fastlane/metadata/ko/description.txt
  fastlane/metadata/nl-NL/description.txt
  fastlane/metadata/pt-BR/description.txt
  fastlane/metadata/ru/description.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/description.txt
  fastlane/metadata/tr/description.txt
  fastlane/metadata/zh-Hans/description.txt
  fastlane/metadata/zh-Hant/description.txt
Labels: Releases

#794 Merge hotfix 4.20.1 into main
  RELEASE-NOTES.txt
  Simplenote/Classes/SPAboutViewController.swift
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/metadata/de-DE/description.txt
  fastlane/metadata/default/description.txt
  fastlane/metadata/en-US/description.txt
  fastlane/metadata/es-ES/description.txt
  fastlane/metadata/fr-FR/description.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/description.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/description.txt
  fastlane/metadata/ja/description.txt
  fastlane/metadata/ko/description.txt
  fastlane/metadata/nl-NL/description.txt
  fastlane/metadata/pt-BR/description.txt
  fastlane/metadata/ru/description.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/description.txt
  fastlane/metadata/tr/description.txt
  fastlane/metadata/zh-Hans/description.txt
  fastlane/metadata/zh-Hant/description.txt
Labels: Releases

#788 Dark mode Nü Theme
  External/DTPinLock/DTPinLockController.m
  RELEASE-NOTES.txt
  Simplenote/Classes/ColorStudio.swift
  Simplenote/Classes/SPActionSheet.m
  Simplenote/Classes/SPHorizontalPickerGradientView.m
  Simplenote/Classes/SPHorizontalPickerView.m
  Simplenote/Classes/SPNoteTableViewCell.swift
  Simplenote/Classes/UIColor+Studio.swift
  Simplenote/Classes/UIImage+Dynamic.swift
Labels: [feature] dark mode

#793 New component to embed a view controller in a card-like view
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPCardViewController.swift
  Simplenote/Classes/UIColor+Studio.swift
  Simplenote/SPShadowView.swift
  Simplenote/UIView+Constraints.swift
Labels: spring cleaning

#800 Change launch screen background to black in dark mode
  Simplenote/Colors.xcassets/simplenoteLaunchBackgroundColor.colorset/Contents.json
Labels: [feature] dark mode

#798 Bugfix: ResultsController Crash
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/NotesListController.swift
  Simplenote/Classes/ResultsController.swift
  Simplenote/Classes/ResultsObjectChange.swift
  Simplenote/Classes/ResultsObjectsChangeset.swift
  Simplenote/Classes/ResultsSectionChange.swift
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/UITableView+ResultsController.swift
  Simplenote/ResultsSectionsChangeset.swift
  SimplenoteTests/MockupTableView.swift
  SimplenoteTests/NotesListControllerTests.swift
  SimplenoteTests/ResultsControllerTests.swift
  SimplenoteTests/ResultsControllerUIKitTests.swift
  SimplenoteTests/ResultsSectionsChangesetTests.swift
Labels: crash

#801 Analytics: Application State Events
  Simplenote/Classes/SPTracker.h
  Simplenote/Classes/SPTracker.m
  Simplenote/SPAppDelegate.m
Labels: analytics

#802 Merge 4.21.0 beta 1 into develop
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/en.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases

#805 Fix tag search text colour
  Simplenote/Classes/SPTagTableViewCell.swift
Labels: enhancement

#808 Editor Adjustments
  RELEASE-NOTES.txt
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Simplenote-DB5.plist
Labels: [feature] editor

#804 Improve side menu accessibility via VoiceOver
  Simplenote/Classes/SPTagListViewCell.m
  Simplenote/Classes/SPTagsListViewController.m
Labels: accessibility

#812 Improve side menu accessibility via VoiceOver (clone from forked repo)
  Simplenote/Classes/SPTagListViewCell.m
  Simplenote/Classes/SPTagsListViewController.m
Labels: accessibility

#796 History Slider - VoiceOver and UI improvements
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteHistoryViewController.swift
  Simplenote/Classes/SPNoteHistoryViewController.xib
  Simplenote/Classes/UIColor+Studio.swift
  Simplenote/Classes/UIKitConstants.swift
  Simplenote/SPCardPresentationController.swift
  Simplenote/SPNoteEditorViewController+Extensions.swift
  Simplenote/SPSnappingSlider.swift
Labels: spring cleaning

#806 Editor: Autolayout FTW
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/KeyboardObservable.swift
  Simplenote/Classes/SPEditorTextView.h
  Simplenote/Classes/SPEditorTextView.m
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPNoteEditorViewController.h
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPTagEntryField.h
  Simplenote/Classes/SPTagEntryField.m
  Simplenote/Classes/SPTagView.h
  Simplenote/Classes/SPTagView.m
  Simplenote/Classes/SPTextView.m
  Simplenote/Classes/UIView+Simplenote.swift
  SimplenoteShare/Presentation/ExtensionPresentationController.swift
Labels: bug, debt

#816 Fixes Interactive Scrollbar
  RELEASE-NOTES.txt
  Simplenote/Classes/SPEditorTextView.m
Labels: bug

#820 Update Fastlane to version 2.152.0
  Gemfile
  Gemfile.lock
  fastlane/Pluginfile
Labels: tooling

#818 Merge release 4.21.0 into develop
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/cy.lproj/Localizable.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/el.lproj/Localizable.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/fa.lproj/Localizable.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/de-DE/description.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/description.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/description.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/description.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/description.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/description.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/description.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/description.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/description.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/description.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/description.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/description.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/description.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/description.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/description.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/description.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#824 Tags Edition: Standard Validation!
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/NSString+Metadata.h
  Simplenote/Classes/NSString+Metadata.m
  Simplenote/Classes/NSString+Simplenote.swift
  Simplenote/Classes/SPObjectManager.m
  Simplenote/Classes/SPTagView.m
  Simplenote/Classes/SPTagsListViewController.m
  Simplenote/Classes/SimplenoteConstants.swift
  SimplenoteTests/NSStringSimplenoteTests.swift
Labels: [feature] tags, enhancement

#825 Merge 4.22.0-beta1 into develop
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/appstoreres/metadata/source/description.txt
  fastlane/download_metadata.swift
Labels: Releases

#828 Tags Normalization
  Simplenote/Classes/NSString+Simplenote.swift
  Simplenote/Classes/SPObjectManager.m
  Simplenote/Classes/SPTagView.m
  Simplenote/Classes/SPTagsListViewController.m
  SimplenoteTests/NSStringSimplenoteTests.swift
Labels: enhancement
