Repository Automattic/simplenote-ios, pull requests merged in 2020-11, with the labels that each got.

#967 Merge release 4.27 beta 1 into develop
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/en.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases

#970 Fixing Text Selection: Mark I
  Simplenote/Classes/SPEditorTextView.m
Labels: bug

#971 Convert text to markdown when copying to pasteboard
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPEditorTextView.h
  Simplenote/Classes/SPEditorTextView.m
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/NSAttributedStringToMarkdownConverter.swift
  Simplenote/SPEditorTextView+Simplenote.swift
Labels: [feature] checklist, [feature] editor

#975 Remove canOpenURL check for https scheme
  Simplenote/Classes/SPSettingsViewController.m
Labels: [feature] settings, bug

#976 Editor: Preventing edition during drag OP(s)
  RELEASE-NOTES.txt
  Simplenote/Classes/SPEditorTapRecognizerDelegate.swift
Labels: bug

#973 Fixing Text Selection: Mark II
  RELEASE-NOTES.txt
  Simplenote/Classes/SPEditorTextView.m
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPTextView.m
Labels: bug

#977 Dropping VSTheme: Mark I
  External/DTPinLock/DTPinLockController.m
  Simplenote/Classes/SPMarkdownParser.m
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPSettingsViewController.m
  Simplenote/Classes/SPTagEntryField.m
  Simplenote/Classes/SPTagPill.h
  Simplenote/Classes/SPTagPill.m
  Simplenote/Classes/SPTagView.m
  Simplenote/Classes/SPTagsListViewController.m
  Simplenote/Classes/SPTextView.m
  Simplenote/SPAppDelegate.m
Labels: debt

#978 Dropping VSTheme: Mark II
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/NSMutableParagraphStyle+Simplenote.swift
  Simplenote/Classes/SPEditorTextView.m
  Simplenote/Classes/SPInteractivePushPopAnimationController.m
  Simplenote/Classes/SPInteractiveTextStorage.h
  Simplenote/Classes/SPInteractiveTextStorage.m
  Simplenote/Classes/SPMarkdownPreviewViewController.m
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPNoteEditorViewController.h
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPSettingsViewController.m
  Simplenote/Classes/SPTransitionController.m
  Simplenote/Classes/UIDevice+Extensions.h
  Simplenote/Classes/UIDevice+Extensions.m
  Simplenote/Classes/UIDevice+Simplenote.swift
  Simplenote/Classes/UIKeyboardAppearance+Simplenote.swift
  Simplenote/Classes/VSTheme+Extensions.m
  Simplenote/Simplenote-Bridging-Header.h
Labels: debt

#980 Dropping VSTheme: Mark III
  Simplenote/Classes/SPEditorTextView.m
  Simplenote/Classes/SPEntryListCell.m
  Simplenote/Classes/SPEntryListViewController.m
  Simplenote/Simplenote-Bridging-Header.h
Labels: debt

#981 Dropping VSTheme: Mark IV
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPEditorTextView.m
  Simplenote/Classes/VSTheme+Extensions.h
  Simplenote/Classes/VSTheme+Extensions.m
  Simplenote/DB5/VSTheme.h
  Simplenote/DB5/VSTheme.m
  Simplenote/DB5/VSThemeLoader.h
  Simplenote/DB5/VSThemeLoader.m
  Simplenote/DB5/VSThemeManager.h
  Simplenote/DB5/VSThemeManager.m
  Simplenote/Simplenote-DB5.plist
Labels: debt

#985 Keychain: Silencing "No password" error
  Simplenote/Classes/KeychainManager.swift
  Simplenote/KeychainPasswordItem.swift
Labels: debt

#982 Fixing Text Selection: Mark III
  RELEASE-NOTES.txt
  Simplenote/Classes/SPEditorTextView.m
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
Labels: bug

#984 Update Tag List
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPTagListViewCell.m
  Simplenote/Classes/SPTagsListViewController.h
  Simplenote/Classes/SPTagsListViewController.m
  Simplenote/Classes/TagListViewController.xib
  Simplenote/SPAppDelegate+Extensions.swift
  Simplenote/SPAppDelegate.h
  Simplenote/SPAppDelegate.m
  Simplenote/Simplenote-Bridging-Header.h
  Simplenote/TagListViewController.swift
Labels: [feature] tags, bug

#986 Mapping Simperium 1.1
  Podfile
  Podfile.lock
Labels: debt

#997 Remove unused "Distribution AdHoc" build configuration
  Simplenote.xcodeproj/project.pbxproj
Labels: tooling

#998 Remove orphan reference to SPTagsListViewController from project
  Simplenote.xcodeproj/project.pbxproj
Labels: tooling

#996 Fixing New Note Action
  RELEASE-NOTES.txt
  Simplenote/Classes/SPNoteEditorViewController.m
Labels: bug

#1000 List: Updates long press action
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
Labels: enhancement

#989 TagList: Updates Separator Behavior
  RELEASE-NOTES.txt
  Simplenote/Classes/SPTagHeaderView.xib
  Simplenote/Classes/TagListViewController.xib
  Simplenote/TagListViewController.swift
Labels: enhancement

#992 Tag List Updates: MK2
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Simplenote/SPAppDelegate.m
  Simplenote/TagListViewController.swift
Labels: [feature] tags

#1006 Update SwiftLint to 0.41.0
  .swiftlint.yml
  Rakefile
Labels: enhancement, tooling

#1002 Interlinks Autocomplete: Mark I
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/InterlinkResultsController.swift
  Simplenote/Classes/String+Simplenote.swift
  SimplenoteTests/InterlinkResultsControllerTests.swift
Labels: interlinking

#1009 Editor: Fixing keyword navigation
  RELEASE-NOTES.txt
  Simplenote/Classes/SPNoteEditorViewController.m
Labels: bug

#1007 Use inclusive language
  Simplenote/Classes/ColorStudio.swift
  Simplenote/Classes/NSManagedObjectContext+CoreDataExtensions.m
  Simplenote/Classes/SPNoteTableViewCell.swift
  SimplenoteScreenshots/SnapshotHelper.swift
Labels: spring cleaning

#965 Show relevant excerpts while searching
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Simplenote/Classes/ContentSlice.swift
  Simplenote/Classes/NSMutableAttributedString+Simplenote.swift
  Simplenote/Classes/NSRegularExpression+Simplenote.swift
  Simplenote/Classes/NSString+Condensing.h
  Simplenote/Classes/NSString+Condensing.m
  Simplenote/Classes/NSString+Search.h
  Simplenote/Classes/NSString+Search.m
  Simplenote/Classes/Note+Properties.swift
  Simplenote/Classes/Note.h
  Simplenote/Classes/Note.m
  Simplenote/Classes/NoteContentHelper.swift
  Simplenote/Classes/NotesListController.swift
  Simplenote/Classes/NotesListState.swift
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPNoteEditorViewController.h
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPNoteTableViewCell.swift
  Simplenote/Classes/SPTextView.m
  Simplenote/Classes/String+Simplenote.swift
  Simplenote/Simplenote-Bridging-Header.h
  SimplenoteTests/NSStringCondensingTests.swift
  SimplenoteTests/NoteBodyExcerptTests.swift
  SimplenoteTests/NoteContentHelperTests.swift
  SimplenoteTests/NoteContentPreviewTests.swift
  SimplenoteTests/StringContentSliceTests.swift
  SimplenoteTests/StringSimplenoteTests.swift
Labels: [feature] search

#1003 Interlinks Autocomplete: Mark II
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/ColorStudio.swift
  Simplenote/Classes/InterlinkProcessor.swift
  Simplenote/Classes/InterlinkViewController.swift
  Simplenote/Classes/InterlinkViewController.xib
  Simplenote/Classes/PassthruView.swift
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPNoteEditorViewController.h
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/UIColor+Studio.swift
  Simplenote/Classes/UITextView+Simplenote.swift
  Simplenote/Classes/UIView+Animations.swift
  Simplenote/Classes/UIViewController+Simplenote.swift
  Simplenote/UIView+Constraints.swift
Labels: interlinking

#1005 Interlinks Autocomplete: Mark III
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/InterlinkProcessor.swift
  Simplenote/Classes/InterlinkViewController.swift
  Simplenote/Classes/NSAttributedString+Simplenote.swift
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/UIPasteboard+Note.swift
  Simplenote/Classes/UITextView+Simplenote.swift
  Simplenote/Note+Links.swift
Labels: interlinking

#1011 NoteInformationController: Updates references title
  Simplenote/Information/NoteInformationController.swift
Labels: enhancement

#1012 Interlinks Autocomplete: Mark IV
  Simplenote/Classes/InterlinkViewController.swift
  Simplenote/Classes/InterlinkViewController.xib
  Simplenote/Classes/UIColor+Studio.swift
  Simplenote/SPShadowView.swift
Labels: interlinking

#1004 Search Minimap
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPNoteEditorViewController.h
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/SearchMapView.swift
Labels: [feature] search, search improvements

#1013 Interlinks Autocomplete: Mark V
  RELEASE-NOTES.txt
  Simplenote/Classes/InterlinkProcessor.swift
  Simplenote/Classes/InterlinkViewController.swift
  Simplenote/Classes/InterlinkViewController.xib
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/UITextView+Simplenote.swift
Labels: interlinking

#1015 Merge release 4.27 into develop
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/cy.lproj/Localizable.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/el.lproj/Localizable.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/fa.lproj/Localizable.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#1020 Merge release 4.28 beta 1 into develop
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/en.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases

#1021 Information card improvements
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Information/NoteInformationViewController.swift
  Simplenote/Information/NoteInformationViewController.xib
  Simplenote/SPShadowView.swift
Labels: spring cleaning

#1017 Use the CocoaPods CDN
  Podfile
  Podfile.lock
Labels: tooling

#1027 Interlinks Autocomplete: RTL Support
  Simplenote/Classes/InterlinkProcessor.swift
  Simplenote/Classes/InterlinkViewController.swift
  Simplenote/Classes/InterlinkViewController.xib
  Simplenote/Classes/SPTracker.h
  Simplenote/Classes/SPTracker.m
Labels: bug, interlinking

#1028 Bugfix: InterlinkProcessor dismissal on Text Selection
  Simplenote/Classes/InterlinkProcessor.swift
  Simplenote/Classes/SPEditorTextView.h
  Simplenote/Classes/SPEditorTextView.m
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/UITextView+Simplenote.swift
Labels: bug, interlinking

#1029 Interlinking: Updates Blur
  Simplenote/Classes/UIColor+Studio.swift
Labels: interlinking

#1030 Interlinking: Dynamic Height
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/CGRect+Simplenote.swift
  Simplenote/Classes/InterlinkViewController.swift
  Simplenote/Classes/InterlinkViewController.xib
  SimplenoteTests/CGRectSimplenoteTests.swift
Labels: interlinking

#1032 Home screen quick actions
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/ApplicationShortcutItemType.swift
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteListViewController.h
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/ShortcutsHandler.swift
  Simplenote/Classes/UIImageName.swift
  Simplenote/Images.xcassets/Icons/icon_search.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_search.imageset/search.pdf
  Simplenote/SPAppDelegate+Extensions.swift
  Simplenote/SPAppDelegate.h
  Simplenote/SPAppDelegate.m
Labels: spring cleaning

#1031 Empty states
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController.h
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPObjectManager+Simplenote.swift
  Simplenote/Classes/SPPlaceholderView.swift
  Simplenote/SPAppDelegate.m
Labels: search improvements, spring cleaning

#1040 Refresh About screen metrics
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/RoundedCrossButton.swift
  Simplenote/Classes/SPAboutViewController.swift
  Simplenote/Classes/SPNoteHistoryViewController.swift
  Simplenote/Classes/SPNoteHistoryViewController.xib
  Simplenote/Classes/UIColor+Studio.swift
  Simplenote/Classes/UIImageName.swift
  Simplenote/Classes/ViewSpinner.swift
  Simplenote/Information/NoteInformationViewController.swift
  Simplenote/Information/NoteInformationViewController.xib
Labels: spring cleaning

#1039 Restoring Blur Alpha
  Simplenote/Classes/InterlinkViewController.swift
  Simplenote/Classes/UIColor+Studio.swift
Labels: interlinking

#1038 Update `notesWithTag` method to use `SimplenoteFoundation`
  Simplenote/Classes/SPObjectManager+Simplenote.swift
  Simplenote/Classes/SPObjectManager.h
  Simplenote/Classes/SPObjectManager.m
Labels: debt

#1034 Merge release 4.28 into develop with conflicts resolution
  Simplenote/Classes/InterlinkProcessor.swift
  Simplenote/Classes/InterlinkViewController.swift
  Simplenote/Classes/InterlinkViewController.xib
  Simplenote/Classes/SPEditorTextView.h
  Simplenote/Classes/SPEditorTextView.m
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPTracker.h
  Simplenote/Classes/SPTracker.m
  Simplenote/Classes/UIColor+Studio.swift
  Simplenote/Classes/UITextView+Simplenote.swift
  config/Version.Public.xcconfig
Labels: Releases

#1050 Merge Release/4.28 back into develop
  Simplenote/Classes/InterlinkViewController.swift
  Simplenote/Classes/UIColor+Studio.swift
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/cy.lproj/Localizable.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/el.lproj/Localizable.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/fa.lproj/Localizable.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases
