Repository Automattic/simplenote-ios, pull requests merged in 2020-09, with the labels that each got.

#867 Fixing Retain Cycle
  Simplenote/Classes/SPTagView.h
  Simplenote/Classes/SPTagView.m
Labels: debt

#868 Interlinking: Navigation Support
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/EditorFactory.swift
  Simplenote/Classes/SPMarkdownPreviewViewController.m
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPNoteEditorViewController.h
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController.h
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/Simperium+Simplenote.swift
  Simplenote/Classes/UINavigationController+Simplenote.swift
  Simplenote/Classes/UIViewController+Helpers.swift
  Simplenote/SPAppDelegate+Extensions.swift
  Simplenote/SPAppDelegate.h
  Simplenote/SPAppDelegate.m
Labels: interlinking

#803 History Slider - Show loading progress for each version
  Simplenote/Classes/SPNoteHistoryViewController.swift
  Simplenote/Classes/SPNoteHistoryViewController.xib
  Simplenote/SPHistoryLoader.swift
  Simplenote/SPNoteEditorViewController+Extensions.swift
  Simplenote/SPNoteHistoryController.swift
  Simplenote/SPNoteHistoryControllerDelegate.swift
Labels: spring cleaning

#872 Fixing Email Validation
  RELEASE-NOTES.txt
  Simplenote/Classes/NSString+Metadata.h
  Simplenote/Classes/NSString+Metadata.m
  Simplenote/Classes/NSString+Simplenote.swift
  Simplenote/Classes/Note.m
  Simplenote/Classes/SPAddCollaboratorsViewController.m
  Simplenote/Classes/SPObjectManager.m
  Simplenote/Classes/SPTagStub.h
  Simplenote/Classes/SPTagStub.m
  Simplenote/Classes/SPTagView.m
  SimplenoteTests/NSPredicateEmailTests.swift
Labels: bug

#871 Fixing Tags Edition
  RELEASE-NOTES.txt
  Simplenote/Classes/SPTagListViewCell.xib
Labels: bug

#873 Disables Interlinking Support
  RELEASE-NOTES.txt
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
Labels: interlinking

#874 Merge v4.24 with conflicts resolution
  .circleci/config.yml
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/EditorFactory.swift
  Simplenote/Classes/SPMarkdownPreviewViewController.m
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPNoteEditorViewController.h
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController.h
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPTagListViewCell.xib
  Simplenote/Classes/Simperium+Simplenote.swift
  Simplenote/Classes/UINavigationController+Simplenote.swift
  Simplenote/Classes/UIViewController+Helpers.swift
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/SPAppDelegate+Extensions.swift
  Simplenote/SPAppDelegate.h
  Simplenote/SPAppDelegate.m
  Simplenote/en.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases

#875 Switch configuration to trunk
  .configure
  Gemfile.lock
  fastlane/Pluginfile
Labels: tooling

#876 Enabling Interlinking
  RELEASE-NOTES.txt
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
Labels: interlinking

#881 Drops iOS 11 Support
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcodeproj/xcshareddata/xcschemes/Simplenote.xcscheme
  Simplenote.xcodeproj/xcshareddata/xcschemes/SimplenoteScreenshots.xcscheme
  Simplenote/Classes/SPEditorTextView.m
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/UIFont+Simplenote.swift
  Simplenote/Classes/UITraitCollection+Simplenote.swift
Labels: debt

#882 Drops 1Password Framework
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  Simplenote/Classes/SPAuthError.swift
  Simplenote/Classes/SPAuthHandler.swift
  Simplenote/Classes/SPAuthViewController.swift
  Simplenote/Classes/SPTextInputView.swift
  Simplenote/Classes/SPTracker.h
  Simplenote/Classes/SPTracker.m
  Simplenote/Classes/SimplenoteConstants.swift
  Simplenote/Classes/UIImageName.swift
  Simplenote/Images.xcassets/Icons/Contents.json
  Simplenote/Images.xcassets/Icons/icon_onepassword.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_onepassword.imageset/icon_onepassword.pdf
  Simplenote/SPConstants.h
  Simplenote/SPConstants.m
Labels: debt

#878 Integrates Simperium + NSURLSession PR
  Podfile
  Podfile.lock
  Simplenote/Classes/SPAuthHandler.swift
Labels: debt

#887 Merge release 4.24 into develop
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/cy.lproj/Localizable.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/el.lproj/Localizable.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/fa.lproj/Localizable.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#883 Housekeeping!
  Simplenote/Classes/MigrationsHandler.swift
  Simplenote/Classes/NSUserActivity+Simplenote.swift
  Simplenote/Classes/NotesListFilter.swift
  Simplenote/Classes/NotesListState.swift
  Simplenote/Classes/SPOptionsViewController.m
  Simplenote/Classes/SPSimpleTextPrintFormatter.swift
  Simplenote/Classes/ShortcutsHandler.swift
  Simplenote/Classes/UserDefaults+Simplenote.swift
  Simplenote/Options.swift
  Simplenote/SPAppDelegate.h
  Simplenote/SPAppDelegate.m
  Simplenote/SPConstants.h
  Simplenote/SPConstants.m
  SimplenoteScreenshots/XCTest+Extensions.swift
Labels: debt

#891 Merge 4.25 beta 1 into develop
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/en.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases

#884 Dropping VSTheme: Mark 1
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPActionButton.m
  Simplenote/Classes/SPActivityView.m
  Simplenote/Classes/SPDefaultTableViewCell.swift
  Simplenote/Classes/SPOptionsViewController.m
  Simplenote/Classes/SPTableViewController.m
  Simplenote/Classes/UIColor+Simplenote.swift
  Simplenote/Classes/UIColor+Studio.swift
  Simplenote/Classes/UIColorName.swift
  Simplenote/Classes/VSTheme+Keys.swift
  Simplenote/Colors.xcassets/Contents.json
  Simplenote/Colors.xcassets/actionSheetButtonBackgroundHighlightColor.colorset/Contents.json
  Simplenote/Colors.xcassets/actionSheetButtonFontColor.colorset/Contents.json
  Simplenote/Colors.xcassets/actionViewButtonDisabledColor.colorset/Contents.json
  Simplenote/Colors.xcassets/actionViewStatusFontColor.colorset/Contents.json
  Simplenote/Colors.xcassets/simplenoteLaunchBackgroundColor.colorset/Contents.json
  Simplenote/Colors.xcassets/tableViewDetailTextLabelColor.colorset/Contents.json
  Simplenote/Resources/LaunchScreen.storyboard
  Simplenote/Simplenote-DB5.plist
  SimplenoteTests/UIColorSimplenoteTests.swift
Labels: debt

#889 Drops SAMKeychain: Mark 1
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/KeyboardObservable.swift
  Simplenote/Classes/KeychainManager.swift
  Simplenote/Classes/UIColor+Studio.swift
  Simplenote/Classes/UIKitConstants.swift
  Simplenote/SPAppDelegate+Extensions.swift
  Simplenote/SPAppDelegate.h
  Simplenote/SPAppDelegate.m
  Simplenote/SPConstants.h
  Simplenote/SPConstants.m
  Simplenote/SPPinLockManager.swift
Labels: debt

#879 Extended Debugging
  Podfile
  Podfile.lock
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/NSAttributedString+AuthError.swift
  Simplenote/Classes/SPAuthError.swift
  Simplenote/Classes/SPAuthHandler.swift
  Simplenote/Classes/SPAuthViewController.swift
  Simplenote/Classes/SPDiagnosticsViewController.swift
  Simplenote/Classes/SPDiagnosticsViewController.xib
  Simplenote/Classes/SPOnboardingViewController.swift
  Simplenote/Classes/SPOnboardingViewController.xib
  Simplenote/Classes/UIKitConstants.swift
Labels: [feature] login, enhancement

#894 Add Help Link
  RELEASE-NOTES.txt
  Simplenote/Classes/SPAboutViewController.swift
  Simplenote/Classes/SPOptionsViewController.m
Labels: [status] needs code review, task

#893 Template Images!
  Simplenote/Images.xcassets/Icons/icon_archive.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_checklist.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_chevron_left.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_chevron_right.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_collaborate.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_cross.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_cross_big.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_cross_big_outlined.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_cross_outlined.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_editor.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_ellipsis.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_hide_keyboard.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_history.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_info.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_menu.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_new_note.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_restore.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_tags.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_tags_close.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_tags_open.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_user.imageset/Contents.json
Labels: debt

#885 Dropping VSTheme: Mark 2
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPActionSheet.h
  Simplenote/Classes/SPActionSheet.m
  Simplenote/Classes/SPBlurEffectView.swift
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPOptionsViewController.m
  Simplenote/Classes/SPRatingsPromptView.swift
  Simplenote/Classes/SPSidebarContainerViewController.m
  Simplenote/Classes/SPSortBar.swift
  Simplenote/Classes/SPTagsListViewController.m
  Simplenote/Classes/SPUserInterface.swift
  Simplenote/Classes/UIBarButtonItem+Appearance.swift
  Simplenote/Classes/UINavigationBar+Appearance.swift
  Simplenote/DB5/VSThemeManager.h
  Simplenote/DB5/VSThemeManager.m
  Simplenote/Options.swift
  Simplenote/SPAppDelegate.m
  Simplenote/SPConstants.h
  Simplenote/SPConstants.m
  Simplenote/Simplenote-DB5.plist
Labels: debt
