Repository Automattic/simplenote-ios, pull requests merged in 2020-04, with the labels that each got.

#723 Add steps to take five more screenshots
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPOptionsViewController.m
  Simplenote/Classes/SPTagsListViewController.m
  SimplenoteScreenshots/SimplenoteScreenshots.swift
  fastlane/Fastfile
Labels: tooling

#718 Feature/beta builds on ci
  .circleci/config.yml
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: tooling

#717 Update hotfix tooling
  fastlane/Fastfile
Labels: tooling

#727 Release/4.17
  .circleci/config.yml
  External/DTPinLock/DTPinLockController.m
  Gemfile
  Gemfile.lock
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/NSRegularExpression+Simplenote.swift
  Simplenote/Classes/NSWritingDirection+Simplenote.swift
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteTableViewCell.swift
  Simplenote/Classes/SPNoteTableViewCell.xib
  Simplenote/Classes/SPOnboardingViewController.swift
  Simplenote/Classes/SPSidebarContainerViewController.m
  Simplenote/Classes/UIColor+Studio.swift
  Simplenote/Classes/UITextView+Simplenote.m
  Simplenote/Images.xcassets/Icons/icon_task_checked.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_task_checked.imageset/task-checked.pdf
  Simplenote/Images.xcassets/Icons/icon_task_checked.imageset/task_checked.png
  Simplenote/Images.xcassets/Icons/icon_task_checked.imageset/task_checked@2x.png
  Simplenote/Images.xcassets/Icons/icon_task_checked.imageset/task_checked@3x.png
  Simplenote/Images.xcassets/Icons/icon_task_unchecked.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_task_unchecked.imageset/task-unchecked.pdf
  Simplenote/Images.xcassets/Icons/icon_task_unchecked.imageset/task_unchecked.png
  Simplenote/Images.xcassets/Icons/icon_task_unchecked.imageset/task_unchecked@2x.png
  Simplenote/Images.xcassets/Icons/icon_task_unchecked.imageset/task_unchecked@3x.png
  Simplenote/NSMutableAttributedString+Styling.m
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  SimplenoteTests/NSMutableAttributedStringStylingTests.swift
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/Fastfile
  fastlane/Pluginfile
  fastlane/actions/ios_update_metadata_source.rb
  fastlane/download_metadata.swift
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: releases

#728 Merge release 4.17 into develop
  .circleci/config.yml
  Simplenote/ar.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/Fastfile
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: releases

#729 Adding support for Persian Language
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/fa.lproj/Localizable.strings
Labels: i18n

#731 Stop tracking .bundle folder
  .bundle/config
  .gitignore
Labels: tooling

#724 Add screenshots composer configuration for iPhone 8 Plus
  .gitignore
  Gemfile.lock
  SimplenoteScreenshots/SimplenoteScreenshots.swift
  fastlane/Fastfile
  fastlane/Pluginfile
  fastlane/appstoreres/.gitattributes
  fastlane/appstoreres/assets/iphone_8_plus.png
  fastlane/appstoreres/assets/styles/style.css
  fastlane/metadata/en-US/app_store_screenshot_1.txt
  fastlane/metadata/en-US/app_store_screenshot_2.txt
  fastlane/metadata/en-US/app_store_screenshot_3.txt
  fastlane/metadata/en-US/app_store_screenshot_4.txt
  fastlane/metadata/en-US/app_store_screenshot_5.txt
  fastlane/metadata/en-US/app_store_screenshot_6.txt
  fastlane/screenshots.json
Labels: tooling

#732 Update release-toolkit
  Gemfile.lock
  fastlane/Pluginfile
Labels: tooling

#737 Add testing checklist
  TESTING-CHECKLIST.md
Labels: documentation

#735 Case insensitive support for Tags Operator
  RELEASE-NOTES.txt
  Simplenote/Classes/NSPredicate+Simplenote.swift
Labels: bug

#736 Merge Release/4.18 back into develop
  RELEASE-NOTES.txt
  Simplenote/Classes/NSPredicate+Simplenote.swift
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases

#739 Merge Release/4.18 into develop
  .circleci/config.yml
  Scripts/update-translations.rb
  Simplenote/fa.lproj/Localizable.strings
  config/Version.Public.xcconfig
Labels: Releases
