Repository Automattic/simplenote-ios, pull requests merged in 2020-03, with the labels that each got.

#683 Fixing Dynamic Type Scaling
  Simplenote/Classes/UIFont+Simplenote.swift
Labels: [status] needs design review, bug

#685 Typography adjustments
  Simplenote/Classes/SPNoteTableViewCell.swift
  Simplenote/Classes/SPSortBar.swift
  Simplenote/Classes/UISearchBar+Simplenote.swift
Labels: spring cleaning

#686 Text Style Fixes
  Simplenote/Classes/UIColor+Studio.swift
Labels: enhancement

#688 Adjust spacing in note table cell
  Simplenote/Classes/SPNoteTableViewCell.swift
  Simplenote/Classes/SPNoteTableViewCell.xib
Labels: spring cleaning

#660 Add automation for release wrap up steps
  fastlane/Fastfile
Labels: tooling

#689 Fixes Issue 126 - Pin Lock UI Can Become Misaligned
  External/DTPinLock/DTPinLockController.m
Labels: bug

#693 Update Nokogiri to fix a security warning
  Gemfile.lock
Labels: tooling

#691 Fix Onboarding Colours
  Simplenote/Classes/SPOnboardingViewController.swift
  Simplenote/Classes/UIColor+Studio.swift
Labels: enhancement

#674 SPSidebarContainerViewController: RTL Support
  RELEASE-NOTES.txt
  Simplenote/Classes/SPSidebarContainerViewController.m
Labels: bug

#698 Add installable builds symbolication
  fastlane/Fastfile
Labels: tooling

#699 Remove rake to fix a CVE
  Gemfile
  Gemfile.lock
Labels: bug

#694 Update checklist icon assets
  Simplenote/Images.xcassets/Icons/icon_task_checked.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_task_checked.imageset/task-checked.pdf
  Simplenote/Images.xcassets/Icons/icon_task_checked.imageset/task_checked.png
  Simplenote/Images.xcassets/Icons/icon_task_checked.imageset/task_checked@2x.png
  Simplenote/Images.xcassets/Icons/icon_task_checked.imageset/task_checked@3x.png
  Simplenote/Images.xcassets/Icons/icon_task_unchecked.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_task_unchecked.imageset/task-unchecked.pdf
  Simplenote/Images.xcassets/Icons/icon_task_unchecked.imageset/task_unchecked.png
  Simplenote/Images.xcassets/Icons/icon_task_unchecked.imageset/task_unchecked@2x.png
  Simplenote/Images.xcassets/Icons/icon_task_unchecked.imageset/task_unchecked@3x.png
Labels: enhancement

#687 Fix editor font heirarchy
  Simplenote/Classes/SPNoteEditorViewController.m
Labels: enhancement

#703 Disable Bitcode
  Simplenote.xcodeproj/project.pbxproj
Labels: tooling

#701 Fixing Layout Issue(s)
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/NSWritingDirection+Simplenote.swift
  Simplenote/Classes/SPNoteTableViewCell.swift
  Simplenote/ar.lproj/Localizable.strings
Labels: bug

#665 Fix/build ITC lane
  Simplenote.xcodeproj/project.pbxproj
  fastlane/Fastfile
Labels: tooling

#704 Update rake to fix a security warning
  Gemfile.lock
Labels: tooling

#709 Merge release 4.17 into develop
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/actions/ios_update_metadata_source.rb
  fastlane/download_metadata.swift
Labels: releases

#706 Merge Release/4.17 back into develop
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/actions/ios_update_metadata_source.rb
  fastlane/download_metadata.swift
Labels: releases

#710 Update to shared lanes
  Gemfile.lock
  fastlane/Pluginfile
  fastlane/actions/ios_update_metadata_source.rb
Labels: tooling

#708 Fixing List Processing
  RELEASE-NOTES.txt
  Simplenote/Classes/NSRegularExpression+Simplenote.swift
  Simplenote/NSMutableAttributedString+Styling.m
  SimplenoteTests/NSMutableAttributedStringStylingTests.swift
Labels: bug

#720 Merge release 4.17 into develop
  RELEASE-NOTES.txt
  Simplenote/Classes/NSRegularExpression+Simplenote.swift
  Simplenote/NSMutableAttributedString+Styling.m
  SimplenoteTests/NSMutableAttributedStringStylingTests.swift
  config/Version.Public.xcconfig
Labels: releases

#721 Add crypto compliance key
  Simplenote/Simplenote-Info.plist
Labels: tooling

#722 Setup test target for screenshots automation
  .configure
  .gitignore
  README.md
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcodeproj/xcshareddata/xcschemes/SimplenoteScreenshots.xcscheme
  Simplenote/Classes/SPNoteListViewController.m
  SimplenoteScreenshots/Info.plist
  SimplenoteScreenshots/ScreenshotsCredentials-demo.swift
  SimplenoteScreenshots/SimplenoteScreenshots.swift
  SimplenoteScreenshots/SnapshotHelper.swift
  fastlane/Fastfile
Labels: tooling
