Repository Automattic/simplenote-ios, pull requests merged in 2020-06, with the labels that each got.

#764 Merge release 4.19 into develop
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/cy.lproj/Localizable.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/el.lproj/Localizable.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/fa.lproj/Localizable.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Needs Screenshots, Releases

#768 SPBlurEffectView: Change maximumAlphaGradientOffset to 22 from 30
  Simplenote/Classes/SPBlurEffectView.swift
Labels: bug

#772 Fixing Tinting Issues
  Simplenote/Classes/SPOnboardingViewController.xib
  Simplenote/Images.xcassets/launch-logo.imageset/Contents.json
  Simplenote/Images.xcassets/launch-logo.imageset/launch-logo.pdf
  Simplenote/Resources/LaunchScreen.storyboard
Labels: bug

#770 Localizing DTPinLock
  Scripts/localize.py
Labels: i18n

#774 Fix: Share Extension Navigation Tint
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  SimplenoteShare/Extensions/UIColor+Simplenote.swift
  SimplenoteShare/ViewControllers/SharePresentationController.swift
Labels: bug

#767 Add lane to upload screenshots
  .ruby-version
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: tooling

#776 Tags Editor: RTL Support
  RELEASE-NOTES.txt
  Simplenote/Classes/SPTagView.h
  Simplenote/Classes/SPTagView.m
Labels: i18n

#779 Merge 4.20.0-beta1 into develop
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/en.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases

#778 SPNoteListViewController: Preventing UITableView Crash
  Simplenote/Classes/SPNoteListViewController.m
Labels: crash

#787 Merge release 4.20 into develop
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/cy.lproj/Localizable.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/el.lproj/Localizable.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/fa.lproj/Localizable.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/app_store_screenshot_1.txt
  fastlane/metadata/en-US/app_store_screenshot_2.txt
  fastlane/metadata/en-US/app_store_screenshot_3.txt
  fastlane/metadata/en-US/app_store_screenshot_4.txt
  fastlane/metadata/en-US/app_store_screenshot_5.txt
  fastlane/metadata/en-US/app_store_screenshot_6.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#791 Privacy Notice for California Users
  RELEASE-NOTES.txt
  Simplenote/Classes/SPAboutViewController.swift
Labels: [priority] high
