Repository Automattic/simplenote-ios, pull requests merged in 2020-02, with the labels that each got.

#601 SearchBar: Hidden when visualizing Trash
  RELEASE-NOTES.txt
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController.h
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPTransitionController.m
Labels: [feature] search

#602 Note Cell: UX Refresh!
  RELEASE-NOTES.txt
  Simplenote/Classes/NSMutableAttributedString+Simplenote.swift
  Simplenote/Classes/NSString+Search.h
  Simplenote/Classes/NSString+Search.m
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteTableViewCell.swift
  Simplenote/Classes/SPNoteTableViewCell.xib
  Simplenote/Classes/SnapshotRenderer.swift
  Simplenote/Classes/UIColor+Studio.swift
Labels: [feature] search

#605 Tags Cell: UX Refresh!
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteTableViewCell.swift
  Simplenote/Classes/SPSectionHeaderView.swift
  Simplenote/Classes/SPSectionHeaderView.xib
  Simplenote/Classes/SPTagTableViewCell.swift
  Simplenote/Classes/SPTagTableViewCell.xib
  Simplenote/Classes/UIFont+Simplenote.swift
Labels: [feature] search

#597 Disabling custom transitions: Part 1
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPTransitionController.h
  Simplenote/Classes/SPTransitionController.m
  Simplenote/Classes/SnapshotRenderer.swift
  Simplenote/SPAppDelegate.m
Labels: [feature] search

#598 Disabling custom transitions: Part 2
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPTransitionController.m
  Simplenote/Classes/SPTransitionSnapshot.h
  Simplenote/Classes/SPTransitionSnapshot.m
  Simplenote/Classes/SnapshotRenderer.swift
Labels: debt

#612 SPNoteTableViewCell: Nukes solid BG optimization
  Simplenote/Classes/SPNoteTableViewCell.swift
Labels: [feature] search

#613 Preventing First Row Animation Glitch
  Simplenote/Classes/SPNoteListViewController.m
Labels: [feature] search

#620 Notes List: Updates SearchBar's Placeholder
  Simplenote/Classes/NotesListState.swift
  Simplenote/Classes/SPNoteListViewController.m
Labels: [feature] search

#607 Not restoring First Responder
  Simplenote/Classes/SPEditorTextView.h
  Simplenote/Classes/SPEditorTextView.m
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPTransitionController.h
  Simplenote/Classes/SPTransitionController.m
Labels: [feature] search

#609 Dismissing SearchBar's Responder status on Scroll
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
Labels: [feature] search

#610 Preserving NavigationBar Hidden state
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SearchDisplayController.swift
Labels: [feature] search

#611 Restoring SearchBar's Autocapitalization
  Simplenote/Classes/SearchDisplayController.swift
Labels: [feature] search

#614 Preventing insane bottom insets
  Simplenote/Classes/SPNoteListViewController.m
Labels: bug

#615 Fixing Incorrect Keyboard Style
  RELEASE-NOTES.txt
  Simplenote/Classes/SPNoteEditorViewController.m
Labels: bug

#617 Resigning SearchBar's Responder status when opening Notes
  Simplenote/Classes/SPNoteListViewController.m
Labels: bug

#619 Exiting SearchMode when pressing `Done`
  RELEASE-NOTES.txt
  Simplenote/Classes/SPNoteListViewController.m
Labels: bug

#623 List: Enabling Row Separators
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController.h
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPNoteTableViewCell.swift
  Simplenote/Classes/SPTagTableViewCell.swift
Labels: [feature] search

#624 UIColor+Studio: Updates Secondary Action Color
  Simplenote/Classes/UIColor+Studio.swift
Labels: [feature] search

#626 Updates (Deleted) Swipeable Actions Colors
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/UIColor+Studio.swift
Labels: debt

#621 Supporting accent characters in Search
  RELEASE-NOTES.txt
  Simplenote/Classes/NSPredicate+Simplenote.swift
  SimplenoteTests/NSPredicateSimplenoteTests.swift
Labels: [feature] search

#625 Restoring results when the Search Keyword is Empty
  Simplenote/Classes/NotesListController.swift
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController.m
Labels: [feature] search

#627 Dismiss the keyboard when search is pressed
  Simplenote/Classes/SearchDisplayController.swift
Labels: [feature] search

#629 SPSectionHeaderView: Updates Leading Margins
  Simplenote/Classes/SPSectionHeaderView.xib
Labels: [feature] search

#628 Updates Preview Generation
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/CSSearchable+Helpers.swift
  Simplenote/Classes/NSString+Condensing.h
  Simplenote/Classes/NSString+Condensing.m
  Simplenote/Classes/Note.h
  Simplenote/Classes/Note.m
  Simplenote/Simplenote-Bridging-Header.h
  SimplenoteTests/NSStringCondensingTests.swift
Labels: [feature] search

#630 Search Highlight Background
  Simplenote/Classes/NSMutableAttributedString+Simplenote.swift
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteTableViewCell.swift
  Simplenote/Classes/SPTextView.m
  Simplenote/Classes/UIColor+Studio.swift
Labels: [feature] search

#634 Revert "Search Highlight Background"
  Simplenote/Classes/NSMutableAttributedString+Simplenote.swift
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteTableViewCell.swift
  Simplenote/Classes/SPTextView.m
  Simplenote/Classes/UIColor+Studio.swift
Labels: [feature] search

#631 Darker Mode
  RELEASE-NOTES.txt
  Simplenote/Classes/ColorStudio.swift
  Simplenote/Classes/UIColor+Studio.swift
  Simplenote/Classes/UIImage+Dynamic.swift
Labels: enhancement

#633 Feature/installable builds
  .circleci/config.yml
  .configure
  .configure-files/SPCredentials.swift.enc
  .configure-files/google_cloud_keys.json.enc
  .configure-files/project.env.enc
  .gitignore
  Gemfile.lock
  Simplenote.xcodeproj/project.pbxproj
  SimplenoteShare/SimplenoteShareDistribution Alpha.entitlements
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: tooling

#637 Properly Dismissing Feedback UI
  RELEASE-NOTES.txt
  Simplenote/Classes/SPFeedbackManager.swift
  Simplenote/Classes/SPNoteListViewController.m
Labels: [priority] high, bug

#638 Adjusting NavigationBar's Alpha
  Simplenote/Classes/SPInteractivePushPopAnimationController.m
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPSheetController.swift
  Simplenote/Classes/SPSidebarContainerViewController.m
  Simplenote/Classes/UIColor+Studio.swift
  Simplenote/Classes/UIKitConstants.swift
Labels: enhancement

#642 Merge 4.15.1 into develop
  RELEASE-NOTES.txt
  Simplenote/Classes/SPFeedbackManager.swift
  Simplenote/Classes/SPNoteListViewController.m
  config/Version.Public.xcconfig
  fastlane/Deliverfile
Labels: releases

#635 Empty States
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPEditorTextView.m
  Simplenote/Classes/SPEmptyListView.h
  Simplenote/Classes/SPEmptyListView.m
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController.h
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPOnboardingViewController.swift
  Simplenote/Classes/SPOnboardingViewController.xib
  Simplenote/Classes/SPPlaceholderView.swift
  Simplenote/Classes/SPToggle.m
  Simplenote/Classes/UIColor+Studio.swift
  Simplenote/Classes/UIColorName.swift
  Simplenote/Classes/UIImageName.swift
  Simplenote/Classes/VSTheme+Keys.swift
  Simplenote/Colors.xcassets/emptyListViewFontColor.colorset/Contents.json
  Simplenote/Images.xcassets/logo_login.imageset/Contents.json
  Simplenote/Simplenote-DB5.plist
Labels: [feature] search

#641 Merge Release/4.15.1 into Master
  RELEASE-NOTES.txt
  Simplenote/Classes/SPFeedbackManager.swift
  Simplenote/Classes/SPNoteListViewController.m
  config/Version.Public.xcconfig
  fastlane/Deliverfile
Labels: releases

#648 Light Color Adjustments
  Simplenote/Classes/ColorStudio.swift
  Simplenote/Classes/UIColor+Studio.swift
Labels: accessibility, enhancement

#640 Implementing SortBar: Mark I
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController.h
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPSortBar.swift
  Simplenote/Classes/SPSortBar.xib
  Simplenote/Classes/SearchDisplayController.swift
  Simplenote/Classes/SortMode.swift
  Simplenote/Classes/UIColor+Studio.swift
  Simplenote/Classes/UIView+Animations.swift
  Simplenote/Images.xcassets/Icons/icon_sort_order.imageset/Contents.json
Labels: [feature] search

#643 Implementing SortBar: Mark II
  Simplenote/Classes/NotesListController.swift
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController.h
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPNotifications.h
  Simplenote/Classes/SPNotifications.m
  Simplenote/Classes/SPSortBar.swift
  Simplenote/Classes/SPTracker.h
  Simplenote/Classes/SPTracker.m
  Simplenote/Classes/UserDefaults+Simplenote.swift
  Simplenote/Options.swift
  SimplenoteTests/NotesListControllerTests.swift
  SimplenoteTests/OptionsTests.swift
Labels: [feature] search

#649 Search: Displaying Relevant Dates
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/DateFormatter+Simplenote.swift
  Simplenote/Classes/NSWritingDirection+Simplenote.swift
  Simplenote/Classes/Note+List.swift
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteTableViewCell.swift
Labels: [feature] search

#647 Password Autofill
  RELEASE-NOTES.txt
  Simplenote/Classes/SPAuthViewController.swift
  Simplenote/Classes/SPTextInputView.swift
  Simplenote/Simplenote-Internal.entitlements
  Simplenote/Simplenote.entitlements
Labels: enhancement

#644 Adjusting Logout Overlay
  Simplenote/Classes/SPModalActivityIndicator.h
  Simplenote/Classes/SPModalActivityIndicator.m
  Simplenote/Classes/UIColor+Studio.swift
  Simplenote/Classes/UIKitConstants.swift
Labels: enhancement

#645 Adjusting Launch Screen
  RELEASE-NOTES.txt
  Simplenote/Colors.xcassets/simplenoteLaunchBackgroundColor.colorset/Contents.json
  Simplenote/Resources/LaunchScreen.storyboard
Labels: enhancement

#653 Note List: Short Date Style
  Simplenote/Classes/DateFormatter+Simplenote.swift
Labels: enhancement

#654 Search Mode: Adjusting Sort Descriptors
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/NSSortDescriptor+Simplenote.swift
  Simplenote/Classes/NotesListController.swift
  Simplenote/Classes/NotesListState.swift
  Simplenote/Classes/SortMode+Descriptors.swift
Labels: [feature] search

#657 SPNoteTableViewCell: New ImageView Anchor
  Simplenote/Classes/SPNoteTableViewCell.xib
Labels: bug

#651 General Colour Adjustments
  External/DTPinLock/DTPinLockController.m
  Simplenote/Classes/ColorStudio.swift
  Simplenote/Classes/SPBlurEffectView.swift
  Simplenote/Classes/SPDefaultTableViewCell.swift
  Simplenote/Classes/SPEntryListCell.m
  Simplenote/Classes/SPEntryListViewController.m
  Simplenote/Classes/SPNavigationController.m
  Simplenote/Classes/SPOptionsViewController.m
  Simplenote/Classes/SPTableViewController.m
  Simplenote/Classes/SPTagsListViewController.m
  Simplenote/Classes/SPThemeViewController.swift
  Simplenote/Classes/UIColor+Studio.swift
  Simplenote/Classes/UIFont+Simplenote.swift
  Simplenote/Classes/UITableView+Simplenote.swift
  Simplenote/SPAppDelegate.m
Labels: enhancement

#652 SectionHeaderView: Switching Initialization Mechanism
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPSectionHeaderView.swift
  Simplenote/Classes/SPSectionHeaderView.xib
Labels: bug

#659 Fix Dark Dividers in Light Mode
  Simplenote/Classes/UIColor+Studio.swift
Labels: spring cleaning

#656 SortBy Popover: Properly Centering on iOS <13
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController.h
  Simplenote/Classes/SPSortBar.swift
Labels: bug

#662 Adjust transparency of blurry bars
  Simplenote/Classes/UIColor+Studio.swift
  Simplenote/Classes/UIKitConstants.swift
Labels: spring cleaning

#666 Merge Release/4.16 into develop
  RELEASE-NOTES.txt
  Simplenote/en.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: releases

#667 Update Fastlane and Sentry gems
  Gemfile.lock
Labels: tooling

#673 Tag Operator: Not producing partial matches
  Simplenote/Classes/NSPredicate+Simplenote.swift
  SimplenoteTests/NSPredicateSimplenoteTests.swift
Labels: bug

#675 Filtering out (reserved) Tag Names
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/SPAppDelegate+Extensions.swift
Labels: bug

#679 Merge Release/4.16 into develop
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/NSPredicate+Simplenote.swift
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/SPAppDelegate+Extensions.swift
  SimplenoteTests/NSPredicateSimplenoteTests.swift
Labels: releases

#664 Notes List: Fixing Checklist Processing
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/NSRegularExpression+Simplenote.swift
  Simplenote/Classes/NSString+Simplenote.swift
  Simplenote/Classes/SPEditorTextView.h
  Simplenote/Classes/SPEditorTextView.m
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteTableViewCell.swift
  Simplenote/Classes/UIImageName.swift
  Simplenote/NSMutableAttributedString+Styling.h
  Simplenote/NSMutableAttributedString+Styling.m
  Simplenote/SPTextAttachment.swift
  SimplenoteTests/NSMutableAttributedStringStylingTests.swift
  SimplenoteTests/SPChecklistTest.swift
Labels: bug

#678 Support the unicode bullet as a list item bullet in unordered lists
  Simplenote/Classes/UITextView+Simplenote.m
Labels: enhancement
