Repository Automattic/simplenote-ios, pull requests merged in 2020-08, with the labels that each got.

#829 Update and organize the testing checklist
  TESTING-CHECKLIST.md
Labels: documentation, enhancement

#826 First pass at wiring up state restoration.
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPSidebarContainerViewController.m
  Simplenote/SPAppDelegate+Extensions.swift
  Simplenote/SPAppDelegate.h
  Simplenote/SPAppDelegate.m
Labels: bug

#833 Merge 4.22.0 into develop
  Simplenote/id.lproj/Localizable.strings
  Simplenote/ja.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/download_metadata.swift
  fastlane/metadata/de-DE/description.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/description.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/description.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/description.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/description.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/description.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/description.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/description.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/description.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/description.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/description.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/description.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/description.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/description.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/description.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/description.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#837 Merge 4.23.0 beta 1 into develop
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases

#843 Integrates SimplenoteFoundation
  .circleci/config.yml
  Podfile
  Podfile.lock
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Simplenote/Classes/FetchedResultsControllerDelegateWrapper.swift
  Simplenote/Classes/NSManagedObject+Simplenote.swift
  Simplenote/Classes/NotesListController.swift
  Simplenote/Classes/ResultsController.swift
  Simplenote/Classes/ResultsObjectsChangeset.swift
  Simplenote/Classes/UITableView+ResultsController.swift
  Simplenote/ResultsSectionsChangeset.swift
  Simplenote/SPAppDelegate+Extensions.swift
  SimplenoteTests/MockupTableView.swift
  SimplenoteTests/NotesListControllerTests.swift
  SimplenoteTests/ResultsControllerTests.swift
  SimplenoteTests/ResultsControllerUIKitTests.swift
  SimplenoteTests/ResultsSectionsChangesetTests.swift
Labels: architecture

#845 Integrates SimplenoteSearch
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Simplenote/Classes/NSPredicate+Simplenote.swift
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/String+Simplenote.swift
  SimplenoteTests/NSPredicateSimplenoteTests.swift
  SimplenoteTests/StringSimplenoteTests.swift
Labels: enhancement

#847 Fixing Text Selection
  RELEASE-NOTES.txt
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPTextView.h
  Simplenote/Classes/SPTextView.m
Labels: bug

#848 Use the `main` mobile secrets branch
  .configure
Labels: accessibility

#846 New note options view UI
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/NoteOptionsViewController.swift
  Simplenote/Classes/SPNavigationController.m
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPNoteEditorViewController.h
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SwitchTableViewCell.swift
  Simplenote/Classes/Value1TableViewCell.swift
Labels: spring cleaning

#850 Merge hotfix 4.22.1 into release 4.23 (with conflict resolution)
  RELEASE-NOTES.txt
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPTextView.h
  Simplenote/Classes/SPTextView.m
Labels: Releases
