Repository Automattic/simplenote-ios, pull requests merged in 2020-10, with the labels that each got.

#898 Merge release 4.25 into develop
  Gemfile.lock
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/cy.lproj/Localizable.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/el.lproj/Localizable.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/fa.lproj/Localizable.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#900 Merge release 4.26 beta 1 into develop
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/en.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases

#903 Editor: Drops direct ivar indirections
  Simplenote/Classes/SPNoteEditorViewController.h
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/SPAppDelegate.m
Labels: debt

#904 Renames OptionsViewController > SettingsViewController
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPOptionsViewController.h
  Simplenote/Classes/SPSettingsViewController.h
  Simplenote/Classes/SPSettingsViewController.m
  Simplenote/Classes/SPTagsListViewController.m
  Simplenote/SPAppDelegate.h
  Simplenote/SPAppDelegate.m
Labels: debt

#902 Contextual Menu Support
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
Labels: interlinking

#916 Editor: Fixing iOS 14 Autoscroll Bug
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPEditorTapRecognizerDelegate.swift
  Simplenote/Classes/SPEditorTextView.m
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/UIGestureRecognizer+Simplenote.swift
  Simplenote/Classes/UITextView+Simplenote.swift
Labels: [priority] high, bug

#905 Nü Note Options: Mark I
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/OptionsViewController.swift
  Simplenote/Classes/OptionsViewController.xib
  Simplenote/Classes/SPNavigationController.m
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPNoteEditorViewController.h
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SwitchTableViewCell.swift
  Simplenote/Classes/UIImageName.swift
  Simplenote/Images.xcassets/Icons/icon_copy.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_copy.imageset/icon_copy.pdf
  Simplenote/Images.xcassets/Icons/icon_note.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_note.imageset/icon_note.pdf
  Simplenote/Images.xcassets/Icons/icon_published.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_published.imageset/icon_published.pdf
  Simplenote/Value1TableViewCell.swift
Labels: interlinking, spring cleaning

#906 Nü Note Options: Mark II
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/NSURL+Links.swift
  Simplenote/Classes/OptionsViewController.swift
  Simplenote/Classes/SPNavigationController.h
  Simplenote/Classes/SPNavigationController.m
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPNoteEditorViewController.h
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPObjectManager.h
  Simplenote/Classes/SPObjectManager.m
  Simplenote/Classes/SPTracker.h
  Simplenote/Classes/SPTracker.m
  Simplenote/Classes/SimplenoteConstants.swift
  Simplenote/Classes/SwitchTableViewCell.swift
  Simplenote/Classes/UIKitConstants.swift
  Simplenote/Classes/UIPasteboard+Interlink.swift
  Simplenote/Classes/UIPasteboard+Note.swift
  Simplenote/Classes/UIViewController+Helpers.swift
  Simplenote/Classes/UserDefaults+Simplenote.swift
  Simplenote/Note+Links.swift
  Simplenote/Options.swift
  Simplenote/SPAppDelegate.m
  Simplenote/SPConstants.h
  Simplenote/SPConstants.m
Labels: interlinking, spring cleaning

#907 Nü Note Options: Mark III
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPActionButton.h
  Simplenote/Classes/SPActionButton.m
  Simplenote/Classes/SPActivityView.h
  Simplenote/Classes/SPActivityView.m
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPToggle.h
  Simplenote/Classes/SPToggle.m
Labels: debt, interlinking, spring cleaning

#909 Nü Note Options: Mark IV
  Simplenote/Classes/OptionsViewController.swift
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPNoteEditorViewController.h
  Simplenote/Classes/SPNoteEditorViewController.m
Labels: spring cleaning

#910 Nü Note Options: Mark V
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/Note+Properties.swift
  Simplenote/Classes/Note.h
  Simplenote/Classes/Note.m
  Simplenote/Classes/OptionsViewController.swift
  Simplenote/Classes/SPAddCollaboratorsViewController.h
  Simplenote/Classes/SPAddCollaboratorsViewController.m
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPObjectManager.h
  Simplenote/Classes/SPObjectManager.m
  Simplenote/Simplenote-Bridging-Header.h
Labels: spring cleaning

#924 Drops Navigation Bar Shrinking
  RELEASE-NOTES.txt
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPNoteEditorViewController.h
  Simplenote/Classes/SPNoteEditorViewController.m
Labels: debt

#929 Note Table Cell: Adjusting Paddings
  RELEASE-NOTES.txt
  Simplenote/Classes/SPNoteTableViewCell.swift
  Simplenote/Classes/SPNoteTableViewCell.xib
Labels: [feature] note list

#925 Navigation Bar: Drops custom metrics
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPMarkdownPreviewViewController.m
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPNoteEditorViewController.h
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPOutsideTouchView.h
  Simplenote/Classes/SPOutsideTouchView.m
  Simplenote/Classes/UIBarButtonItem+Images.h
  Simplenote/Classes/UIBarButtonItem+Images.m
  Simplenote/Classes/UIButton+Images.h
  Simplenote/Classes/UIButton+Images.m
  Simplenote/Classes/UIViewController+Extensions.h
  Simplenote/Classes/UIViewController+Extensions.m
  Simplenote/Classes/UIViewController+Helpers.swift
Labels: debt

#926 Nü Note Options: Mark VI
  Simplenote/Classes/OptionsViewController.swift
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPTracker.h
  Simplenote/Classes/SPTracker.m
  Simplenote/Classes/UIImageName.swift
  Simplenote/Images.xcassets/Icons/icon_ellipsis_outline.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_ellipsis_outline.imageset/icon_ellipsis_outline.pdf
  Simplenote/Value1TableViewCell.swift
Labels: spring cleaning

#835 Nü History Slider
  Podfile.lock
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPActionSheet.h
  Simplenote/Classes/SPActionSheet.m
  Simplenote/Classes/SPHorizontalPickerGradientView.h
  Simplenote/Classes/SPHorizontalPickerGradientView.m
  Simplenote/Classes/SPHorizontalPickerView.h
  Simplenote/Classes/SPHorizontalPickerView.m
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPNoteEditorViewController.h
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteHistoryViewController.swift
  Simplenote/Classes/SPNoteHistoryViewController.xib
  Simplenote/Classes/SPVersionPickerViewCell.h
  Simplenote/Classes/SPVersionPickerViewCell.m
  Simplenote/Classes/UIColor+Studio.swift
  Simplenote/Classes/UIKitConstants.swift
  Simplenote/Controllers/VersionsController.swift
  Simplenote/SPAppDelegate+Extensions.swift
  Simplenote/SPAppDelegate.h
  Simplenote/SPAppDelegate.m
  Simplenote/SPCardConfigurable.swift
  Simplenote/SPCardDismissalAnimator.swift
  Simplenote/SPCardPresentationAnimator.swift
  Simplenote/SPCardPresentationController.swift
  Simplenote/SPCardTransitioningManager.swift
  Simplenote/SPCardView.swift
  Simplenote/SPHistoryVersion.swift
  Simplenote/SPManagedObject+Version.swift
  Simplenote/SPNoteHistoryController.swift
  Simplenote/SPNoteHistoryControllerDelegate.swift
  Simplenote/SPShadowView.swift
  Simplenote/SPSnappingSlider.swift
  Simplenote/UISlider+Simplenote.swift
  Simplenote/UIView+Constraints.swift
Labels: spring cleaning

#933 Merge release 4.26 final into develop
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/cy.lproj/Localizable.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/el.lproj/Localizable.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/fa.lproj/Localizable.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#936 Drops legacy Views
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPButton.h
  Simplenote/Classes/SPButton.m
  Simplenote/Classes/SPHorizontalPickerViewCell.h
  Simplenote/Classes/SPHorizontalPickerViewCell.m
  Simplenote/Classes/SPSideBySideView.h
  Simplenote/Classes/SPSideBySideView.m
Labels: debt

#928 List: Contextual Menu Previewing Style
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPTagView.h
  Simplenote/Classes/SPTagView.m
  Simplenote/Classes/UIColor+Studio.swift
Labels: [feature] note list

#940 Updates Dependencies + CI Xcode12 Support
  .circleci/config.yml
  Podfile
  Podfile.lock
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: task

#941 Fixing Search Bar Height
  RELEASE-NOTES.txt
  Simplenote/Classes/UISearchBar+Simplenote.swift
Labels: bug

#939 Nü Metrics: Mark I
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/DateFormatter+Simplenote.swift
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPNoteEditorViewController.h
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteHistoryViewController.xib
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/HuggableTableView.swift
  Simplenote/Information/NoteInformationViewController.swift
  Simplenote/Information/NoteInformationViewController.xib
  Simplenote/NoteMetrics.swift
  Simplenote/NumberFormatter+Simplenote.swift
  Simplenote/SPCardPresentationController.swift
  Simplenote/Value1TableViewCell.swift
Labels: spring cleaning

#942 Nü Metrics: Mark II
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPNoteEditorViewController.h
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Information/NoteInformationController.swift
  Simplenote/Information/NoteInformationViewController.swift
  Simplenote/Information/NoteInformationViewController.xib
Labels: spring cleaning

#948 Nü Metrics: Mark III
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/DateFormatter+Simplenote.swift
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/UIFont+Simplenote.swift
  Simplenote/Classes/UITableViewCell+Simplenote.swift
  Simplenote/Information/NoteInformationController.swift
  Simplenote/Information/NoteInformationViewController.swift
  Simplenote/Note+Links.swift
  Simplenote/SPAppDelegate+Extensions.swift
  Simplenote/SPCardPresentationController.swift
  Simplenote/SubtitleTableViewCell.swift
  Simplenote/TableHeaderViewCell.swift
  Simplenote/UIView+Constraints.swift
Labels: interlinking, spring cleaning

#920 Enforce use of bundle exec in Fastfile+Podfile
  Podfile
  Podfile.lock
  fastlane/Fastfile
Labels: tooling

#959 Silencing Cocoapods Warnings
  Podfile
  Podfile.lock
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcodeproj/xcshareddata/xcschemes/Simplenote.xcscheme
  Simplenote.xcodeproj/xcshareddata/xcschemes/SimplenoteScreenshots.xcscheme
Labels: debt

#958 Update Search Highlight Colors
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/NSString+Search.m
  Simplenote/Classes/NSTextStorage+Highlight.h
  Simplenote/Classes/NSTextStorage+Highlight.m
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPTextView.h
  Simplenote/Classes/SPTextView.m
  Simplenote/Classes/UIColor+Studio.swift
  Simplenote/NSTextStorage+Simplenote.swift
  Simplenote/Simplenote-Bridging-Header.h
Labels: [feature] search

#957 Update Sort Bar
  Simplenote/Classes/SPSortBar.xib
Labels: [feature] search

#962 CONTRIBUTING.md: Add information about our PR merge policy
  CONTRIBUTING.md
Labels: documentation

#961 Fix highlight when search query contains multiple words
  Simplenote/Classes/NSString+Search.m
Labels: [feature] search, bug

#964 Bugfix: Tag Autocomplete
  RELEASE-NOTES.txt
  Simplenote/Classes/SPEditorTapRecognizerDelegate.swift
  Simplenote/Classes/SPEditorTextView.m
Labels: bug
