Repository Automattic/simplenote-ios, pull requests merged in 2021-08, with the labels that each got.

#1354 In app account deletion
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/AccountRemote.swift
  Simplenote/Classes/SPAuthError.swift
  Simplenote/Classes/SPAuthHandler.swift
  Simplenote/Classes/SPSettingsViewController+Extensions.swift
  Simplenote/Classes/SPSettingsViewController.m
  Simplenote/Classes/SignupRemote.swift
  Simplenote/Classes/SimplenoteConstants.swift
  Simplenote/Classes/UIColor+Studio.swift
  Simplenote/Controllers/AccountDeletionController.swift
  Simplenote/Date+Simplenote.swift
  Simplenote/NoticeFactory.swift
  Simplenote/Remote.swift
  Simplenote/RemoteError.swift
  Simplenote/SPAppDelegate+Extensions.swift
  Simplenote/SPAppDelegate.h
  Simplenote/SPAppDelegate.m
  Simplenote/SPTracker+Extensions.swift
  Simplenote/SpinnerViewController.swift
  Simplenote/Verification/AccountVerificationController.swift
  Simplenote/Verification/AccountVerificationRemote.swift
  Simplenote/Verification/AccountVerificationViewController.swift
  SimplenoteTests/RemoteResult+TestHelpers.swift
  SimplenoteTests/SignupRemoteTests.swift
  SimplenoteTests/Verification/AccountVerificationControllerTests.swift
  SimplenoteTests/Verification/AccountVerificationRemoteTests.swift
  SimplenoteTests/Verification/Helpers/MockAccountVerificationRemote.swift
Labels: enhancement

#1378 Add bulk trash test
  SimplenoteUITests/Generic.swift
  SimplenoteUITests/NoteList.swift
  SimplenoteUITests/SimplenoteUITestsNoteEditor.swift
  SimplenoteUITests/UIDs.swift
Labels: UIAutomation

#1373 [Tooling] Fix hotfix lanes
  fastlane/Fastfile
Labels: tooling

#1379 Finish intents extension entitlements setup
  Simplenote.xcodeproj/project.pbxproj
  SimplenoteIntents/SimplenoteIntents.entitlements
  SimplenoteIntents/SimplenoteIntentsDistributionAlpha.entitlements
  SimplenoteIntents/SimplenoteIntentsDistributionInternal.entitlements
Labels: tooling

#1384 Updated release notes for 4.42
  RELEASE-NOTES.txt
Labels: Releases

#1381 Fixed a bug where the account deletion token was created incorrectly
  Simplenote/AccountRemote.swift
  Simplenote/Classes/SPAuthError.swift
  Simplenote/Classes/SPAuthHandler.swift
  Simplenote/Classes/SPSettingsViewController+Extensions.swift
  Simplenote/Classes/SignupRemote.swift
  Simplenote/Controllers/AccountDeletionController.swift
  Simplenote/RemoteError.swift
  Simplenote/SPAppDelegate+Extensions.swift
  Simplenote/SPAppDelegate.m
Labels: bug, [feature] settings

#1374 Added group entitlements to simplenote intents
  Simplenote.xcodeproj/project.pbxproj
  SimplenoteIntents/SimplenoteIntents.entitlements
  SimplenoteIntents/SimplenoteIntentsDebug.entitlements
  SimplenoteIntents/SimplenoteIntentsDistributionAlpha.entitlements
  SimplenoteIntents/SimplenoteIntentsDistributionInternal.entitlements
Labels: [feature] Widgets

#1382 Merge 4.41 final to develop
  Simplenote/pt-BR.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/keywords.txt
  fastlane/metadata/ar-SA/promotional_text.txt
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/keywords.txt
  fastlane/metadata/de-DE/promotional_text.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/keywords.txt
  fastlane/metadata/default/promotional_text.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/keywords.txt
  fastlane/metadata/en-US/promotional_text.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/keywords.txt
  fastlane/metadata/es-ES/promotional_text.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/keywords.txt
  fastlane/metadata/fr-FR/promotional_text.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/keywords.txt
  fastlane/metadata/id/promotional_text.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/keywords.txt
  fastlane/metadata/it/promotional_text.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/keywords.txt
  fastlane/metadata/ja/promotional_text.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/keywords.txt
  fastlane/metadata/ko/promotional_text.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/keywords.txt
  fastlane/metadata/nl-NL/promotional_text.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/keywords.txt
  fastlane/metadata/pt-BR/promotional_text.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/keywords.txt
  fastlane/metadata/ru/promotional_text.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/keywords.txt
  fastlane/metadata/sv/promotional_text.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/keywords.txt
  fastlane/metadata/tr/promotional_text.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/keywords.txt
  fastlane/metadata/zh-Hans/promotional_text.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/keywords.txt
  fastlane/metadata/zh-Hant/promotional_text.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#1386 Merge 4.42 code freeze to develop
  Gemfile.lock
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/en.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/Pluginfile
  fastlane/download_metadata.swift
Labels: Releases

#1385 Undo via snackbar and copy internal link tests
  SimplenoteUITests/NoteEditor.swift
  SimplenoteUITests/NoteList.swift
  SimplenoteUITests/SimplenoteUITestsNoteEditor.swift
  SimplenoteUITests/UIDs.swift
Labels: UIAutomation

#1391 Fixed an issue where tags aren't removed from notes when deleted
  Simplenote/Classes/SPObjectManager+Simplenote.swift
Labels: bug

#1396 Fix syntax errors in AppStoreStrings.pot
  Simplenote/Resources/AppStoreStrings.pot
Labels: Releases

#1394 Password verification alert
  RELEASE-NOTES.txt
  Simplenote/Classes/SPAuthError.swift
  Simplenote/Classes/SPAuthViewController.swift
Labels: enhancement

#1392 Use XCUITestsHelper to query user interface style (dark mode)
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SimplenoteScreenshots/SimplenoteScreenshots.swift
  SimplenoteScreenshots/XCTest+Extensions.swift
Labels: Testing

#1397 Fixed a bug where non http/https urls crashed when opened from markdown
  Simplenote/Classes/SPMarkdownPreviewViewController.m
Labels: bug, crash, [feature] markdown

#1395 Log out user account after account deletion success
  Podfile
  Podfile.lock
  Simplenote/Classes/SPSettingsViewController+Extensions.swift
  Simplenote/Controllers/AccountDeletionController.swift
  Simplenote/SPAppDelegate+Extensions.swift
  Simplenote/SPAppDelegate.m
Labels: enhancement

#1398 Added error case at login if user email is not verified
  RELEASE-NOTES.txt
  Simplenote/Classes/SPAuthError.swift
  Simplenote/Classes/SPAuthViewController.swift
  Simplenote/Classes/UIAlertController+Helpers.swift
Labels: enhancement

#1400 Updated release notes for 4.43
  RELEASE-NOTES.txt
Labels: Releases

#1404 Merge 4.42 final to develop
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/cy.lproj/Localizable.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/el.lproj/Localizable.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/fa.lproj/Localizable.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#1406 Merge 4.43 code freeze to develop
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/en.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases

#1417 Fixes a bug where the select all button state might be off
  RELEASE-NOTES.txt
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
Labels: bug, [feature] note list

#1401 Adopt ScreenObject package in screenshots tests: Proof of Concept
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SimplenoteScreenshots/PasscodeScreen.swift
  SimplenoteScreenshots/SimplenoteScreenshots.swift
Labels: Testing
