Repository Automattic/simplenote-ios, pull requests merged in 2021-05, with the labels that each got.

#1268 Fixed an issue where tags would not be deleted on trashed notes
  Simplenote/Classes/SPObjectManager+Simplenote.swift
  Simplenote/Classes/SPObjectManager.m
Labels: bug

#1262 Issue/1229 quick dissmiss notices
  Simplenote/NoticeController.swift
  Simplenote/NoticePresenter.swift
  Simplenote/NoticeView.swift
  SimplenoteTests/NoticeControllerTests.swift
Labels: In App Notifications, enhancement

#1271 Parameterising the test account for UI Tests
  Simplenote.xcodeproj/xcshareddata/xcschemes/SimplenoteUITests.xcscheme
  SimplenoteUITests/EmailLogin.swift
  SimplenoteUITests/Generic.swift
  SimplenoteUITests/SimplenoteUISmokeTestsSettings.swift
  SimplenoteUITests/SimplenoteUITestsLogin.swift
  SimplenoteUITests/SimplenoteUITestsNoteEditor.swift
  SimplenoteUITests/SimplenoteUITestsSearch.swift
  SimplenoteUITests/SimplenoteUITestsTrash.swift
  SimplenoteUITests/UIDs.swift
  fastlane/Fastfile
Labels: UIAutomation

#1272 Lowercase signup emails before sending to server
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SignupRemote.swift
  Simplenote/URLRequest+Simplenote.swift
  SimplenoteTests/Network/MockURLSession.swift
  SimplenoteTests/SignupRemoteTests.swift
Labels: bug

#1278 Change how notices auto size
  Simplenote/NoticeView.swift
  Simplenote/NoticeView.xib
Labels: In App Notifications, bug

#1281 Fix xcode compiler warnings
  Simplenote/Classes/KeyboardObservable.swift
  Simplenote/Classes/OptionsViewController.swift
  Simplenote/Classes/PinLock/PinLockController.swift
  Simplenote/Classes/PinLock/PinLockRemoveController.swift
  Simplenote/Classes/PinLock/PinLockSetupController.swift
  Simplenote/Classes/PinLock/PinLockVerifyController.swift
  Simplenote/Classes/SPEntryListViewController.m
  Simplenote/Classes/SPRatingsPromptView.swift
  Simplenote/Classes/TagView.swift
  Simplenote/NoticeView.swift
  Simplenote/SPCardPresentationController.swift
  Simplenote/SPNoteHistoryControllerDelegate.swift
  Simplenote/TagListViewCell.swift
  Simplenote/Tags/NoteEditorTagListViewController.swift
Labels: iOS 14

#1267 Issue/1043 add multi select
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController.h
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPNoteTableViewCell.swift
  Simplenote/Classes/SPNoteTableViewCell.xib
  Simplenote/Classes/UITableView+Simplenote.swift
  Simplenote/Images.xcassets/Icons/icon_task_checked.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_task_unchecked.imageset/Contents.json
  Simplenote/NoticeFactory.swift
  Simplenote/SeparatorsView.swift
Labels: enhancement, spring cleaning

#1275 New lane and functions managing test accounts for UI tests
  .circleci/config.yml
  fastlane/Fastfile
Labels: UIAutomation

#1280 Merge 4.36 beta 1 into develop
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/en.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/Fastfile
  fastlane/download_metadata.swift
Labels: Releases

#1279 Integrates Simperium Mk 1.8.0
  Podfile
  Podfile.lock
  Simplenote/Classes/Simperium+Simplenote.swift
  Simplenote/SPAppDelegate+Extensions.swift
Labels: enhancement

#1288 Changed in app notification dark mode background color
  Simplenote/Classes/UIColor+Studio.swift
Labels: In App Notifications, bug

#1284 Move secrets out of the repository – Part 1
  .circleci/config.yml
  .configure
  Gemfile.lock
  README.md
  Scripts/Build-Phases/copy-secret.sh
  Simplenote.xcodeproj/project.pbxproj
  fastlane/Fastfile
  fastlane/Matchfile
  fastlane/Pluginfile
Labels: tooling

#1294 Merge finalized release 4.36 into develop
  RELEASE-NOTES.txt
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/cy.lproj/Localizable.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/el.lproj/Localizable.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/fa.lproj/Localizable.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#1298 Fixed an issue where the new note button might not appear
  Simplenote/Classes/SPNoteListViewController.m
Labels: bug

#1296 Update get_prs_list helper lane
  fastlane/Fastfile
Labels: tooling

#1299 Alert users that biometric lock requires setting up a pin code
  Simplenote/Classes/SPSettingsViewController.m
Labels: bug
