Repository Automattic/simplenote-ios, pull requests merged in 2021-01, with the labels that each got.

#1046 Nü passcode screen: I
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/PinLock/PinLockViewController.swift
  Simplenote/Classes/PinLock/PinLockViewController.xib
  Simplenote/Classes/RoundedButton.swift
  Simplenote/Classes/RoundedCrossButton.swift
  Simplenote/Classes/UIColor+Studio.swift
  Simplenote/PinLockProgressView.swift
Labels: Part of a WIP Feature, [feature] security, spring cleaning

#1047 Nü passcode screen: II
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/PinLock/PinLockController.swift
  Simplenote/Classes/PinLock/PinLockSetupController.swift
  Simplenote/Classes/PinLock/PinLockViewController.swift
  Simplenote/Classes/PinLock/PinLockViewController.xib
  Simplenote/Classes/SPSettingsViewController+Extensions.swift
  Simplenote/Classes/SPSettingsViewController.m
  Simplenote/Classes/UIView+Animations.swift
Labels: Part of a WIP Feature, [feature] security, spring cleaning

#1068 Nü passcode screen: III
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/PinLock/PinLockBaseController.swift
  Simplenote/Classes/PinLock/PinLockRemoveController.swift
  Simplenote/Classes/PinLock/PinLockSetupController.swift
  Simplenote/Classes/PinLock/PinLockViewController.swift
  Simplenote/Classes/SPSettingsViewController+Extensions.swift
  Simplenote/Classes/SPSettingsViewController.h
  Simplenote/Classes/SPSettingsViewController.m
  Simplenote/Classes/UIView+Animations.swift
Labels: Part of a WIP Feature, [feature] security, spring cleaning

#1069 Nü passcode screen: IV
  External/DTPinLock/DTPinDigitView.h
  External/DTPinLock/DTPinDigitView.m
  External/DTPinLock/DTPinErrorView.h
  External/DTPinLock/DTPinErrorView.m
  External/DTPinLock/DTPinLockController.h
  External/DTPinLock/DTPinLockController.m
  External/DTPinLock/DTTwoPageViewController.h
  External/DTPinLock/DTTwoPageViewController.m
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/PinLock/PinLockBaseController.swift
  Simplenote/Classes/PinLock/PinLockController.swift
  Simplenote/Classes/PinLock/PinLockRemoveController.swift
  Simplenote/Classes/PinLock/PinLockSetupController.swift
  Simplenote/Classes/PinLock/PinLockVerifyController.swift
  Simplenote/Classes/PinLock/PinLockViewController.swift
  Simplenote/Classes/SPSettingsViewController+Extensions.swift
  Simplenote/Classes/SPSettingsViewController.h
  Simplenote/Classes/SPSettingsViewController.m
  Simplenote/Classes/UserDefaults+Simplenote.swift
  Simplenote/Options.swift
  Simplenote/SPAppDelegate+Extensions.swift
  Simplenote/SPAppDelegate.h
  Simplenote/SPAppDelegate.m
  Simplenote/SPConstants.m
  Simplenote/SPPinLockManager.swift
Labels: Part of a WIP Feature, [feature] security, spring cleaning

#1070 Nü passcode screen: V
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/ApplicationStateProvider.swift
  Simplenote/Classes/BiometricAuthentication.swift
  Simplenote/Classes/PinLock/PinLockController.swift
  Simplenote/Classes/PinLock/PinLockRemoveController.swift
  Simplenote/Classes/PinLock/PinLockSetupController.swift
  Simplenote/Classes/PinLock/PinLockVerifyController.swift
  Simplenote/Classes/SPSettingsViewController+Extensions.swift
  Simplenote/Classes/SPSettingsViewController.m
  Simplenote/Classes/UIApplication+Simplenote.swift
  Simplenote/SPAppDelegate+Extensions.swift
  Simplenote/SPAppDelegate.m
  Simplenote/SPPinLockManager.swift
  SimplenoteTests/MockApplication.swift
  SimplenoteTests/PinLock/Helpers/MockPinLockManager.swift
  SimplenoteTests/PinLock/Helpers/PinLockControllerConfiguration+Tests.swift
  SimplenoteTests/PinLock/Helpers/PinLockControllerConfigurationObserver.swift
  SimplenoteTests/PinLock/PinLockBaseControllerTests.swift
  SimplenoteTests/PinLock/PinLockRemoveControllerTests.swift
  SimplenoteTests/PinLock/PinLockSetupControllerTests.swift
  SimplenoteTests/PinLock/PinLockVerifyControllerTests.swift
Labels: Testing, [feature] security, spring cleaning

#1076 Nü passcode screen: VI
  Gemfile.lock
  Simplenote/Classes/PinLock/PinLockViewController.swift
  Simplenote/Classes/PinLock/PinLockViewController.xib
  Simplenote/PinLockProgressView.swift
  Simplenote/SPAppDelegate+Extensions.swift
Labels: Part of a WIP Feature, [feature] security, accessibility, spring cleaning

#1079 Fix predictive text entry for tag field
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/NSString+Simplenote.swift
  Simplenote/Classes/SPTagEntryField.m
  Simplenote/Classes/SPTagListViewCell.xib
  Simplenote/Classes/SPTagView+Extensions.swift
  Simplenote/Classes/SPTagView.h
  Simplenote/Classes/SPTagView.m
  Simplenote/Classes/SimplenoteConstants.swift
  Simplenote/Classes/TagListTextField.swift
  Simplenote/Classes/TagTextFieldInputValidator.swift
  Simplenote/Classes/UITextField+Tag.swift
  Simplenote/Classes/UITextInput+Simplenote.swift
  Simplenote/TagListViewController.swift
  SimplenoteTests/NSStringSimplenoteTests.swift
  SimplenoteTests/Tags/TagTextFieldInputValidatorTests.swift
Labels: [feature] tags

#1072 [Platform] Update L10n Linter strategy to allow retry
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: tooling

#1080 Merge release 4.30 beta 1 into develop
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/en.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases

#1087 Simperium: Swift Initialization
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/SPAppDelegate+Extensions.swift
  Simplenote/SPAppDelegate.h
  Simplenote/SPAppDelegate.m
  Simplenote/Simplenote-Bridging-Header.h
Labels: debt

#1081 Review your account
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/ActivityIndicatorButton.swift
  Simplenote/Classes/SimplenoteConstants.swift
  Simplenote/Classes/UIColor+Studio.swift
  Simplenote/Classes/UIImageName.swift
  Simplenote/Classes/UIView+Animations.swift
  Simplenote/Images.xcassets/Icons/icon_mail.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_mail.imageset/mail.pdf
  Simplenote/Images.xcassets/Icons/icon_warning.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_warning.imageset/warning.pdf
  Simplenote/UIView+Constraints.swift
  Simplenote/Verification/AccountVerificationController.swift
  Simplenote/Verification/AccountVerificationViewController.swift
  Simplenote/Verification/AccountVerificationViewController.xib
Labels: Part of a WIP Feature, [feature] security

#1085 Show "Trash" button when editing Tags from the Sidebar
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPTagListViewCell.h
  Simplenote/Classes/SPTagListViewCell.m
  Simplenote/Classes/SPTagListViewCell.xib
  Simplenote/Classes/TagListViewCell.xib
  Simplenote/Simplenote-Bridging-Header.h
  Simplenote/TagListViewCell.swift
  Simplenote/TagListViewController.swift
  Simplenote/Value1TableViewCell.swift
Labels: [feature] tags, spring cleaning

#1082 Apply minimum cell height in condensed list mode
  RELEASE-NOTES.txt
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPNoteTableViewCell.swift
  Simplenote/Classes/SPNoteTableViewCell.xib
Labels: [feature] note list, spring cleaning

#1094 Adds ability to swipe to dismiss SPTextView
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPNoteEditorViewController.m
Labels: [feature] editor, enhancement

#1093 Issue #1037 Empty Trash Button Remains Enabled
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController.h
  Simplenote/Classes/SPNoteListViewController.m
Labels: [feature] note list, bug

#1095 Show account verification screen
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPTracker.h
  Simplenote/Classes/Simperium+Simplenote.swift
  Simplenote/Classes/SimplenoteConstants.swift
  Simplenote/Classes/UIViewController+Simplenote.swift
  Simplenote/EmailVerification.swift
  Simplenote/SPAppDelegate+Extensions.swift
  Simplenote/SPAppDelegate.h
  Simplenote/SPAppDelegate.m
  Simplenote/SPTracker+Extensions.swift
  Simplenote/Verification/AccountVerificationController.swift
  Simplenote/Verification/AccountVerificationViewController.swift
Labels: [feature] security

#1101 Unit tests for account verification
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Verification/AccountVerificationController.swift
  Simplenote/Verification/AccountVerificationRemote.swift
  SimplenoteTests/Network/MockURLSession.swift
  SimplenoteTests/Network/MockURLSessionDataTask.swift
  SimplenoteTests/Verification/AccountVerificationControllerTests.swift
  SimplenoteTests/Verification/AccountVerificationRemoteTests.swift
  SimplenoteTests/Verification/Helpers/MockAccountVerificationRemote.swift
Labels: [feature] security

#1088 Prevent bypassing login screen
  Simplenote/Classes/ShortcutsHandler.swift
  Simplenote/SPAppDelegate.m
Labels: [feature] security

#1099 Updates Verification Parser
  Podfile
  Podfile.lock
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/EmailVerification.swift
  Simplenote/Verification/AccountVerificationController.swift
  SimplenoteTests/EmailVerificationTests.swift
  SimplenoteTests/Verification/AccountVerificationControllerTests.swift
Labels: [feature] security

#1089 Email verification
  .configure
  .configure-files/SPCredentials.swift.enc
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/ActivityIndicatorButton.swift
  Simplenote/Classes/SPTracker.h
  Simplenote/Classes/Simperium+Simplenote.swift
  Simplenote/Classes/SimplenoteConstants.swift
  Simplenote/Classes/UIColor+Studio.swift
  Simplenote/Classes/UIImageName.swift
  Simplenote/Classes/UIView+Animations.swift
  Simplenote/Classes/UIViewController+Simplenote.swift
  Simplenote/EmailVerification.swift
  Simplenote/Images.xcassets/Icons/icon_mail.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_mail.imageset/mail.pdf
  Simplenote/Images.xcassets/Icons/icon_warning.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_warning.imageset/warning.pdf
  Simplenote/SPAppDelegate+Extensions.swift
  Simplenote/SPAppDelegate.h
  Simplenote/SPAppDelegate.m
  Simplenote/SPCredentials-demo.swift
  Simplenote/SPTracker+Extensions.swift
  Simplenote/Simplenote-Bridging-Header.h
  Simplenote/UIView+Constraints.swift
  Simplenote/Verification/AccountVerificationController.swift
  Simplenote/Verification/AccountVerificationRemote.swift
  Simplenote/Verification/AccountVerificationViewController.swift
  Simplenote/Verification/AccountVerificationViewController.xib
  SimplenoteTests/EmailVerificationTests.swift
  SimplenoteTests/Network/MockURLSession.swift
  SimplenoteTests/Network/MockURLSessionDataTask.swift
  SimplenoteTests/Verification/AccountVerificationControllerTests.swift
  SimplenoteTests/Verification/AccountVerificationRemoteTests.swift
  SimplenoteTests/Verification/Helpers/MockAccountVerificationRemote.swift
Labels: [feature] security

#1096 Extended unit tests for string hashing
  SimplenoteTests/NSStringSimplenoteTests.swift
Labels: Testing

#1110 Bugfix: Configure popover when presenting tag delete sheet on iPad
  Simplenote/TagListViewController.swift
Labels: [feature] tags, bug

#1108 Merge finalize release 4.30 into develop
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/cy.lproj/Localizable.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/el.lproj/Localizable.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/fa.lproj/Localizable.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/keywords.txt
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#1112 Merge release 4.31 beta 1 into develop
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/en.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases
