Repository Automattic/simplenote-ios, pull requests merged in 2021-09, with the labels that each got.

#1419 Adding UI tests for History feature
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcodeproj/xcshareddata/xcschemes/SimplenoteUITests_Subset.xcscheme
  SimplenoteUITests/AssertGeneric.swift
  SimplenoteUITests/Generic.swift
  SimplenoteUITests/History.swift
  SimplenoteUITests/NoteEditor.swift
  SimplenoteUITests/SimplenoteUITestsHistory.swift
  SimplenoteUITests/UIDs.swift
Labels: UIAutomation

#1422 Updated check for verification required body response
  Simplenote/Classes/SPAuthError.swift
Labels: bug

#1423 Updated copy for account deletion alert message to include user email
  RELEASE-NOTES.txt
  Simplenote/Classes/SPSettingsViewController+Extensions.swift
Labels: enhancement

#1420 Added extra info to readme building steps
  README.md
Labels: documentation

#1429 Merge 4.44 code freeze to develop
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/en.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases

#1431 Use ScreenObject version 0.1.0
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Testing

#1408 Update Intents "Distribution AppStore" configuration to match other extensions
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Supporting Files/Simplenote-Info.plist
  Simplenote/Supporting Files/Simplenote-Internal.entitlements
  Simplenote/Supporting Files/Simplenote-Prefix.pch
  Simplenote/Supporting Files/Simplenote.entitlements
  Simplenote/Supporting Files/main.m
  Simplenote/en.lproj/InfoPlist.strings
  SimplenoteIntents/Supporting Files/Info.plist
  SimplenoteIntents/Supporting Files/SimplenoteIntents-Debug.entitlements
  SimplenoteIntents/Supporting Files/SimplenoteIntents-DistributionAlpha.entitlements
  SimplenoteIntents/Supporting Files/SimplenoteIntents-DistributionInternal.entitlements
  SimplenoteIntents/Supporting Files/SimplenoteIntents-Release.entitlements
  SimplenoteShare/Supporting Files/Info.plist
  SimplenoteShare/Supporting Files/SimplenoteShare-AppStore.entitlements
  SimplenoteShare/Supporting Files/SimplenoteShare-Development.entitlements
  SimplenoteShare/Supporting Files/SimplenoteShare-DistributionAlpha.entitlements
  SimplenoteShare/Supporting Files/SimplenoteShare-Internal.entitlements
  SimplenoteWidgets/Supporting Files/SimplenoteWidgetsExtension-Debug.entitlements
  SimplenoteWidgets/Supporting Files/SimplenoteWidgetsExtension-DistributionAlpha.entitlements
  SimplenoteWidgets/Supporting Files/SimplenoteWidgetsExtension-DistributionInternal.entitlements
  SimplenoteWidgets/Supporting Files/SimplenoteWidgetsExtension-Release.entitlements
Labels: tooling

#1434 Merge 4.44 final to develop
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/cy.lproj/Localizable.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/el.lproj/Localizable.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/fa.lproj/Localizable.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/keywords.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/name.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#1433 Merge 4.44 final to trunk
  README.md
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcodeproj/xcshareddata/xcschemes/SimplenoteUITests_Subset.xcscheme
  Simplenote.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/cy.lproj/Localizable.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/el.lproj/Localizable.strings
  Simplenote/en.lproj/Localizable.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/fa.lproj/Localizable.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  SimplenoteScreenshots/PasscodeScreen.swift
  SimplenoteScreenshots/SimplenoteScreenshots.swift
  SimplenoteUITests/AssertGeneric.swift
  SimplenoteUITests/Generic.swift
  SimplenoteUITests/History.swift
  SimplenoteUITests/NoteEditor.swift
  SimplenoteUITests/SimplenoteUITestsHistory.swift
  SimplenoteUITests/UIDs.swift
  TESTING-CHECKLIST.md
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/keywords.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/name.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#1439 Updates UI tests user(s) passwords to more secure ones
  SimplenoteUITests/UIDs.swift
Labels: UIAutomation

#1430 Use multiple elements to verify `PasscodeScreen` is loaded on screen
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SimplenoteScreenshots/PasscodeScreen.swift
Labels: Testing

#1443 Update some localized string definitions to correct the English rendering
  Simplenote/Classes/NotesListFilter.swift
  Simplenote/Classes/SPAddCollaboratorsViewController.m
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPTagEntryField.m
  Simplenote/Classes/TagViewCell.swift
  Simplenote/TagListViewController.swift
  Simplenote/en.lproj/Localizable.strings
Labels: Releases

#1441 Updated text for Compromised password alert
  Simplenote/Classes/SPAuthError.swift
  Simplenote/Classes/SPAuthViewController.swift
Labels: enhancement, [feature] security

#1449 Merge 4.45 beta 2 to develop
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/cy.lproj/Localizable.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/el.lproj/Localizable.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/fa.lproj/Localizable.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#1448 Use ellipsis (`…`) instead of three dots in "Tag…" localized string
  Simplenote/Classes/SPTagEntryField.m
  SimplenoteUITests/UIDs.swift
Labels: tooling

#1447 Add UI tests foundation framework
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcodeproj/xcshareddata/xcschemes/UITestsFoundation.xcscheme
  SimplenoteScreenshots/SimplenoteScreenshots.swift
  SimplenoteUITests/SimplenoteUITestsLogin.swift
  UITestsFoundation/PasscodeScreen.swift
  UITestsFoundation/UITestsFoundation.h
  UITestsFoundation/XCUIApplication+Assertions.swift
Labels: UIAutomation

#1452 Add `previous-application-identifier` to Intents' Release entitlements
  SimplenoteIntents/Supporting Files/SimplenoteIntents-Release.entitlements
Labels: tooling

#1453 Fixed a crash for ios 12 and 13 caused by widgets when app enters bg
  Simplenote/SPAppDelegate+Extensions.swift
Labels: crash, [feature] Widgets

#1432 readme updates
  README.md
Labels: documentation

#1450 Dropping iOS 12 Support
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  Scripts/Build-Phases/copy-secret.sh
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/ActivityIndicatorButton.swift
  Simplenote/Classes/PinLock/PinLockViewController.swift
  Simplenote/Classes/SPAuthViewController.swift
  Simplenote/Classes/SPBlurEffectView.swift
  Simplenote/Classes/SPMarkdownParser.m
  Simplenote/Classes/SPMarkdownPreviewViewController.m
  Simplenote/Classes/SPModalActivityIndicator.h
  Simplenote/Classes/SPModalActivityIndicator.m
  Simplenote/Classes/SPNavigationController.m
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteHistoryViewController.swift
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPOnboardingViewController.swift
  Simplenote/Classes/SPSettingsViewController.m
  Simplenote/Classes/SPSidebarContainerViewController.m
  Simplenote/Classes/SPThemeViewController.swift
  Simplenote/Classes/SPUserInterface.swift
  Simplenote/Classes/SimplenoteConstants.swift
  Simplenote/Classes/Theme.swift
  Simplenote/Classes/UIApplication+Simplenote.swift
  Simplenote/Classes/UIBlurEffect+Simplenote.swift
  Simplenote/Classes/UIColor+Helpers.swift
  Simplenote/Classes/UIColor+Studio.swift
  Simplenote/Classes/UIDevice+Simplenote.swift
  Simplenote/Classes/UIImage+Simplenote.swift
  Simplenote/Classes/UIKeyCommand+Simplenote.swift
  Simplenote/Classes/UIMenuController+Simplenote.swift
  Simplenote/Classes/UIView+Animations.swift
  Simplenote/Color+Simplenote.swift
  Simplenote/Controllers/WidgetController.swift
  Simplenote/SPAppDelegate.m
  Simplenote/SpinnerViewController.swift
  Simplenote/Supporting Files/Simplenote-Info.plist
  Simplenote/TagListViewController.swift
  Simplenote/Verification/AccountVerificationViewController.swift
  SimplenoteIntents/Supporting Files/SimplenoteIntents-Release.entitlements
  SimplenoteShare/Themes/SPUserInterface.swift
  SimplenoteTests/OptionsTests.swift
  SimplenoteWidgets/Supporting Files/ListWidgetIntent.intentdefinition
  SimplenoteWidgets/Supporting Files/NoteWidgetIntent.intentdefinition
Labels: enhancement
