Repository Automattic/simplenote-ios, pull requests merged in 2021-10, with the labels that each got.

#1454 Fixed an issue where loading notes from widgets use different animations
  Simplenote/SPAppDelegate+Extensions.swift
Labels: bug, [feature] Widgets

#1451 Crash when publishing deleted note
  RELEASE-NOTES.txt
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/SPAppDelegate.m
Labels: bug, crash, [feature] publish

#1455 Added 429 too many login attempts error
  Simplenote/Classes/SPAuthError.swift
Labels: enhancement, [feature] login

#1456 Merge 4.45 final to develop
  Simplenote/SPAppDelegate+Extensions.swift
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#1458 Merge 4.46 code freeze to develop
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/en.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases

#1460 Revert translateable app name
  Simplenote/Resources/AppStoreStrings.pot
  fastlane/Fastfile
  fastlane/download_metadata.swift
  fastlane/metadata/id/name.txt
Labels: tooling
