Repository Automattic/simplenote-ios, pull requests merged in 2021-07, with the labels that each got.

#1351 Merge 4.39 final to develop
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/cy.lproj/Localizable.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/el.lproj/Localizable.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/fa.lproj/Localizable.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#1347 Previously viewed tag loaded on app launch
  Simplenote/SPAppDelegate.m
  Simplenote/SPConstants.m
Labels: bug

#1345 Updated new note icon to new design
  Simplenote/Images.xcassets/Icons/icon_new_note.imageset/new-note.pdf
Labels: enhancement

#1348 Search Highlighting out of place after rotation
  RELEASE-NOTES.txt
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPNoteEditorViewController.h
  Simplenote/Classes/SPNoteEditorViewController.m
Labels: bug

#1355 Merge 4.40 code freeze to develop
  Gemfile.lock
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases

#1318 Check translation progress during final release
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: tooling

#1349 Migrate CoreData to shared app group directory
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/Bundle+Simplenote.swift
  Simplenote/Classes/FileManager+Simplenote.swift
  Simplenote/Classes/SPObjectManager.m
  Simplenote/CoreDataManager.swift
  Simplenote/SPAppDelegate+Extensions.swift
  Simplenote/SPAppDelegate.h
  Simplenote/SPAppDelegate.m
  Simplenote/SharedStorageMigrator.swift
  Simplenote/StorageSettings.swift
Labels: enhancement

#1358 Update keywords for 4.40
  Simplenote/Resources/AppStoreStrings.pot
  fastlane/appstoreres/metadata/source/keywords.txt
Labels: tooling

#1361 Track XCUITestHelpers using version 0.1.0
  Simplenote.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: tooling

#1360 Merge updated keywords to develop
  Simplenote/Resources/AppStoreStrings.pot
  fastlane/appstoreres/metadata/source/keywords.txt
Labels: Releases

#1357 Fixing failing Search tests and `addBulletedLists` test (again)
  SimplenoteUITests/NoteEditor.swift
  SimplenoteUITests/SimplenoteUISmokeTestsSettings.swift
  SimplenoteUITests/SimplenoteUITestsNoteEditor.swift
Labels: UIAutomation

#1363 Merge 4.40 final to develop
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/pt-BR.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/keywords.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/keywords.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/keywords.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/keywords.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/keywords.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/keywords.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/keywords.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/keywords.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/keywords.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/keywords.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/keywords.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/keywords.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/keywords.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/keywords.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/keywords.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/keywords.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#1364 Merge 4.40 final to trunk
  Gemfile.lock
  RELEASE-NOTES.txt
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPNoteEditorViewController.h
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Images.xcassets/Icons/icon_new_note.imageset/new-note.pdf
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/SPAppDelegate.m
  Simplenote/SPConstants.m
  Simplenote/pt-BR.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/appstoreres/metadata/source/keywords.txt
  fastlane/download_metadata.swift
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/keywords.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/keywords.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/keywords.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/keywords.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/keywords.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/keywords.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/keywords.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/keywords.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/keywords.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/keywords.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/keywords.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/keywords.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/keywords.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/keywords.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/keywords.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/keywords.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#1344 Update Fastlane code signing automation to include Intents extension
  Simplenote.xcodeproj/project.pbxproj
  fastlane/Fastfile
Labels: tooling

#1336 Add SimplenoteIntents extension to app
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Simplenote-Info.plist
  SimplenoteIntents/Info.plist
  SimplenoteIntents/IntentHandler.swift
  SimplenoteWidgets/Providers/NotePreviewWidgetProvider.swift
  SimplenoteWidgets/SimplenoteWidgets.swift
  SimplenoteWidgets/Supporting Files/NoteWidgetIntent.intentdefinition
  SimplenoteWidgets/Views/NotePreviewWidgetView.swift
  SimplenoteWidgets/Widgets/NotePreviewWidget.swift
  fastlane/Fastfile
Labels: [feature] Widgets

#1366 Updated release notes
  RELEASE-NOTES.txt
Labels: documentation

#1367 Merge 4.41 code freeze to develop
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/appstoreres/metadata/source/keywords.txt
  fastlane/download_metadata.swift
Labels: Releases

#1369 Sanitize app store keywords after updating metadata
  fastlane/Fastfile
Labels: tooling

#1368 Drops experimental scheme
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcodeproj/xcshareddata/xcschemes/Simplenote Experimental.xcscheme
  Simplenote/Classes/SPOnboardingViewController.swift
  Simplenote/Classes/SimplenoteConstants.swift
  Simplenote/SPAppDelegate+Extensions.swift
  Simplenote/SPCredentials-demo.swift
  config/Simplenote.internal.xcconfig
Labels: enhancement

#1370 Update app store subtitle
  Simplenote/Resources/AppStoreStrings.pot
  fastlane/appstoreres/metadata/source/subtitle.txt
Labels: Releases, tooling

#1371 Merge sanitize app store keywords & subtitle change to develop
  Simplenote/Resources/AppStoreStrings.pot
  fastlane/Fastfile
  fastlane/appstoreres/metadata/source/subtitle.txt
Labels: Releases

#1365 Connect shared db to widgets
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/BuildConfiguration.swift
  SimplenoteIntents/IntentHandler.swift
  SimplenoteIntents/Simplenote-Intents-Bridging-Header.h
  SimplenoteWidgets/Models/Note+Widget.swift
  SimplenoteWidgets/Models/SPManagedObject+Widget.swift
  SimplenoteWidgets/Models/Tag+Widget.swift
  SimplenoteWidgets/Simplenote-Widgets-Bridging-Header.h
Labels: [feature] Widgets, enhancement
