Repository Automattic/simplenote-ios, pull requests merged in 2021-06, with the labels that each got.

#1302 Merge 4.37 code freeze to develop
  .configure
  .configure-files/project.env.enc
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/en.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/Fastfile
  fastlane/download_metadata.swift
Labels: Releases

#1309 Updated release notes to include multi select
  RELEASE-NOTES.txt
Labels: spring cleaning

#1292 Run `Trash` UI tests on every commit
  .circleci/config.yml
  fastlane/Fastfile
Labels: UIAutomation

#1301 New scheme with a subset of UI tests + test accounts sanitiser
  .circleci/config.yml
  Simplenote.xcodeproj/xcshareddata/xcschemes/SimplenoteUITests_Subset.xcscheme
  SimplenoteUITests/NoteEditor.swift
  SimplenoteUITests/NoteList.swift
  SimplenoteUITests/Preview.swift
  fastlane/Fastfile
Labels: UIAutomation

#1314 Merge new release notes from 4.37 to develop
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
Labels: Releases

#1319 Merge 4.37 to develop
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/cy.lproj/Localizable.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/el.lproj/Localizable.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/fa.lproj/Localizable.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/keywords.txt
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#1321 [Tooling] Fix GitHub releases for intermediate betas
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: tooling

#1322 Apply suggestions from #1321
  fastlane/Fastfile
Labels: Releases

#1323 Adds release notes for 4.38
  RELEASE-NOTES.txt
Labels: Releases

#1324 Adds missing PROJECT_ROOT_FOLDER to fastlane
  fastlane/Fastfile
Labels: tooling

#1315 Replace UI tests helper local framework with remote Swift package
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SimplenoteScreenshots/SimplenoteScreenshots.swift
  SimplenoteUITests/Preview.swift
  UITestHelpers/Info.plist
  UITestHelpers/UITestHelpers.h
  UITestHelpers/XCUIApplication+Device.swift
  UITestHelpers/XCUIElement+TextManagement.swift
  UITestHelpers/XCUIElementQuery+Sequence.swift
  fastlane/Fastfile
Labels: UIAutomation

#1325 Merge 4.38.0.0 to develop
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/en.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases

#1317 Update logic to sanitize keywords via Fastlane
  .circleci/config.yml
  Gemfile.lock
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcodeproj/xcshareddata/xcschemes/SimplenoteUITests_Subset.xcscheme
  Simplenote.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Simplenote/Classes/SPSettingsViewController.m
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/en.lproj/Localizable.strings
  SimplenoteScreenshots/SimplenoteScreenshots.swift
  SimplenoteScreenshots/SnapshotHelper.swift
  SimplenoteUITests/NoteEditor.swift
  SimplenoteUITests/NoteList.swift
  SimplenoteUITests/Preview.swift
  UITestHelpers/Info.plist
  UITestHelpers/UITestHelpers.h
  UITestHelpers/XCUIApplication+Device.swift
  UITestHelpers/XCUIElement+TextManagement.swift
  UITestHelpers/XCUIElementQuery+Sequence.swift
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/Fastfile
  fastlane/Pluginfile
  fastlane/download_metadata.swift
Labels: tooling

#1331 Update logic to sanitize keywords via Fastlane – Take 3
  fastlane/Fastfile
Labels: tooling

#1286 Add tracks to notices
  Simplenote/Classes/OptionsViewController.swift
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Controllers/PublishNoticePresenter.swift
  Simplenote/SPTracker+Extensions.swift
Labels: analytics, enhancement

#1333 Upgrade CircleCI to use Xcode 12.5
  .circleci/config.yml
  .xcversion
  SimplenoteUITests/UIDs.swift
  fastlane/Fastfile
Labels: tooling

#1334 Update AppStoreStrings to mention English comma keywords requirement
  Simplenote/Resources/AppStoreStrings.pot
Labels: tooling

#1293 New note widget
  Gemfile.lock
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPObjectManager+Simplenote.swift
  Simplenote/Classes/UIColor+Helpers.swift
  Simplenote/SPAppDelegate.m
  Simplenote/SimplenoteWidgetsExtension.entitlements
  Simplenote/SimplenoteWidgetsExtensionDebug.entitlements
  Simplenote/SimplenoteWidgetsExtensionDistributionAlpha.entitlements
  Simplenote/SimplenoteWidgetsExtensionDistributionInternal.entitlements
  SimplenoteTests/UIColorSimplenoteTests.swift
  SimplenoteWidgets/Assets.xcassets/AccentColor.colorset/Contents.json
  SimplenoteWidgets/Assets.xcassets/AppIcon.appiconset/Contents.json
  SimplenoteWidgets/Assets.xcassets/Contents.json
  SimplenoteWidgets/Assets.xcassets/WidgetBackground.colorset/Contents.json
  SimplenoteWidgets/Info.plist
  SimplenoteWidgets/Providers/NewNoteWidgetProvider.swift
  SimplenoteWidgets/SimplenoteWidgets.swift
  SimplenoteWidgets/Views/NewNoteWidgetView.swift
  SimplenoteWidgets/Widgets/NewNoteWidget.swift
  fastlane/Fastfile
Labels: [feature] Widgets, enhancement

#1335 Reduce flakiness of `testBulletedLists()` and `testLongTappingOnLinkOpensLinkInNewWindow()`
  Simplenote.xcodeproj/xcshareddata/xcschemes/SimplenoteUITests_Subset.xcscheme
  SimplenoteUITests/AssertGeneric.swift
  SimplenoteUITests/Generic.swift
  SimplenoteUITests/NoteEditor.swift
  SimplenoteUITests/NoteList.swift
  SimplenoteUITests/Preview.swift
  SimplenoteUITests/UIDs.swift
Labels: UIAutomation

#1337 Fixed an issue where cell separators appeared on ipad
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
Labels: bug

#1328 Edit mode/Action Bar updates
  Gemfile.lock
  RELEASE-NOTES.txt
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPSidebarViewController+Extensions.swift
  Simplenote/Classes/SearchDisplayController.swift
  Simplenote/Classes/UIColor+Studio.swift
  Simplenote/Classes/UIImageName.swift
  Simplenote/Classes/UISearchBar+Simplenote.swift
  Simplenote/Images.xcassets/Icons/icon_success.imageset/Contents.json
  Simplenote/Images.xcassets/Icons/icon_success.imageset/success.pdf
  fastlane/Pluginfile
Labels: spring cleaning

#1338 Merge 4.38 final to develop
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/cy.lproj/Localizable.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/el.lproj/Localizable.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/fa.lproj/Localizable.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#1339 Merge 4.38 final to trunk
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/cy.lproj/Localizable.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/el.lproj/Localizable.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/fa.lproj/Localizable.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#1340 Merge 4.39 code freeze to develop
  Gemfile.lock
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/en.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases
