Repository Automattic/simplenote-ios, pull requests merged in 2021-04, with the labels that each got.

#1226 Merge release 4.34 into develop
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#1222 In app notifications - Notices!!
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/OptionsViewController.swift
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Controllers/PublishController.swift
  Simplenote/Controllers/PublishNoticePresenter.swift
  Simplenote/Note+Publish.swift
  Simplenote/NoticeFactory.swift
  Simplenote/SPAppDelegate+Extensions.swift
  Simplenote/SPAppDelegate.h
  Simplenote/SPAppDelegate.m
  Simplenote/TimerFactory.swift
  SimplenoteTests/MockTimerFactory.swift
  SimplenoteTests/MockupStorage+Sample.swift
  SimplenoteTests/NoticeControllerTests.swift
  SimplenoteTests/PublishControllerTests.swift
Labels: In App Notifications, enhancement

#1232 Deleted Tag crash
  Simplenote/TagListViewController.swift
Labels: bug, crash

#1233 Fixed tag bar getting stuck on swipe to markdown preview
  Simplenote/Classes/SPNoteEditorViewController.m
Labels: bug

#1214 Use API calls to trigger release jobs
  .circleci/config.yml
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
  fastlane/env/user.env-example
Labels: tooling

#1225 Adding `UI Tests` job to CircleCI
  .circleci/config.yml
  Simplenote.xcodeproj/xcshareddata/xcschemes/SimplenoteUITests.xcscheme
  fastlane/Fastfile
Labels: UIAutomation

#1239 Refactor search flow UI tests to use value type for fake data
  Simplenote.xcodeproj/project.pbxproj
  SimplenoteUITests/NoteData.swift
  SimplenoteUITests/NoteList.swift
  SimplenoteUITests/SimplenoteUITestsSearch.swift
Labels: Testing

#1237 Updated copy for verify email text
  Simplenote/Classes/SignupVerificationViewController.swift
Labels: enhancement

#1238 Remove search sort bar bar
  RELEASE-NOTES.txt
  Simplenote/Classes/NotesListController.swift
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController.h
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPNotifications.h
  Simplenote/Classes/SPNotifications.m
  Simplenote/Classes/SPTracker.h
  Simplenote/Classes/SPTracker.m
  Simplenote/Classes/UserDefaults+Simplenote.swift
  Simplenote/Options.swift
  SimplenoteTests/NotesListControllerTests.swift
  SimplenoteTests/OptionsTests.swift
Labels: enhancement, spring cleaning

#1235 Update encrypted credentials for screenshots account
  .configure
  .configure-files/ScreenshotsCredentials.swift.enc
Labels: tooling

#1240 Automated first test from `Settings`
  Simplenote.xcodeproj/project.pbxproj
  SimplenoteUITests/Generic.swift
  SimplenoteUITests/NoteData.swift
  SimplenoteUITests/NoteList.swift
  SimplenoteUITests/Settings.swift
  SimplenoteUITests/SimplenoteUISmokeTestsSettings.swift
  TESTING-CHECKLIST.md
Labels: UIAutomation

#1228 Feature/in app notifications
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/OptionsViewController.swift
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/UIColor+Studio.swift
  Simplenote/Controllers/PublishController.swift
  Simplenote/Controllers/PublishNoticePresenter.swift
  Simplenote/Note+Publish.swift
  Simplenote/Notice.swift
  Simplenote/NoticeAction.swift
  Simplenote/NoticeController.swift
  Simplenote/NoticeFactory.swift
  Simplenote/NoticePresenter.swift
  Simplenote/NoticeView.swift
  Simplenote/NoticeView.xib
  Simplenote/SPAppDelegate+Extensions.swift
  Simplenote/SPAppDelegate.h
  Simplenote/SPAppDelegate.m
  Simplenote/TimerFactory.swift
  Simplenote/UIView+Constraints.swift
  SimplenoteTests/MockTimerFactory.swift
  SimplenoteTests/MockupStorage+Sample.swift
  SimplenoteTests/NoticeControllerTests.swift
  SimplenoteTests/PublishControllerTests.swift
Labels: In App Notifications

#1242 UI tests helper framework proof of concept
  Simplenote.xcodeproj/project.pbxproj
  SimplenoteScreenshots/SimplenoteScreenshots.swift
  SimplenoteUITests/Extensions.swift
  SimplenoteUITests/Preview.swift
  UITestHelpers/Info.plist
  UITestHelpers/UITestHelpers.h
  UITestHelpers/XCUIApplication+Device.swift
  UITestHelpers/XCUIElementQuery+Sequence.swift
Labels: UIAutomation

#1243 Test notes for search are now created via paste
  Simplenote.xcodeproj/project.pbxproj
  SimplenoteScreenshots/SimplenoteScreenshots.swift
  SimplenoteUITests/Extensions.swift
  SimplenoteUITests/NoteEditor.swift
  SimplenoteUITests/NoteList.swift
  SimplenoteUITests/SimplenoteUITestsSearch.swift
  UITestHelpers/XCUIElement+TextManagement.swift
Labels: UIAutomation

#1247 Use private(set) for var tags property in NoteData
  SimplenoteUITests/NoteData.swift
Labels: Testing

#1251 Merge 4.35 beta 1 into develop
  Gemfile.lock
  RELEASE-NOTES.txt
  Scripts/extract_release_notes.rb
  Simplenote/Resources/release_notes.txt
  Simplenote/en.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/Fastfile
  fastlane/Pluginfile
  fastlane/download_metadata.swift
Labels: Releases

#1249 Test Checklist: Adding more consistency
  TESTING-CHECKLIST.md
Labels: [feature] checklist

#1253 Added a `setup` test, asking to sign up using mixed-capitalization
  TESTING-CHECKLIST.md
Labels: [feature] checklist

#1258 Issue/1248 contexual menu sizing issue
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
Labels: bug

#1260 Remove all caps on collaboration alert
  Simplenote/Tags/NoteEditorTagListViewController.swift
Labels: enhancement

#1246 Feature: New Note Bar
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteListViewController.m
Labels: enhancement, spring cleaning

#1264 Adding support of new note bar
  SimplenoteUITests/Generic.swift
  SimplenoteUITests/NoteList.swift
  SimplenoteUITests/Trash.swift
  SimplenoteUITests/UIDs.swift
Labels: UIAutomation

#1266 Add missing 4.35 "what's new" values to AppStoreStrings.pot
  Gemfile.lock
  Simplenote/Resources/AppStoreStrings.pot
  fastlane/Pluginfile
Labels: Releases, tooling
