Repository Automattic/simplenote-ios, pull requests merged in 2021-02, with the labels that each got.

#1119 AccountVerificationController: Case insensitive comparison
  Simplenote/Verification/AccountVerificationController.swift
Labels: [feature] security, [priority] high

#1116 Make Note non-optional in SPNoteEditorViewController
  Simplenote/Classes/EditorFactory.swift
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPNoteEditorViewController.h
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController.h
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/SPAppDelegate+Extensions.swift
  Simplenote/SPAppDelegate.m
  Simplenote/SPConstants.h
  Simplenote/SPConstants.m
Labels: debt, task

#1106 Add dismiss handle to Information Sheet
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Information/NoteInformationViewController.swift
  Simplenote/Information/NoteInformationViewController.xib
  Simplenote/SPDragBar.swift
Labels: enhancement, spring cleaning

#1105 Information Sheet Style Updates
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Simplenote/Information/NoteInformationController.swift
  Simplenote/Information/NoteInformationViewController.swift
  Simplenote/Information/NoteInformationViewController.xib
  Simplenote/SPDragBar.swift
  Simplenote/SubtitleTableViewCell.swift
  Simplenote/TableHeaderViewCell.swift
Labels: enhancement, spring cleaning

#1122 Merge version 4.31 beta 2 into develop
  Simplenote/Verification/AccountVerificationController.swift
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/cy.lproj/Localizable.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/el.lproj/Localizable.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/fa.lproj/Localizable.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/keywords.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
Labels: Releases

#1111 Keyboard support: MK1
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPSidebarViewController+Extensions.swift
  Simplenote/Classes/UIKeyCommand+Simplenote.swift
  Simplenote/Classes/UIResponder+Simplenote.swift
  Simplenote/Classes/UITableView+Simplenote.swift
  Simplenote/SPAppDelegate+Extensions.swift
  Simplenote/SPAppDelegate.m
  Simplenote/TagListViewController.swift
Labels: accessibility

#1113 Keyboard Support: MK2
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Simplenote/Classes/EditorFactory.swift
  Simplenote/Classes/SPMarkdownPreviewViewController+Extensions.swift
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPNoteEditorViewController.h
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController.h
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPSidebarViewController+Extensions.swift
  Simplenote/Classes/UIApplication+Simplenote.swift
  Simplenote/Classes/UIKeyCommand+Simplenote.swift
  Simplenote/Classes/UIScrollView+Simplenote.swift
  Simplenote/Classes/UITableView+Simplenote.swift
  Simplenote/Classes/UIView+Animations.swift
  Simplenote/NoteScrollPositionCache.swift
  Simplenote/SPAppDelegate+Extensions.swift
  Simplenote/SPTracker+Extensions.swift
  Simplenote/Simplenote-Bridging-Header.h
  Simplenote/TagListViewController.swift
Labels: accessibility

#1127 Add Fastlane API Key
  .configure
  .configure-files/app_store_connect_fastlane_api_key.json.enc
Labels: enhancement, tooling

#1129 Merge release 4.31 into develop
  .configure
  .configure-files/app_store_connect_fastlane_api_key.json.enc
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/keywords.txt
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#1134 Merge release 4.32 beta 1 into develop
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/en.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases

#1135 Exclude share to books from UIActivityViewController
  Simplenote/UIActivityViewController+Simplenote.swift
Labels: bug

#1133 Moving tags editors from text view to view controller
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPEditorTextView.h
  Simplenote/Classes/SPEditorTextView.m
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPNoteEditorViewController.h
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPTagEntryField.m
  Simplenote/Classes/SPTagView.h
  Simplenote/Classes/SPTagView.m
  Simplenote/SPEditorTextView+Simplenote.swift
  Simplenote/Tags/NoteEditorTagListViewController.swift
  Simplenote/Tags/NoteEditorTagListViewController.xib
Labels: debt, task

#1142 Updating new-note and collaborate icons.
  RELEASE-NOTES.txt
  Simplenote/Images.xcassets/Icons/icon_collaborate.imageset/icon_collaborate.pdf
  Simplenote/Images.xcassets/Icons/icon_new_note.imageset/icon_new_note.pdf
Labels: enhancement

#1136 Refactor SimplenoteActivityItemSource
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/FileManager+Simplenote.swift
  Simplenote/Classes/SimplenoteActivityItemSource.swift
  Simplenote/UIActivityViewController+Simplenote.swift
Labels: enhancement

#1141 Making Lint Changes as Suggested by SwiftLint
  Simplenote/BuildConfiguration.swift
  Simplenote/Classes/CSSearchable+Helpers.swift
  Simplenote/Classes/NSString+Count.swift
  Simplenote/Classes/Note+Properties.swift
  Simplenote/Classes/PinLock/PinLockSetupController.swift
  Simplenote/Classes/PinLock/PinLockVerifyController.swift
  Simplenote/Classes/SPAboutViewController.swift
  Simplenote/Classes/SPAuthError.swift
  Simplenote/Classes/SPBlurEffectView.swift
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteTableViewCell.swift
  Simplenote/Classes/SPRatingsPromptView.swift
  Simplenote/Classes/SPSimpleTextPrintFormatter.swift
  Simplenote/Classes/SPTextInputView.swift
  Simplenote/Classes/UIColor+Studio.swift
  Simplenote/Classes/UIKeyCommand+Simplenote.swift
  Simplenote/Classes/UITextView+Simplenote.swift
  Simplenote/Information/NoteInformationController.swift
  Simplenote/Information/NoteInformationViewController.swift
  Simplenote/KeychainPasswordItem.swift
  Simplenote/NSTextStorage+Simplenote.swift
  Simplenote/Options.swift
  Simplenote/SPDragBar.swift
  Simplenote/SPPinLockManager.swift
  Simplenote/SPPrivacyViewController.swift
  Simplenote/TagListViewController.swift
  Simplenote/UIActivityViewController+Simplenote.swift
  Simplenote/UIView+Constraints.swift
  Simplenote/Verification/AccountVerificationViewController.swift
  SimplenoteShare/Presentation/ExtensionPresentationController.swift
  SimplenoteShare/Simperium/Note.swift
  SimplenoteShare/ViewControllers/SharePresentationController.swift
  SimplenoteTests/EmailVerificationTests.swift
  SimplenoteTests/NSMutableAttributedStringStylingTests.swift
  SimplenoteTests/NSStringSimplenoteTests.swift
  SimplenoteTests/OptionsTests.swift
Labels: debt

#1137 Persist scroll positions to a local file
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/EditorFactory.swift
  Simplenote/Classes/FileStorage.swift
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPObjectManager.h
  Simplenote/NoteScrollPositionCache.swift
  Simplenote/SPAppDelegate+Extensions.swift
  Simplenote/SPAppDelegate.m
  SimplenoteTests/NoteScrollPositionCacheTests.swift
Labels: [feature] editor, task

#1144 Add FileManager extension
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/EditorFactory.swift
  Simplenote/Classes/FileManager+Simplenote.swift
Labels: task

#1118 Localize keyword for tag search
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/SearchQuery+Simplenote.swift
Labels: [feature] search, enhancement

#1155 Fix bundler on develop
  Gemfile
  Gemfile.lock
Labels: tooling

#1156 Fix bundler on the 4.32 release branch
  Gemfile
  Gemfile.lock
Labels: tooling

#1153 Fix keyboard navigation in search bar
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
Labels: [feature] search, bug

#1066 Update screenshots automation with new details and iOS version – Local only
  SimplenoteScreenshots/SimplenoteScreenshots.swift
  SimplenoteScreenshots/SnapshotHelper.swift
  fastlane/Fastfile
  fastlane/appstoreres/assets/ipad_2nd_gen.png
  fastlane/appstoreres/assets/ipad_3rd_gen.png
  fastlane/appstoreres/assets/iphone_8_plus.png
  fastlane/appstoreres/assets/iphone_Xs_max.png
  fastlane/appstoreres/assets/styles/style.css
  fastlane/metadata/en-US/app_store_screenshot_1.txt
  fastlane/metadata/en-US/app_store_screenshot_2.txt
  fastlane/metadata/en-US/app_store_screenshot_3.txt
  fastlane/metadata/en-US/app_store_screenshot_4.txt
  fastlane/metadata/en-US/app_store_screenshot_5.txt
  fastlane/metadata/en-US/app_store_screenshot_6.txt
  fastlane/screenshots.json
Labels: tooling

#1157 Merge version 4.32 beta 2 into develop
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/cy.lproj/Localizable.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/el.lproj/Localizable.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/fa.lproj/Localizable.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/keywords.txt
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#1124 Added automated UI tests to the workspace
  .bundle/config
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcodeproj/xcshareddata/xcschemes/Simplenote.xcscheme
  Simplenote.xcodeproj/xcshareddata/xcschemes/SimplenoteScreenshots.xcscheme
  Simplenote.xcodeproj/xcshareddata/xcschemes/SimplenoteUITests.xcscheme
  SimplenoteUITests/AllNotes.swift
  SimplenoteUITests/AssertGeneric.swift
  SimplenoteUITests/EmailLogin.swift
  SimplenoteUITests/Generic.swift
  SimplenoteUITests/Info.plist
  SimplenoteUITests/NoteEditor.swift
  SimplenoteUITests/Preview.swift
  SimplenoteUITests/SimplenoteUITests.swift
  SimplenoteUITests/Trash.swift
  SimplenoteUITests/UIDs.swift
  SimplenoteUITests/XCTest+Extensions.swift
  TESTING-CHECKLIST.md
Labels: UIAutomation

#1149 Tags editor, bubblified: MK2
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/RoundedCrossButton.swift
  Simplenote/Classes/RoundedView.swift
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPTagCompletionPill.h
  Simplenote/Classes/SPTagCompletionPill.m
  Simplenote/Classes/SPTagEntryField.h
  Simplenote/Classes/SPTagEntryField.m
  Simplenote/Classes/SPTagPill.h
  Simplenote/Classes/SPTagPill.m
  Simplenote/Classes/SPTagStub.h
  Simplenote/Classes/SPTagStub.m
  Simplenote/Classes/SPTagView+Extensions.swift
  Simplenote/Classes/SPTagView.h
  Simplenote/Classes/SPTagView.m
  Simplenote/Classes/TagView.swift
  Simplenote/Classes/TagViewCell.swift
  Simplenote/Classes/UIColor+Studio.swift
  Simplenote/Simplenote-Bridging-Header.h
  Simplenote/Tags/NoteEditorTagListViewController.swift
  Simplenote/Tags/NoteEditorTagListViewController.xib
  Simplenote/UIView+Constraints.swift
Labels: Part of a WIP Feature, [feature] editor, [feature] tags

#1152 Make Interlink Popover UI reusable in tags editor
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/InterlinkProcessor.swift
  Simplenote/Classes/InterlinkViewController.swift
  Simplenote/Classes/InterlinkViewController.xib
  Simplenote/Classes/PopoverViewController.swift
  Simplenote/Classes/PopoverViewController.xib
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/SPNoteEditorViewController.m
  Simplenote/Classes/SPPopoverContainerViewController.h
  Simplenote/Classes/SPPopoverContainerViewController.m
  Simplenote/Classes/UIViewController+Simplenote.swift
  Simplenote/HuggableTableView.swift
  Simplenote/PopoverPresenter.swift
Labels: [feature] editor, interlinking

#1154 Tags editor, showing autocomplete: MK4
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/PassthruView.swift
  Simplenote/Classes/PopoverViewController.swift
  Simplenote/Classes/PopoverViewController.xib
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
  Simplenote/Classes/TagView.swift
  Simplenote/Classes/UIViewController+Simplenote.swift
  Simplenote/HuggableTableView.swift
  Simplenote/PopoverPresenter.swift
  Simplenote/Tags/NoteEditorTagListViewController.swift
  Simplenote/Tags/NoteEditorTagSuggestionsViewController.swift
  Simplenote/Tags/NoteEditorTagSuggestionsViewController.xib
Labels: [feature] tags

#1160 Tags editor, usability improvements: MK5
  Simplenote/Classes/SPTagEntryField.m
  Simplenote/Classes/TagView.swift
Labels: [feature] tags

#1143 Adding Existing Rake Binary of SwiftLint to Xcode
  Scripts/swiftlint.sh
  Simplenote.xcodeproj/project.pbxproj
Labels: analytics

#1138 Remove Trailing Comma on Tag
  RELEASE-NOTES.txt
  Simplenote/Classes/TagTextFieldInputValidator.swift
  Simplenote/Classes/TagView.swift
  Simplenote/TagListViewController.swift
  SimplenoteTests/Tags/TagTextFieldInputValidatorTests.swift
Labels: bug

#1162 Update secrets in release 4.32
  .configure
  .configure-files/google_cloud_keys.json.enc
Labels: tooling

#1159 Update search Sort Bar
  .configure
  .configure-files/google_cloud_keys.json.enc
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/PopoverViewController.swift
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
  Simplenote/Classes/SPNoteListViewController.m
  Simplenote/Classes/SPSortBar.swift
  Simplenote/Classes/SPSortBar.xib
  Simplenote/Classes/SortMode.swift
  Simplenote/Classes/SortModePickerViewController.swift
  Simplenote/Classes/SortModePickerViewController.xib
  Simplenote/PopoverPresenter.swift
Labels: [feature] note list, [feature] search

#1165 UIAutomation: Adjusted setUp() and setUpWithError() methods to speed up execution
  Simplenote.xcodeproj/xcshareddata/xcschemes/SimplenoteUITests.xcscheme
  SimplenoteUITests/AllNotes.swift
  SimplenoteUITests/AssertGeneric.swift
  SimplenoteUITests/EmailLogin.swift
  SimplenoteUITests/Generic.swift
  SimplenoteUITests/NoteEditor.swift
  SimplenoteUITests/Preview.swift
  SimplenoteUITests/SimplenoteUITests.swift
  SimplenoteUITests/Trash.swift
  SimplenoteUITests/UIDs.swift
Labels: UIAutomation

#1166 Update encoded SPCredentials
  .configure
  .configure-files/SPCredentials.swift.enc
Labels: tooling

#1167 Update secrets
  .configure
  .configure-files/SPCredentials.swift.enc
  .configure-files/app_store_connect_fastlane_api_key.json.enc
  .configure-files/google_cloud_keys.json.enc
Labels: tooling

#1168 Merge finalized release 4.32 into develop
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/Fastfile
  fastlane/metadata/ar-SA/keywords.txt
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#1171 "Tags&Search" tests automation MK1
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcodeproj/xcshareddata/xcschemes/SimplenoteUITests.xcscheme
  SimplenoteUITests/AllNotes.swift
  SimplenoteUITests/AssertGeneric.swift
  SimplenoteUITests/EmailLogin.swift
  SimplenoteUITests/Generic.swift
  SimplenoteUITests/NoteEditor.swift
  SimplenoteUITests/Preview.swift
  SimplenoteUITests/SimplenoteUITestsLogin.swift
  SimplenoteUITests/SimplenoteUITestsNoteEditor.swift
  SimplenoteUITests/SimplenoteUITestsSearch.swift
  SimplenoteUITests/SimplenoteUITestsTrash.swift
  SimplenoteUITests/Trash.swift
  SimplenoteUITests/UIDs.swift
  TESTING-CHECKLIST.md
Labels: UIAutomation

#1173 "Tags&Search" tests automation MK2
  Simplenote.xcodeproj/project.pbxproj
  SimplenoteUITests/AllNotes.swift
  SimplenoteUITests/Generic.swift
  SimplenoteUITests/NoteEditor.swift
  SimplenoteUITests/Sidebar.swift
  SimplenoteUITests/SimplenoteUITestsLogin.swift
  SimplenoteUITests/SimplenoteUITestsNoteEditor.swift
  SimplenoteUITests/SimplenoteUITestsSearch.swift
  SimplenoteUITests/SimplenoteUITestsTrash.swift
  SimplenoteUITests/Trash.swift
  SimplenoteUITests/UIDs.swift
Labels: UIAutomation
