Repository Automattic/simplenote-ios, pull requests merged in 2021-03, with the labels that each got.

#1174 UI Tests Refactor: Renaming AllNotes to NoteList
  Simplenote.xcodeproj/project.pbxproj
  SimplenoteUITests/NotesList.swift
  SimplenoteUITests/SimplenoteUITestsLogin.swift
  SimplenoteUITests/SimplenoteUITestsNoteEditor.swift
  SimplenoteUITests/SimplenoteUITestsSearch.swift
  SimplenoteUITests/SimplenoteUITestsTrash.swift
Labels: UIAutomation

#1176 Automated two more Search tests
  SimplenoteUITests/AssertGeneric.swift
  SimplenoteUITests/EmailLogin.swift
  SimplenoteUITests/NotesList.swift
  SimplenoteUITests/SimplenoteUITestsSearch.swift
  SimplenoteUITests/Trash.swift
  TESTING-CHECKLIST.md
Labels: UIAutomation

#1181 UI Automation Refactor: Using optionals in return values
  SimplenoteUITests/AssertGeneric.swift
  SimplenoteUITests/Generic.swift
  SimplenoteUITests/NotesList.swift
  SimplenoteUITests/SimplenoteUITestsLogin.swift
  SimplenoteUITests/SimplenoteUITestsSearch.swift
  SimplenoteUITests/UIDs.swift
Labels: UIAutomation

#1183 "Tags&Search" tests automation MK4
  SimplenoteUITests/AssertGeneric.swift
  SimplenoteUITests/Generic.swift
  SimplenoteUITests/NotesList.swift
  SimplenoteUITests/SimplenoteUITestsSearch.swift
  SimplenoteUITests/Trash.swift
  SimplenoteUITests/UIDs.swift
  TESTING-CHECKLIST.md
Labels: UIAutomation

#1184 "Tags&Search" tests automation MK5
  SimplenoteUITests/Generic.swift
  SimplenoteUITests/NotesList.swift
  SimplenoteUITests/SimplenoteUITestsSearch.swift
  TESTING-CHECKLIST.md
Labels: UIAutomation

#1175 Issue/1407 reference count incorrect
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/String+Simplenote.swift
  Simplenote/Information/NoteInformationController.swift
  Simplenote/Note+Links.swift
  SimplenoteShare/ViewControllers/ShareViewController.swift
  SimplenoteTests/MockupStorage+Sample.swift
  SimplenoteTests/NoteLinkTests.swift
  SimplenoteTests/StringSimplenoteTests.swift
Labels: bug

#1188 [Tooling] Mark *.enc configure files as binary
  .gitattributes
Labels: tooling

#1182 SignUp flow update
  Podfile
  Podfile.lock
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/MagicLinkAuthenticator.swift
  Simplenote/Classes/NSMutableAttributedString+Simplenote.swift
  Simplenote/Classes/RemoteConstants.swift
  Simplenote/Classes/SPAuthHandler.swift
  Simplenote/Classes/SPAuthViewController.swift
  Simplenote/Classes/SignupRemote.swift
  Simplenote/Classes/SignupVerificationViewController.swift
  Simplenote/Classes/SignupVerificationViewController.xib
  Simplenote/Classes/SimplenoteConstants.swift
  Simplenote/SPAppDelegate+Extensions.swift
  Simplenote/SPAppDelegate.m
  Simplenote/Verification/AccountVerificationRemote.swift
Labels: [feature] login, [feature] security

#1189 Don't create a welcome note
  Simplenote/SPAppDelegate.m
Labels: [feature] login, task

#1192 Merge version 4.33 beta 1 into develop
  RELEASE-NOTES.txt
  Scripts/extract_release_notes.rb
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/en.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases

#1191 Improve Note Contextual Action VoiceOver Titles
  Simplenote/Classes/SPNoteListViewController+Extensions.swift
Labels: accessibility, bug

#1197 Add editorconfig
  .editorconfig
Labels: tooling

#1185 Project: In App Notifications - View Implementation and Styling
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/UIColor+Studio.swift
  Simplenote/Notice.swift
  Simplenote/NoticeAction.swift
  Simplenote/NoticeView.swift
  Simplenote/NoticeView.xib
  Simplenote/UIView+Constraints.swift
Labels: In App Notifications, enhancement

#1196 Accessibility Color updates
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPMarkdownParser.m
  Simplenote/Resources/markdown-dark-contrast.css
  Simplenote/Resources/markdown-dark.css
  Simplenote/Resources/markdown-default-contrast.css
  Simplenote/Resources/markdown-default.css
Labels: accessibility, bug

#1201 Merge finalized release 4.33 into develop
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/cy.lproj/Localizable.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/el.lproj/Localizable.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/fa.lproj/Localizable.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/Fastfile
  fastlane/metadata/ar-SA/keywords.txt
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/app_store_screenshot_1.txt
  fastlane/metadata/en-US/app_store_screenshot_2.txt
  fastlane/metadata/en-US/app_store_screenshot_3.txt
  fastlane/metadata/en-US/app_store_screenshot_4.txt
  fastlane/metadata/en-US/app_store_screenshot_5.txt
  fastlane/metadata/en-US/app_store_screenshot_6.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#1200 Added support for accessibility three finger navigation
  Simplenote/Classes/SPNoteEditorViewController+Extensions.swift
Labels: accessibility, bug

#1210 Fix issue where unit test log out simulator
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPTracker.h
  Simplenote/Classes/SPTracker.m
  Simplenote/KeychainMigrator.swift
  Simplenote/SPAppDelegate.m
  SimplenoteTests/KeychainMigratorTests.swift
Labels: Testing, bug

#1203 Add Notice Controller and Presenter to In App Notifications
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Notice.swift
  Simplenote/NoticeController.swift
  Simplenote/NoticePresenter.swift
  Simplenote/NoticeView.swift
  Simplenote/NoticeView.xib
  Simplenote/SPAppDelegate+Extensions.swift
  Simplenote/SPAppDelegate.m
  Simplenote/TimerFactory.swift
  Simplenote/UIView+Constraints.swift
  SimplenoteTests/NoticeContorllerTests.swift
Labels: In App Notifications

#1213 Fixes crash when editor loads in search mode but can not highlight search value
  Simplenote/Classes/SPNoteEditorViewController.m
Labels: bug, crash

#1190 Adding `XCUIElementQuery: Sequence` extension
  Simplenote.xcodeproj/project.pbxproj
  SimplenoteUITests/Extensions.swift
  SimplenoteUITests/Generic.swift
  SimplenoteUITests/NoteEditor.swift
  SimplenoteUITests/NoteList.swift
  SimplenoteUITests/Preview.swift
  SimplenoteUITests/SimplenoteUITestsNoteEditor.swift
  SimplenoteUITests/SimplenoteUITestsSearch.swift
  SimplenoteUITests/XCTest+Extensions.swift
Labels: UIAutomation

#1187 UI automation refactor mk1: Using `trackTest()` and `trackStep()` in older tests
  Simplenote.xcodeproj/project.pbxproj
  SimplenoteUITests/Extensions.swift
  SimplenoteUITests/Generic.swift
  SimplenoteUITests/NoteEditor.swift
  SimplenoteUITests/NoteList.swift
  SimplenoteUITests/Preview.swift
  SimplenoteUITests/SimplenoteUITestsLogin.swift
  SimplenoteUITests/SimplenoteUITestsNoteEditor.swift
  SimplenoteUITests/SimplenoteUITestsTrash.swift
  SimplenoteUITests/XCTest+Extensions.swift
Labels: UIAutomation

#1208 NoticeController tests
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/NoticeController.swift
  Simplenote/NoticePresenter.swift
  Simplenote/NoticeView.swift
  SimplenoteTests/NoticeContorllerTests.swift
  SimplenoteTests/NoticeControllerTests.swift
Labels: In App Notifications, enhancement

#1220 Merge release 4.34 beta 1 into develop
  RELEASE-NOTES.txt
  Scripts/extract_release_notes.rb
  Scripts/localize.py
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases

#1219 Merge 4.33.1 hotfix into trunk
  RELEASE-NOTES.txt
  Simplenote/Classes/SPNoteEditorViewController.m
  config/Version.Public.xcconfig
  fastlane/Deliverfile
Labels: Releases

#1215 UI automation maintenance: new locator for `Trash Note` button
  SimplenoteUITests/Generic.swift
  SimplenoteUITests/NoteList.swift
  SimplenoteUITests/Trash.swift
  SimplenoteUITests/UIDs.swift
Labels: UIAutomation
