Repository Automattic/simplenote-ios, pull requests merged in 2022-11, with the labels that each got.

#1492 Simplenote Sustainer UI
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPSettingsViewController+Extensions.swift
  Simplenote/Classes/SPSettingsViewController.m
  Simplenote/Classes/SPSidebarContainerViewController.m
  Simplenote/Classes/UIColor+Studio.swift
  Simplenote/SustainerView.swift
  Simplenote/SustainerView.xib
  Simplenote/TagListViewController.swift
Labels: enhancement

#1493 Sustainer IAP
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcodeproj/xcshareddata/xcschemes/Simplenote.xcscheme
  Simplenote/Classes/SPNotifications.h
  Simplenote/Classes/SPNotifications.m
  Simplenote/Classes/SPSettingsViewController+Extensions.swift
  Simplenote/Classes/SPSettingsViewController.m
  Simplenote/Classes/Simperium+Simplenote.h
  Simplenote/Classes/UITableView+Simplenote.swift
  Simplenote/CrashLogging.swift
  Simplenote/Preferences+IAP.swift
  Simplenote/Preferences.m
  Simplenote/SPAppDelegate+Extensions.swift
  Simplenote/SPAppDelegate.m
  Simplenote/SPPrivacyViewController.swift
  Simplenote/StoreConstants.swift
  Simplenote/StoreManager.swift
  Simplenote/StoreProduct.swift
  Simplenote/TagListViewController.swift
  Simplenote/TestConfiguration.storekit
Labels: IAP

#1496 Sustainer: Product Alert
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPSettingsViewController+Extensions.swift
  Simplenote/SPTracker+Extensions.swift
  Simplenote/StoreManager.swift
  Simplenote/TagListViewController.swift
  Simplenote/UIAlertController+Sustainer.swift
Labels: IAP

#1498 Sustainer: Purchase Restoration
  Simplenote/Classes/SPSettingsViewController+Extensions.swift
  Simplenote/Classes/SPSettingsViewController.m
  Simplenote/StoreManager.swift
Labels: IAP

#1501 UIAlertController+Sustainer: Switching to Alert
  Simplenote/UIAlertController+Sustainer.swift
Labels: crash

#1502 Merge 4.48.0.2 into trunk
  RELEASE-NOTES.txt
  Simplenote/Classes/SPSettingsViewController+Extensions.swift
  Simplenote/Classes/SPSettingsViewController.m
  Simplenote/Resources/release_notes.txt
  Simplenote/StoreManager.swift
  Simplenote/UIAlertController+Sustainer.swift
  config/Version.Public.xcconfig
  fastlane/Deliverfile
  fastlane/Fastfile
  fastlane/download_metadata.swift
Labels: Releases

#1505 Merge 4.48 strings into trunk
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/en.lproj/Localizable.strings
  fastlane/Fastfile
Labels: tooling, Releases

#1506 Merge updated 4.48 release notes into trunk
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
Labels: Releases

#1504 [UI Tests] Adjust UI tests to support iOS 16 & switch to iPhone SE
  .buildkite/pipeline.yml
  SimplenoteUITests/AssertGeneric.swift
  SimplenoteUITests/NoteEditor.swift
  SimplenoteUITests/Sidebar.swift
  SimplenoteUITests/SimplenoteUITestsNoteEditor.swift
Labels: UIAutomation

#1511 Merge 4.48 final into trunk
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/cy.lproj/Localizable.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/el.lproj/Localizable.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/fa.lproj/Localizable.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases
