Repository Automattic/simplenote-ios, pull requests merged in 2024-07, with the labels that each got.

#1599 Login with Passkeys!!
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPAuthHandler.swift
  Simplenote/Classes/SPAuthViewController.swift
  Simplenote/Classes/SPAuthViewController.xib
  Simplenote/Classes/SPOnboardingViewController.swift
  Simplenote/Classes/SPSettingsViewController+Extensions.swift
  Simplenote/Classes/SPSettingsViewController.h
  Simplenote/Classes/SPSettingsViewController.m
  Simplenote/Classes/SPSheetController.swift
  Simplenote/Classes/SPSheetController.xib
  Simplenote/Classes/SimplenoteConstants.swift
  Simplenote/Classes/String+Simplenote.swift
  Simplenote/Data+Simplenote.swift
  Simplenote/PasskeyAuthChallenge.swift
  Simplenote/PasskeyAuthResponse.swift
  Simplenote/PasskeyAuthenticator.swift
  Simplenote/PasskeyRegistrationChallenge.swift
  Simplenote/PasskeyRegistrationResponse.swift
  Simplenote/PasskeyRemote.swift
  Simplenote/PasskeyVerifyResponse.swift
  Simplenote/Remote.swift
  Simplenote/Supporting Files/Simplenote-Internal.entitlements
  Simplenote/Supporting Files/Simplenote.entitlements
Labels: [feature] login

#1609 Universal Links
  .swiftlint.yml
  Simplenote/Classes/MagicLinkAuthenticator.swift
  Simplenote/SPAppDelegate+Extensions.swift
  Simplenote/SPAppDelegate.m
  Simplenote/Supporting Files/Simplenote-Internal.entitlements
  Simplenote/Supporting Files/Simplenote.entitlements
Labels: enhancement

#1598 Magic Link Login
  .swiftlint.yml
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/MagicLinkAuthenticator.swift
  Simplenote/Classes/SPAuthHandler.swift
  Simplenote/Classes/SPAuthViewController.swift
  Simplenote/Classes/SPOnboardingViewController.swift
  Simplenote/Classes/SPSettingsViewController+Extensions.swift
  Simplenote/Classes/SPTracker.h
  Simplenote/Classes/SPTracker.m
  Simplenote/Classes/SimplenoteConstants.swift
  Simplenote/LoginRemote.swift
  Simplenote/MagicLinkRequestedView.swift
  Simplenote/Remote.swift
  Simplenote/RemoteError.swift
  Simplenote/UIButton+Simplenote.swift
  SimplenoteUITests/EmailLogin.swift
  SimplenoteUITests/UIDs.swift
Labels: enhancement

#1606 Invalid Authentication Link Alert
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/MagicLinkAuthenticator.swift
  Simplenote/Classes/SPAuthViewController.swift
  Simplenote/Classes/SPOnboardingViewController.swift
  Simplenote/MagicLinkInvalidView.swift
Labels: enhancement

#1610 Passkeys: Errors, Alerts, UI Feedback
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPAuthViewController.swift
  Simplenote/Classes/SPSettingsViewController+Extensions.swift
  Simplenote/Classes/SPSettingsViewController.h
  Simplenote/PasskeyAuthenticator.swift
  Simplenote/PasskeyRegistrator.swift
  Simplenote/PasskeyRemote.swift
  Simplenote/SPModalActivityIndicator.swift
  Simplenote/Simplenote-Bridging-Header.h
  Simplenote/Supporting Files/Simplenote-Internal.entitlements
  Simplenote/Supporting Files/Simplenote.entitlements
Labels: [feature] login

#1612 Magic Links: Wires new Endpoints
  Simplenote/Classes/MagicLinkAuthenticator.swift
  Simplenote/LoginRemote.swift
Labels: enhancement

#1613 Magic Links: Adjusting Copy
  Simplenote/Classes/MagicLinkAuthenticator.swift
  Simplenote/Classes/SPAuthViewController.swift
  Simplenote/Classes/SPTracker.h
  Simplenote/Classes/SPTracker.m
  Simplenote/MagicLinkInvalidView.swift
Labels: enhancement

#1616 Refactored passkey remote to handle all json conversions for passkeys
  Simplenote/PasskeyRegistrationResponse.swift
  Simplenote/PasskeyRegistrator.swift
  Simplenote/PasskeyRemote.swift
Labels: [feature] login

#1614 Login Flow: Splitting Username / Password Interfaces
  RELEASE-NOTES.txt
  Simplenote/Classes/SPAuthViewController.swift
  Simplenote/Classes/SPAuthViewController.xib
  Simplenote/Classes/SPOnboardingViewController.swift
  SimplenoteUITests/EmailLogin.swift
  SimplenoteUITests/SimplenoteUITestsLogin.swift
  SimplenoteUITests/UIDs.swift
Labels: enhancement

#1617 Login: Code Header
  Simplenote/AuthenticationMode.swift
  Simplenote/Classes/MagicLinkAuthenticator.swift
  Simplenote/Classes/SPAuthViewController.swift
  Simplenote/Classes/SPAuthViewController.xib
  Simplenote/Classes/SPOnboardingViewController.swift
Labels: enhancement

#1618 Magic Links: Handling 429
  Simplenote/AuthenticationMode.swift
  Simplenote/Classes/SPAuthError.swift
  Simplenote/Classes/SPAuthViewController.swift
  SimplenoteUITests/EmailLogin.swift
  SimplenoteUITests/UIDs.swift
Labels: enhancement

#1619 Login: Addressing Debt
  Simplenote/AuthenticationMode.swift
  Simplenote/Classes/SPAuthViewController.swift
Labels: debt

#1620 Passkeys: Update endpoint paths
  Simplenote/Classes/SimplenoteConstants.swift
Labels: bug

#1622 AuthViewController: Adds missing Header
  Simplenote/Classes/SPAuthViewController.swift
Labels: enhancement

#1623 Auth: Updates Error Handling
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPAuthError.swift
  Simplenote/Classes/SPAuthHandler.swift
  Simplenote/Classes/SPAuthViewController.swift
  Simplenote/Classes/SPSettingsViewController+Extensions.swift
  Simplenote/Remote.swift
  Simplenote/RemoteError.swift
  Simplenote/UIAlertController+Auth.swift
  SimplenoteTests/RemoteResult+TestHelpers.swift
  SimplenoteTests/SignupRemoteTests.swift
  SimplenoteTests/Verification/AccountVerificationRemoteTests.swift
Labels: enhancement

#1624 Integrates SimplenoteEndpoints Swift Package
  .buildkite/pipeline.yml
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Simplenote/AccountRemote.swift
  Simplenote/Classes/MagicLinkAuthenticator.swift
  Simplenote/Classes/RemoteConstants.swift
  Simplenote/Classes/SPAuthError.swift
  Simplenote/Classes/SPAuthHandler.swift
  Simplenote/Classes/SPAuthViewController.swift
  Simplenote/Classes/SPSettingsViewController+Extensions.swift
  Simplenote/Classes/SignupRemote.swift
  Simplenote/Controllers/AccountDeletionController.swift
  Simplenote/LoginRemote.swift
  Simplenote/Remote.swift
  Simplenote/RemoteError.swift
  Simplenote/SPUser+UserProtocol.swift
  Simplenote/URLRequest+Simplenote.swift
  Simplenote/Verification/AccountVerificationController.swift
  SimplenoteTests/Network/MockURLSession.swift
  SimplenoteTests/Network/MockURLSessionDataTask.swift
  SimplenoteTests/RemoteResult+TestHelpers.swift
  SimplenoteTests/SignupRemoteTests.swift
  SimplenoteTests/Verification/AccountVerificationControllerTests.swift
  SimplenoteTests/Verification/AccountVerificationRemoteTests.swift
  SimplenoteTests/Verification/Helpers/MockAccountVerificationRemote.swift
Labels: debt, [feature] login

#1625 Authentication: Updates Expired Code Handling
  Simplenote/Classes/SPAuthViewController.swift
  Simplenote/UIAlertController+Auth.swift
Labels: [feature] login

#1628 Remove `strings` expected encoding and add ASC metadata source
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Resources/AppStoreStrings.pot
  fastlane/Fastfile
Labels: Releases
