Repository Automattic/simplenote-ios, pull requests merged in 2024-10, with the labels that each got.

#1666 [Tooling] Use bot for release management git operations
  .buildkite/commands/configure-for-release.sh
  .buildkite/commands/configure-git-for-release-management.sh
  .buildkite/release-pipelines/complete-code-freeze.yml
  .buildkite/release-pipelines/new-beta-release.yml
  .buildkite/release-pipelines/start-code-freeze.yml
  .xcode-version
Labels: tooling

#1663 Convert dependency check annotation from `h3` to `p`
  fastlane/lanes/release.rb
Labels: tooling

#1667 Update release notes for 4.55
  fastlane/metadata/default/release_notes.txt
Labels: Releases

#1669 Convert the bool `beta` flag to string for Buildkite
  fastlane/lanes/release.rb
Labels: tooling

#1670 Pass both keys and values in `buildkite_pipeline_upload` as strings
  fastlane/lanes/release.rb
Labels: tooling, Releases

#1673 Run `buildkite_pipeline_upload` on branch HEAD
  fastlane/lanes/release.rb
Labels: tooling, Releases

#1675 Force release builds in CI to checkout release branch
  .buildkite/release-build.yml
  config/Version.Public.xcconfig
  fastlane/lanes/release.rb
Labels: tooling, Releases

#1679 [Tooling] Call `use-bot-for-git` script directly
  .buildkite/commands/configure-for-release.sh
  .buildkite/release-pipelines/complete-code-freeze.yml
  .buildkite/release-pipelines/finalize-release.yml
  .buildkite/release-pipelines/new-beta-release.yml
  .buildkite/release-pipelines/publish-release.yml
  .buildkite/release-pipelines/start-code-freeze.yml
  .buildkite/release-pipelines/update-metadata-on-app-store-connect.yml
Labels: tooling
