Repository Automattic/simplenote-ios, pull requests merged in 2024-04, with the labels that each got.

#1558 Persist was sustainer value in preferences
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Classes/SPSettingsViewController+Extensions.swift
  Simplenote/Classes/SPSettingsViewController.m
  Simplenote/Classes/Simperium+Simplenote.swift
  Simplenote/Classes/UserDefaults+Simplenote.swift
  Simplenote/Preferences+IAP.swift
  Simplenote/Preferences.h
  Simplenote/Preferences.m
  Simplenote/SPAppDelegate+Extensions.swift
  Simplenote/SPAppDelegate.h
  Simplenote/SPAppDelegate.m
  Simplenote/Simplenote.xcdatamodeld/.xccurrentversion
  Simplenote/Simplenote.xcdatamodeld/Simplenote 7.xcdatamodel/contents
Labels: dawn

#1559 Updated rake file to fix bundle install --path depreciation
  Rakefile
Labels: tooling

#1560 Fixed an issue where note tableview cells highlighted before selection
  RELEASE-NOTES.txt
  Simplenote/Classes/SPNoteTableViewCell.swift
Labels: bug, [feature] note list

#1507 Apply RuboCop corrections
  .rubocop.yml
  Gemfile.lock
  Rakefile
  fastlane/Fastfile
Labels: tooling

#1564 New note widget lock screen
  RELEASE-NOTES.txt
  Simplenote/Classes/PinLock/PinLockVerifyController.swift
  Simplenote/Classes/PinLock/PinLockViewController.swift
  Simplenote/SPAppDelegate+Extensions.swift
  Simplenote/SPAppDelegate.h
  Simplenote/SPAppDelegate.m
  Simplenote/URL+Simplenote.swift
Labels: [feature] Widgets

#1562 Option to disable spotlight search
  RELEASE-NOTES.txt
  Simplenote/Classes/CSSearchable+Helpers.swift
  Simplenote/Classes/SPSettingsViewController+Extensions.swift
  Simplenote/Classes/SPSettingsViewController.m
  Simplenote/Classes/UserDefaults+Simplenote.swift
  Simplenote/Options.swift
  Simplenote/SPAppDelegate.m
  Simplenote/Simplenote-Bridging-Header.h
Labels: [feature] search

#1561 Fastlane `match`: Migrate Code Signing from Google Cloud to S3
  .bundle/config
  Gemfile.lock
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/Matchfile
  fastlane/env/user.env-example
Labels: tooling

#1571 Merge 4.51 code freeze into trunk
  RELEASE-NOTES.txt
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  config/Version.Public.xcconfig
Labels: Releases

#1572 Add `template_name` parameter to `fastlane match` call
  fastlane/Fastfile
Labels: tooling

#1574 Merge 4.51 final into trunk
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  config/Version.Public.xcconfig
Labels: Releases

#1573 Drop collaboration Step 1
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/BannerView.swift
  Simplenote/BannerView.xib
  Simplenote/Classes/SPAddCollaboratorsViewController.h
  Simplenote/Classes/SPAddCollaboratorsViewController.m
  Simplenote/Classes/SPEntryListViewController.h
  Simplenote/Classes/SPEntryListViewController.m
  Simplenote/SPAddCollaboratorsViewController.swift
Labels: [feature] collaborate

#1576 Apple Privacy manifests
  Gemfile
  Gemfile.lock
  Podfile.lock
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Resources/PrivacyInfo.xcprivacy
  SimplenoteIntents/Supporting Files/PrivacyInfo.xcprivacy
  SimplenoteWidgets/Supporting Files/PrivacyInfo.xcprivacy
Labels: privacy
