Repository Automattic/simplenote-ios, pull requests merged in 2024-11, with the labels that each got.

#1680 Fix version file path in `release_is_hotfix?` helper
  fastlane/lanes/release.rb
Labels: tooling, Releases

#1681 Merge release/4.55 into trunk
  .buildkite/commands/configure-for-release.sh
  .buildkite/release-pipelines/complete-code-freeze.yml
  .buildkite/release-pipelines/finalize-release.yml
  .buildkite/release-pipelines/new-beta-release.yml
  .buildkite/release-pipelines/publish-release.yml
  .buildkite/release-pipelines/start-code-freeze.yml
  .buildkite/release-pipelines/update-metadata-on-app-store-connect.yml
  config/Version.Public.xcconfig
  fastlane/lanes/release.rb
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#1683 Allow bypassing confirmation in upload metadata via CI
  .buildkite/release-pipelines/update-metadata-on-app-store-connect.yml
  fastlane/Fastfile
Labels: tooling

#1686 [Tooling] Update CI image from `xcode-16.1-rc.1` to `xcode-16.1-v4`
  .buildkite/shared-pipeline-vars
  .xcode-version
Labels: tooling
