Repository Automattic/simplenote-ios, pull requests merged in 2024-09, with the labels that each got.

#1645 Merge release/4.52 into trunk
  config/Version.Public.xcconfig
  fastlane/Fastfile
  fastlane/lanes/localization.rb
  fastlane/lanes/release.rb
  fastlane/metadata/default/support_url.txt
Labels: Releases

#1644 Add method for milestone moving
  fastlane/lanes/release.rb
Labels: tooling

#1647 Make Fastlane the single source of truth for release notes
  Scripts/extract_release_notes.rb
  Simplenote/Resources/release_notes.txt
  fastlane/Fastfile
  fastlane/lanes/build.rb
  fastlane/lanes/localization.rb
  fastlane/lanes/release.rb
Labels: tooling, i18n

#1643 [Tooling] Run Danger on Buildkite Linter Agent
  .buildkite/pipeline.yml
  .github/workflows/run-danger.yml
  Gemfile.lock
Labels: tooling

#1646 Run code freeze in CI
  .buildkite/commands/checkout-release-branch.sh
  .buildkite/commands/configure-environment.sh
  .buildkite/commands/configure-git-for-release-management.sh
  .buildkite/pipeline.yml
  .buildkite/release-build.yml
  .buildkite/release-pipelines/complete-code-freeze.yml
  .buildkite/release-pipelines/start-code-freeze.yml
  fastlane/Fastfile
  fastlane/lanes/build.rb
  fastlane/lanes/ci_releases.rb
  fastlane/lanes/release.rb
Labels: tooling, Releases

#1649 Run start code freeze on `tumblr-metal` agent
  .buildkite/commands/configure-environment.sh
  .buildkite/commands/configure-git-for-release-management.sh
  .buildkite/release-pipelines/complete-code-freeze.yml
  .buildkite/release-pipelines/start-code-freeze.yml
Labels: tooling

#1650 Pass `wpmobilebot` explicitly in `start-code-freeze.yml`
  .buildkite/release-pipelines/start-code-freeze.yml
Labels: tooling

#1651 Update `release_notes.txt` with copy for 4.53
  fastlane/metadata/default/release_notes.txt
Labels: Releases

#1653 Make method to trigger Buildkite build annotate the caller
  .buildkite/release-pipelines/start-code-freeze.yml
  fastlane/lanes/release.rb
Labels: tooling, Releases

#1657 Update California privacy policy link
  RELEASE-NOTES.txt
  Simplenote/Classes/SPAboutViewController.swift
  Simplenote/Resources/AppStoreStrings.pot
  fastlane/appstoreres/metadata/source/description.txt
  fastlane/metadata/ar-SA/description.txt
  fastlane/metadata/de-DE/description.txt
  fastlane/metadata/default/description.txt
  fastlane/metadata/es-ES/description.txt
  fastlane/metadata/fr-FR/description.txt
  fastlane/metadata/he/description.txt
  fastlane/metadata/id/description.txt
  fastlane/metadata/it/description.txt
  fastlane/metadata/ja/description.txt
  fastlane/metadata/ko/description.txt
  fastlane/metadata/nl-NL/description.txt
  fastlane/metadata/pt-BR/description.txt
  fastlane/metadata/ru/description.txt
  fastlane/metadata/sv/description.txt
  fastlane/metadata/tr/description.txt
  fastlane/metadata/zh-Hans/description.txt
  fastlane/metadata/zh-Hant/description.txt
Labels: groundskeeping, privacy

#1656 Add fall back login with username and password option to login
  Simplenote/AuthenticationMode.swift
  Simplenote/Classes/SPAuthViewController.swift
Labels: [feature] login

#1660 Updated AppIcon assets to work with new ios 18 styles
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/Contents.json
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/Icon-App-20x20.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/Icon-App-20x20@2x-1.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/Icon-App-20x20@2x.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/Icon-App-20x20@3x.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/Icon-App-29x29-1.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/Icon-App-29x29.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/Icon-App-29x29@2x-1.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/Icon-App-29x29@2x.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/Icon-App-29x29@3x.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/Icon-App-40x40.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/Icon-App-40x40@2x-2.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/Icon-App-40x40@2x.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/Icon-App-40x40@3x.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/Icon-App-60x60@2x.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/Icon-App-60x60@3x.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/Icon-App-76x76.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/Icon-App-76x76@2x.png
  Simplenote/Icons.xcassets/AppIcon-Beta.appiconset/Icon-App-83.5x83.5@2x.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/Contents.json
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-20x20.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-20x20@2x-1.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-29x29-1.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-29x29.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-29x29@2x-1.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-40x40.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-40x40@2x-1.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-76x76.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  Simplenote/Icons.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
Labels: debt

#1659 Merge release/4.53 into trunk
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/cy.lproj/Localizable.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/el.lproj/Localizable.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/fa.lproj/Localizable.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
  config/Version.Public.xcconfig
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#1655 Add CI pipeline to generate a new beta
  .buildkite/release-pipelines/new-beta-release.yml
  Gemfile
  Gemfile.lock
  fastlane/Fastfile
  fastlane/lanes/build.rb
  fastlane/lanes/ci_releases.rb
  fastlane/lanes/release.rb
Labels: tooling

#1661 Add CI automation for beta releases + automation improvements
  .buildkite/release-pipelines/new-beta-release.yml
  Gemfile
  Gemfile.lock
  fastlane/Fastfile
  fastlane/lanes/build.rb
  fastlane/lanes/ci_releases.rb
  fastlane/lanes/release.rb
Labels: tooling
