Repository Automattic/simplenote-ios, pull requests merged in 2024-08, with the labels that each got.

#1634 Merge 4.52 code freeze into `trunk`
  .buildkite/commands/release-build.sh
  .buildkite/release-build.yml
  .configure
  .rubocop.yml
  Gemfile
  Gemfile.lock
  RELEASE-NOTES.txt
  Simplenote.xcodeproj/project.pbxproj
  Simplenote/Resources/AppStoreStrings.pot
  Simplenote/Resources/release_notes.txt
  Simplenote/en.lproj/Localizable.strings
  config/Project.Release.xcconfig
  config/Simplenote.release.xcconfig
  config/Version.Public.xcconfig
  fastlane/Fastfile
  fastlane/example.env
  fastlane/lanes/build.rb
  fastlane/lanes/localization.rb
  fastlane/lanes/release.rb
  fastlane/lib/env_manager.rb
Labels: Releases

#1635 Split building for ASC from uploading to TestFlight and run as separate CI steps
  .buildkite/commands/release-build.sh
  .buildkite/commands/release-upload.sh
  .buildkite/release-build.yml
  config/Version.Public.xcconfig
  fastlane/Fastfile
  fastlane/lanes/build.rb
Labels: tooling, Releases

#1630 Magic Links: Limit character input on login code text field
  Simplenote/Classes/SPAuthViewController.swift
Labels: [feature] login

#1632 Markdown animations and swipe for RTL languages
  Simplenote/Classes/SPInteractivePushPopAnimationController.m
  Simplenote/Classes/SPNoteEditorViewController.m
Labels: [feature] markdown

#1633 Prepare app to build on Xcode 16
  Simplenote.xcodeproj/project.pbxproj
  Simplenote.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: tooling

#1631 Validate deleting tag before completing
  Simplenote/TagListViewController.swift
Labels: [feature] tags

#1638 Updates Translations
  Simplenote/ar.lproj/Localizable.strings
  Simplenote/cy.lproj/Localizable.strings
  Simplenote/de.lproj/Localizable.strings
  Simplenote/el.lproj/Localizable.strings
  Simplenote/es.lproj/Localizable.strings
  Simplenote/fa.lproj/Localizable.strings
  Simplenote/fr.lproj/Localizable.strings
  Simplenote/he.lproj/Localizable.strings
  Simplenote/id.lproj/Localizable.strings
  Simplenote/it.lproj/Localizable.strings
  Simplenote/ja.lproj/Localizable.strings
  Simplenote/ko.lproj/Localizable.strings
  Simplenote/nl.lproj/Localizable.strings
  Simplenote/pt-BR.lproj/Localizable.strings
  Simplenote/ru.lproj/Localizable.strings
  Simplenote/sv.lproj/Localizable.strings
  Simplenote/tr.lproj/Localizable.strings
  Simplenote/zh-Hans-CN.lproj/Localizable.strings
  Simplenote/zh-Hant-TW.lproj/Localizable.strings
Labels: i18n

#1639 Fix broken localization automation in release branch
  .gitignore
  Scripts/localize.py
  fastlane/Fastfile
  fastlane/download_metadata.swift
  fastlane/lanes/localization.rb
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-US/description.txt
  fastlane/metadata/en-US/keywords.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/en-US/subtitle.txt
Labels: tooling, Releases
